/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NRPPA-IEs"
 * 	found in "e2ap-v01.01.asn1"
 * 	`asn1c -gen-PER -fcompound-names -findirect-choice -fno-include-deps`
 */

#include "AbortTransmission.h"

#include "ProtocolIE-Single-Container.h"
static asn_oer_constraints_t asn_OER_type_AbortTransmission_constr_1 CC_NOTUSED = {
	{ 0, 0 },
	-1};
static asn_per_constraints_t asn_PER_type_AbortTransmission_constr_1 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 2,  2,  0,  2 }	/* (0..2) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_TYPE_member_t asn_MBR_AbortTransmission_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct AbortTransmission, choice.deactivateSRSResourceSetID),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_SRSResourceSetID,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"deactivateSRSResourceSetID"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct AbortTransmission, choice.releaseALL),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NULL,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"releaseALL"
		},
	{ ATF_POINTER, 0, offsetof(struct AbortTransmission, choice.choice_extension),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ProtocolIE_Single_Container_2907P0,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"choice-extension"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_AbortTransmission_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* deactivateSRSResourceSetID */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* releaseALL */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 } /* choice-extension */
};
static asn_CHOICE_specifics_t asn_SPC_AbortTransmission_specs_1 = {
	sizeof(struct AbortTransmission),
	offsetof(struct AbortTransmission, _asn_ctx),
	offsetof(struct AbortTransmission, present),
	sizeof(((struct AbortTransmission *)0)->present),
	asn_MAP_AbortTransmission_tag2el_1,
	3,	/* Count of tags in the map */
	0, 0,
	-1	/* Extensions start */
};
asn_TYPE_descriptor_t asn_DEF_AbortTransmission = {
	"AbortTransmission",
	"AbortTransmission",
	&asn_OP_CHOICE,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	{ &asn_OER_type_AbortTransmission_constr_1, &asn_PER_type_AbortTransmission_constr_1, CHOICE_constraint },
	asn_MBR_AbortTransmission_1,
	3,	/* Elements count */
	&asn_SPC_AbortTransmission_specs_1	/* Additional specs */
};

