/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NRPPA-IEs"
 * 	found in "38455.asn"
 * 	`asn1c -no-gen-OER -fcompound-names -no-gen-example -findirect-choice
 * -fno-include-deps -D nrppa`
 */

#ifndef _AperiodicSRSResourceTrigger_H_
#define _AperiodicSRSResourceTrigger_H_

#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* AperiodicSRSResourceTrigger */
typedef long AperiodicSRSResourceTrigger_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_AperiodicSRSResourceTrigger_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_AperiodicSRSResourceTrigger;
asn_struct_free_f AperiodicSRSResourceTrigger_free;
asn_struct_print_f AperiodicSRSResourceTrigger_print;
asn_constr_check_f AperiodicSRSResourceTrigger_constraint;
ber_type_decoder_f AperiodicSRSResourceTrigger_decode_ber;
der_type_encoder_f AperiodicSRSResourceTrigger_encode_der;
xer_type_decoder_f AperiodicSRSResourceTrigger_decode_xer;
xer_type_encoder_f AperiodicSRSResourceTrigger_encode_xer;
per_type_decoder_f AperiodicSRSResourceTrigger_decode_uper;
per_type_encoder_f AperiodicSRSResourceTrigger_encode_uper;
per_type_decoder_f AperiodicSRSResourceTrigger_decode_aper;
per_type_encoder_f AperiodicSRSResourceTrigger_encode_aper;

#ifdef __cplusplus
}
#endif

#endif /* _AperiodicSRSResourceTrigger_H_ */
#include <asn_internal.h>
