/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NRPPA-IEs"
 * 	found in "e2ap-v01.01.asn1"
 * 	`asn1c -gen-PER -fcompound-names -findirect-choice -fno-include-deps`
 */

#ifndef	_AssistanceInformationFailureList_H_
#define	_AssistanceInformationFailureList_H_


#include <asn_application.h>

/* Including external dependencies */
#include <asn_SEQUENCE_OF.h>
#include "PosSIB-Type.h"
#include "Outcome.h"
#include <constr_SEQUENCE.h>
#include <constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct ProtocolExtensionContainer;

/* Forward definitions */
typedef struct AssistanceInformationFailureList__Member {
	PosSIB_Type_t	 posSIB_Type;
	Outcome_t	 outcome;
	struct ProtocolExtensionContainer	*iE_Extensions	/* OPTIONAL */;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} AssistanceInformationFailureList__Member;

/* AssistanceInformationFailureList */
typedef struct AssistanceInformationFailureList {
	A_SEQUENCE_OF(AssistanceInformationFailureList__Member) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} AssistanceInformationFailureList_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_AssistanceInformationFailureList;

#ifdef __cplusplus
}
#endif

#endif	/* _AssistanceInformationFailureList_H_ */
#include <asn_internal.h>
