/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NRPPA-IEs"
 * 	found in "38455.asn"
 * 	`asn1c -no-gen-OER -fcompound-names -no-gen-example -findirect-choice
 * -fno-include-deps -D nrppa`
 */

#ifndef _BCCH_H_
#define _BCCH_H_

#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* BCCH */
typedef long BCCH_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_BCCH_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_BCCH;
asn_struct_free_f BCCH_free;
asn_struct_print_f BCCH_print;
asn_constr_check_f BCCH_constraint;
ber_type_decoder_f BCCH_decode_ber;
der_type_encoder_f BCCH_encode_der;
xer_type_decoder_f BCCH_decode_xer;
xer_type_encoder_f BCCH_encode_xer;
per_type_decoder_f BCCH_decode_uper;
per_type_encoder_f BCCH_encode_uper;
per_type_decoder_f BCCH_decode_aper;
per_type_encoder_f BCCH_encode_aper;

#ifdef __cplusplus
}
#endif

#endif /* _BCCH_H_ */
#include <asn_internal.h>
