/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NRPPA-IEs"
 * 	found in "38455.asn"
 * 	`asn1c -no-gen-OER -fcompound-names -no-gen-example -findirect-choice
 * -fno-include-deps -D nrppa`
 */

#ifndef _DL_Bandwidth_EUTRA_H_
#define _DL_Bandwidth_EUTRA_H_

#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum DL_Bandwidth_EUTRA {
  DL_Bandwidth_EUTRA_bw6   = 0,
  DL_Bandwidth_EUTRA_bw15  = 1,
  DL_Bandwidth_EUTRA_bw25  = 2,
  DL_Bandwidth_EUTRA_bw50  = 3,
  DL_Bandwidth_EUTRA_bw75  = 4,
  DL_Bandwidth_EUTRA_bw100 = 5
  /*
   * Enumeration is extensible
   */
} e_DL_Bandwidth_EUTRA;

/* DL-Bandwidth-EUTRA */
typedef long DL_Bandwidth_EUTRA_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_DL_Bandwidth_EUTRA_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_DL_Bandwidth_EUTRA;
extern const asn_INTEGER_specifics_t asn_SPC_DL_Bandwidth_EUTRA_specs_1;
asn_struct_free_f DL_Bandwidth_EUTRA_free;
asn_struct_print_f DL_Bandwidth_EUTRA_print;
asn_constr_check_f DL_Bandwidth_EUTRA_constraint;
ber_type_decoder_f DL_Bandwidth_EUTRA_decode_ber;
der_type_encoder_f DL_Bandwidth_EUTRA_encode_der;
xer_type_decoder_f DL_Bandwidth_EUTRA_decode_xer;
xer_type_encoder_f DL_Bandwidth_EUTRA_encode_xer;
per_type_decoder_f DL_Bandwidth_EUTRA_decode_uper;
per_type_encoder_f DL_Bandwidth_EUTRA_encode_uper;
per_type_decoder_f DL_Bandwidth_EUTRA_decode_aper;
per_type_encoder_f DL_Bandwidth_EUTRA_encode_aper;

#ifdef __cplusplus
}
#endif

#endif /* _DL_Bandwidth_EUTRA_H_ */
#include <asn_internal.h>
