/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NRPPA-IEs"
 * 	found in "e2ap-v01.01.asn1"
 * 	`asn1c -gen-PER -fcompound-names -findirect-choice -fno-include-deps`
 */

#ifndef	_E_CID_MeasurementResult_H_
#define	_E_CID_MeasurementResult_H_


#include <asn_application.h>

/* Including external dependencies */
#include "NG-RAN-CGI.h"
#include "TAC.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct NG_RANAccessPointPosition;
struct MeasuredResults;
struct ProtocolExtensionContainer;

/* E-CID-MeasurementResult */
typedef struct E_CID_MeasurementResult {
	NG_RAN_CGI_t	 servingCell_ID;
	TAC_t	 servingCellTAC;
	struct NG_RANAccessPointPosition	*nG_RANAccessPointPosition	/* OPTIONAL */;
	struct MeasuredResults	*measuredResults	/* OPTIONAL */;
	struct ProtocolExtensionContainer	*iE_Extensions	/* OPTIONAL */;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} E_CID_MeasurementResult_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_E_CID_MeasurementResult;

#ifdef __cplusplus
}
#endif

#endif	/* _E_CID_MeasurementResult_H_ */
#include <asn_internal.h>
