/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NRPPA-IEs"
 * 	found in "nrppa.asn1"
 * 	`asn1c -pdu=all -fcompound-names -fno-include-deps -findirect-choice
 * -no-gen-BER -no-gen-OER -no-gen-JER -no-gen-example -D oai-lmf/src/nrppa/`
 */

#ifndef _HESSID_H_
#define _HESSID_H_

#include <asn_application.h>

/* Including external dependencies */
#include <OCTET_STRING.h>

#ifdef __cplusplus
extern "C" {
#endif

/* HESSID */
typedef OCTET_STRING_t HESSID_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_HESSID_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_HESSID;
asn_struct_free_f HESSID_free;
asn_struct_print_f HESSID_print;
asn_constr_check_f HESSID_constraint;
xer_type_decoder_f HESSID_decode_xer;
xer_type_encoder_f HESSID_encode_xer;
per_type_decoder_f HESSID_decode_uper;
per_type_encoder_f HESSID_encode_uper;
per_type_decoder_f HESSID_decode_aper;
per_type_encoder_f HESSID_encode_aper;

#ifdef __cplusplus
}
#endif

#endif /* _HESSID_H_ */
#include <asn_internal.h>
