/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NRPPA-PDU-Descriptions"
 * 	found in "38455.asn"
 * 	`asn1c -no-gen-OER -fcompound-names -no-gen-example -findirect-choice
 * -fno-include-deps -D nrppa`
 */

#ifndef _InitiatingMessage_H_
#define _InitiatingMessage_H_

#include <asn_application.h>

/* Including external dependencies */
#include "ProcedureCode.h"
#include "Criticality.h"
#include "NRPPATransactionID.h"
#include <ANY.h>
#include <asn_ioc.h>
#include "E-CIDMeasurementInitiationRequest.h"
#include "E-CIDMeasurementInitiationResponse.h"
#include "E-CIDMeasurementInitiationFailure.h"
#include "OTDOAInformationRequest.h"
#include "OTDOAInformationResponse.h"
#include "OTDOAInformationFailure.h"
#include "PositioningInformationRequest.h"
#include "PositioningInformationResponse.h"
#include "PositioningInformationFailure.h"
#include "MeasurementRequest.h"
#include "MeasurementResponse.h"
#include "MeasurementFailure.h"
#include "TRPInformationRequest.h"
#include "TRPInformationResponse.h"
#include "TRPInformationFailure.h"
#include "PositioningActivationRequest.h"
#include "PositioningActivationResponse.h"
#include "PositioningActivationFailure.h"
#include "E-CIDMeasurementFailureIndication.h"
#include "E-CIDMeasurementReport.h"
#include "E-CIDMeasurementTerminationCommand.h"
#include "ErrorIndication.h"
#include "PrivateMessage.h"
#include "AssistanceInformationControl.h"
#include "AssistanceInformationFeedback.h"
#include "PositioningInformationUpdate.h"
#include "MeasurementReport.h"
#include "MeasurementUpdate.h"
#include "MeasurementAbort.h"
#include "MeasurementFailureIndication.h"
#include "PositioningDeactivation.h"
#include <OPEN_TYPE.h>
#include <constr_CHOICE.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum InitiatingMessage__value_PR {
  InitiatingMessage__value_PR_NOTHING, /* No components present */
  InitiatingMessage__value_PR_E_CIDMeasurementInitiationRequest,
  InitiatingMessage__value_PR_OTDOAInformationRequest,
  InitiatingMessage__value_PR_PositioningInformationRequest,
  InitiatingMessage__value_PR_MeasurementRequest,
  InitiatingMessage__value_PR_TRPInformationRequest,
  InitiatingMessage__value_PR_PositioningActivationRequest,
  InitiatingMessage__value_PR_E_CIDMeasurementFailureIndication,
  InitiatingMessage__value_PR_E_CIDMeasurementReport,
  InitiatingMessage__value_PR_E_CIDMeasurementTerminationCommand,
  InitiatingMessage__value_PR_ErrorIndication,
  InitiatingMessage__value_PR_PrivateMessage,
  InitiatingMessage__value_PR_AssistanceInformationControl,
  InitiatingMessage__value_PR_AssistanceInformationFeedback,
  InitiatingMessage__value_PR_PositioningInformationUpdate,
  InitiatingMessage__value_PR_MeasurementReport,
  InitiatingMessage__value_PR_MeasurementUpdate,
  InitiatingMessage__value_PR_MeasurementAbort,
  InitiatingMessage__value_PR_MeasurementFailureIndication,
  InitiatingMessage__value_PR_PositioningDeactivation
} InitiatingMessage__value_PR;

/* InitiatingMessage */
typedef struct InitiatingMessage {
  ProcedureCode_t procedureCode;
  Criticality_t criticality;
  NRPPATransactionID_t nrppatransactionID;
  struct InitiatingMessage__value {
    InitiatingMessage__value_PR present;
    union InitiatingMessage__value_u {
      E_CIDMeasurementInitiationRequest_t E_CIDMeasurementInitiationRequest;
      OTDOAInformationRequest_t OTDOAInformationRequest;
      PositioningInformationRequest_t PositioningInformationRequest;
      MeasurementRequest_t MeasurementRequest;
      TRPInformationRequest_t TRPInformationRequest;
      PositioningActivationRequest_t PositioningActivationRequest;
      E_CIDMeasurementFailureIndication_t E_CIDMeasurementFailureIndication;
      E_CIDMeasurementReport_t E_CIDMeasurementReport;
      E_CIDMeasurementTerminationCommand_t E_CIDMeasurementTerminationCommand;
      ErrorIndication_t ErrorIndication;
      PrivateMessage_t PrivateMessage;
      AssistanceInformationControl_t AssistanceInformationControl;
      AssistanceInformationFeedback_t AssistanceInformationFeedback;
      PositioningInformationUpdate_t PositioningInformationUpdate;
      MeasurementReport_t MeasurementReport;
      MeasurementUpdate_t MeasurementUpdate;
      MeasurementAbort_t MeasurementAbort;
      MeasurementFailureIndication_t MeasurementFailureIndication;
      PositioningDeactivation_t PositioningDeactivation;
    } choice;

    /* Context for parsing across buffer boundaries */
    asn_struct_ctx_t _asn_ctx;
  } value;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} InitiatingMessage_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_InitiatingMessage;
extern asn_SEQUENCE_specifics_t asn_SPC_InitiatingMessage_specs_1;
extern asn_TYPE_member_t asn_MBR_InitiatingMessage_1[4];

#ifdef __cplusplus
}
#endif

#endif /* _InitiatingMessage_H_ */
#include <asn_internal.h>
