/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NRPPA-IEs"
 * 	found in "nrppa.asn1"
 * 	`asn1c -pdu=all -fcompound-names -fno-include-deps -findirect-choice
 * -no-gen-BER -no-gen-OER -no-gen-JER -no-gen-example -D oai-lmf/src/nrppa/`
 */

#ifndef _MeasurementPeriodicityExtended_H_
#define _MeasurementPeriodicityExtended_H_

#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum MeasurementPeriodicityExtended {
  MeasurementPeriodicityExtended_ms160     = 0,
  MeasurementPeriodicityExtended_ms320     = 1,
  MeasurementPeriodicityExtended_ms1280    = 2,
  MeasurementPeriodicityExtended_ms2560    = 3,
  MeasurementPeriodicityExtended_ms61440   = 4,
  MeasurementPeriodicityExtended_ms81920   = 5,
  MeasurementPeriodicityExtended_ms368640  = 6,
  MeasurementPeriodicityExtended_ms737280  = 7,
  MeasurementPeriodicityExtended_ms1843200 = 8
  /*
   * Enumeration is extensible
   */
} e_MeasurementPeriodicityExtended;

/* MeasurementPeriodicityExtended */
typedef long MeasurementPeriodicityExtended_t;

/* Implementation */
extern asn_per_constraints_t
    asn_PER_type_MeasurementPeriodicityExtended_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_MeasurementPeriodicityExtended;
extern const asn_INTEGER_specifics_t
    asn_SPC_MeasurementPeriodicityExtended_specs_1;
asn_struct_free_f MeasurementPeriodicityExtended_free;
asn_struct_print_f MeasurementPeriodicityExtended_print;
asn_constr_check_f MeasurementPeriodicityExtended_constraint;
xer_type_decoder_f MeasurementPeriodicityExtended_decode_xer;
xer_type_encoder_f MeasurementPeriodicityExtended_encode_xer;
per_type_decoder_f MeasurementPeriodicityExtended_decode_uper;
per_type_encoder_f MeasurementPeriodicityExtended_encode_uper;
per_type_decoder_f MeasurementPeriodicityExtended_decode_aper;
per_type_encoder_f MeasurementPeriodicityExtended_encode_aper;

#ifdef __cplusplus
}
#endif

#endif /* _MeasurementPeriodicityExtended_H_ */
#include <asn_internal.h>
