/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NRPPA-IEs"
 * 	found in "38455.asn"
 * 	`asn1c -no-gen-OER -fcompound-names -no-gen-example -findirect-choice
 * -fno-include-deps -D nrppa`
 */

#ifndef _NR_PRS_Beam_Information_H_
#define _NR_PRS_Beam_Information_H_

#include <asn_application.h>

/* Including external dependencies */
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct ProtocolExtensionContainer;
struct NR_PRS_Beam_InformationItem;
struct LCG_to_GCS_TranslationItem;

/* NR-PRS-Beam-Information */
typedef struct NR_PRS_Beam_Information {
  struct NR_PRS_Beam_Information__nR_PRS_Beam_InformationList {
    A_SEQUENCE_OF(struct NR_PRS_Beam_InformationItem) list;

    /* Context for parsing across buffer boundaries */
    asn_struct_ctx_t _asn_ctx;
  } nR_PRS_Beam_InformationList;
  struct NR_PRS_Beam_Information__lCG_to_GCS_TranslationList {
    A_SEQUENCE_OF(struct LCG_to_GCS_TranslationItem) list;

    /* Context for parsing across buffer boundaries */
    asn_struct_ctx_t _asn_ctx;
  } lCG_to_GCS_TranslationList;
  struct ProtocolExtensionContainer* iE_Extensions; /* OPTIONAL */
  /*
   * This type is extensible,
   * possible extensions are below.
   */

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} NR_PRS_Beam_Information_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_NR_PRS_Beam_Information;
extern asn_SEQUENCE_specifics_t asn_SPC_NR_PRS_Beam_Information_specs_1;
extern asn_TYPE_member_t asn_MBR_NR_PRS_Beam_Information_1[3];

#ifdef __cplusplus
}
#endif

#endif /* _NR_PRS_Beam_Information_H_ */
#include <asn_internal.h>
