/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NRPPA-PDU-Descriptions"
 * 	found in "38455.asn"
 * 	`asn1c -no-gen-OER -fcompound-names -no-gen-example -findirect-choice
 * -fno-include-deps -D nrppa`
 */

#ifndef _NRPPA_PDU_H_
#define _NRPPA_PDU_H_

#include <asn_application.h>

/* Including external dependencies */
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum NRPPA_PDU_PR {
  NRPPA_PDU_PR_NOTHING, /* No components present */
  NRPPA_PDU_PR_initiatingMessage,
  NRPPA_PDU_PR_successfulOutcome,
  NRPPA_PDU_PR_unsuccessfulOutcome
  /* Extensions may appear below */

} NRPPA_PDU_PR;

/* Forward declarations */
struct InitiatingMessage;
struct SuccessfulOutcome;
struct UnsuccessfulOutcome;

/* NRPPA-PDU */
typedef struct NRPPA_PDU {
  NRPPA_PDU_PR present;
  union NRPPA_PDU_u {
    struct InitiatingMessage* initiatingMessage;
    struct SuccessfulOutcome* successfulOutcome;
    struct UnsuccessfulOutcome* unsuccessfulOutcome;
    /*
     * This type is extensible,
     * possible extensions are below.
     */
  } choice;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} NRPPA_PDU_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_NRPPA_PDU;

#ifdef __cplusplus
}
#endif

#endif /* _NRPPA_PDU_H_ */
#include <asn_internal.h>
