/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NRPPA-PDU-Contents"
 * 	found in "38455.asn"
 * 	`asn1c -no-gen-OER -fcompound-names -no-gen-example -findirect-choice
 * -fno-include-deps -D nrppa`
 */

#ifndef _OTDOA_Information_Type_H_
#define _OTDOA_Information_Type_H_

#include <asn_application.h>

/* Including external dependencies */
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct ProtocolIE_Single_Container;

/* OTDOA-Information-Type */
typedef struct OTDOA_Information_Type {
  A_SEQUENCE_OF(struct ProtocolIE_Single_Container) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} OTDOA_Information_Type_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_OTDOA_Information_Type;
extern asn_SET_OF_specifics_t asn_SPC_OTDOA_Information_Type_specs_1;
extern asn_TYPE_member_t asn_MBR_OTDOA_Information_Type_1[1];
extern asn_per_constraints_t asn_PER_type_OTDOA_Information_Type_constr_1;

#ifdef __cplusplus
}
#endif

#endif /* _OTDOA_Information_Type_H_ */
#include <asn_internal.h>
