/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NRPPA-IEs"
 * 	found in "38455.asn"
 * 	`asn1c -no-gen-OER -fcompound-names -no-gen-example -findirect-choice
 * -fno-include-deps -D nrppa`
 */

#include "OtherRATMeasuredResultsValue.h"

#include "ResultGERAN.h"
#include "ResultUTRAN.h"
#include "ProtocolIE-Single-Container.h"
asn_per_constraints_t asn_PER_type_OtherRATMeasuredResultsValue_constr_1
    CC_NOTUSED = {
        {APC_CONSTRAINED, 2, 2, 0, 2} /* (0..2) */,
        {APC_UNCONSTRAINED, -1, -1, 0, 0},
        0,
        0 /* No PER value map */
};
asn_TYPE_member_t asn_MBR_OtherRATMeasuredResultsValue_1[] = {
    {ATF_POINTER,
     0,
     offsetof(struct OtherRATMeasuredResultsValue, choice.resultGERAN),
     (ASN_TAG_CLASS_CONTEXT | (0 << 2)),
     -1, /* IMPLICIT tag at current level */
     &asn_DEF_ResultGERAN,
     0,
     {0, 0, 0},
     0,
     0, /* No default value */
     "resultGERAN"},
    {ATF_POINTER,
     0,
     offsetof(struct OtherRATMeasuredResultsValue, choice.resultUTRAN),
     (ASN_TAG_CLASS_CONTEXT | (1 << 2)),
     -1, /* IMPLICIT tag at current level */
     &asn_DEF_ResultUTRAN,
     0,
     {0, 0, 0},
     0,
     0, /* No default value */
     "resultUTRAN"},
    {ATF_POINTER,
     0,
     offsetof(
         struct OtherRATMeasuredResultsValue,
         choice.otherRATMeasuredResultsValue_Extension),
     (ASN_TAG_CLASS_CONTEXT | (2 << 2)),
     -1, /* IMPLICIT tag at current level */
     &asn_DEF_ProtocolIE_Single_Container_2792P13,
     0,
     {0, 0, 0},
     0,
     0, /* No default value */
     "otherRATMeasuredResultsValue-Extension"},
};
static const asn_TYPE_tag2member_t
    asn_MAP_OtherRATMeasuredResultsValue_tag2el_1[] = {
        {(ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0}, /* resultGERAN */
        {(ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0}, /* resultUTRAN */
        {(ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0,
         0} /* otherRATMeasuredResultsValue-Extension */
};
asn_CHOICE_specifics_t asn_SPC_OtherRATMeasuredResultsValue_specs_1 = {
    sizeof(struct OtherRATMeasuredResultsValue),
    offsetof(struct OtherRATMeasuredResultsValue, _asn_ctx),
    offsetof(struct OtherRATMeasuredResultsValue, present),
    sizeof(((struct OtherRATMeasuredResultsValue*) 0)->present),
    asn_MAP_OtherRATMeasuredResultsValue_tag2el_1,
    3, /* Count of tags in the map */
    0,
    0,
    -1 /* Extensions start */
};
asn_TYPE_descriptor_t asn_DEF_OtherRATMeasuredResultsValue = {
    "OtherRATMeasuredResultsValue",
    "OtherRATMeasuredResultsValue",
    &asn_OP_CHOICE,
    0, /* No effective tags (pointer) */
    0, /* No effective tags (count) */
    0, /* No tags (pointer) */
    0, /* No tags (count) */
    {0, &asn_PER_type_OtherRATMeasuredResultsValue_constr_1, CHOICE_constraint},
    asn_MBR_OtherRATMeasuredResultsValue_1,
    3,                                            /* Elements count */
    &asn_SPC_OtherRATMeasuredResultsValue_specs_1 /* Additional specs */
};
