/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NRPPA-Containers"
 * 	found in "nrppa.asn1"
 * 	`asn1c -pdu=all -fcompound-names -fno-include-deps -findirect-choice
 * -no-gen-BER -no-gen-OER -no-gen-JER -no-gen-example -D oai-lmf/src/nrppa/`
 */

#ifndef _ProtocolExtensionContainer_H_
#define _ProtocolExtensionContainer_H_

#include <asn_application.h>

/* Including external dependencies */
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct OTDOA_Information_Type_ItemExtIEs;
struct SemipersistentSRS_ExtIEs;
struct AperiodicSRS_ExtIEs;
struct ActiveULBWP_ExtIEs;
struct AdditionalPathListItem_ExtIEs;
struct Assistance_Information_ExtIEs;
struct AssistanceInformationFailureList_ExtIEs;
struct AssistanceInformationMetaData_ExtIEs;
struct CGI_EUTRA_ExtIEs;
struct CGI_NR_ExtIEs;
struct CriticalityDiagnostics_ExtIEs;
struct CriticalityDiagnostics_IE_List_ExtIEs;
struct DL_PRS_ExtIEs;
struct DLPRSResourceCoordinates_ExtIEs;
struct DLPRSResourceSetARP_ExtIEs;
struct DLPRSResourceARP_ExtIEs;
struct E_CID_MeasurementResult_ExtIEs;
struct GeographicalCoordinates_ExtIEs;
struct GNB_RxTxTimeDiff_ExtIEs;
struct LCS_to_GCS_TranslationAoA_ExtIEs;
struct LCS_to_GCS_TranslationItem_ExtIEs;
struct LocationUncertainty_ExtIEs;
struct MeasurementBeamInfo_ExtIEs;
struct MeasurementQuantitiesValue_ExtIEs;
struct NG_RANAccessPointPosition_ExtIEs;
struct NGRANHighAccuracyAccessPointPosition_ExtIEs;
struct NG_RAN_CGI_ExtIEs;
struct NR_PRS_Beam_Information_IEs;
struct NR_PRS_Beam_InformationItem_ExtIEs;
struct OTDOACells_ExtIEs;
struct OtherRATMeasurementQuantitiesValue_ExtIEs;
struct PathlossReferenceInformation_ExtIEs;
struct PosSIBs_ExtIEs;
struct PosSIB_Segments_ExtIEs;
struct PosSRSResource_Item_ExtIEs;
struct PosSRSResourceSet_Item_ExtIEs;
struct PosResourceSetTypePeriodic_ExtIEs;
struct PosResourceSetTypeSemi_persistent_ExtIEs;
struct PosResourceSetTypeAperiodic_ExtIEs;
struct PRSAngleItem_ExtIEs;
struct PRSInformationPos_ExtIEs;
struct PRSConfiguration_ExtIEs;
struct PRSFrequencyHoppingConfiguration_EUTRA_Item_IEs;
struct PRSMuting_ExtIEs;
struct PRSMutingOption1_ExtIEs;
struct PRSMutingOption2_ExtIEs;
struct PRSResource_Item_ExtIEs;
struct PRSResource_QCLSourceSSB_ExtIEs;
struct PRSResource_QCLSourcePRS_ExtIEs;
struct PRSResourceSet_Item_ExtIEs;
struct RelativeGeodeticLocation_ExtIEs;
struct RelativeCartesianLocation_ExtIEs;
struct RequestedSRSTransmissionCharacteristics_ExtIEs;
struct SRSResourceSet_Item_ExtIEs;
struct ResourceSetTypePeriodic_ExtIEs;
struct ResourceSetTypeSemi_persistent_ExtIEs;
struct ResourceSetTypeAperiodic_ExtIEs;
struct ResourceTypePeriodic_ExtIEs;
struct ResourceTypeSemi_persistent_ExtIEs;
struct ResourceTypeAperiodic_ExtIEs;
struct ResourceTypePeriodicPos_ExtIEs;
struct ResourceTypeSemi_persistentPos_ExtIEs;
struct ResourceTypeAperiodicPos_ExtIEs;
struct ResultCSI_RSRP_Item_ExtIEs;
struct ResultCSI_RSRP_PerCSI_RS_Item_ExtIEs;
struct ResultCSI_RSRQ_Item_ExtIEs;
struct ResultCSI_RSRQ_PerCSI_RS_Item_ExtIEs;
struct ResultEUTRA_Item_ExtIEs;
struct ResultRSRP_EUTRA_Item_ExtIEs;
struct ResultRSRQ_EUTRA_Item_ExtIEs;
struct ResultSS_RSRP_Item_ExtIEs;
struct ResultSS_RSRP_PerSSB_Item_ExtIEs;
struct ResultSS_RSRQ_Item_ExtIEs;
struct ResultSS_RSRQ_PerSSB_Item_ExtIEs;
struct ResultGERAN_Item_ExtIEs;
struct ResultNR_Item_ExtIEs;
struct ResultUTRAN_Item_ExtIEs;
struct SCS_SpecificCarrier_ExtIEs;
struct Search_window_information_ExtIEs;
struct SpatialDirectionInformation_ExtIEs;
struct SpatialRelationInfo_ExtIEs;
struct SpatialRelationforResourceIDItem_ExtIEs;
struct SpatialRelationPerSRSResource_ExtIEs;
struct SpatialRelationPerSRSResourceItem_ExtIEs;
struct SRSConfig_ExtIEs;
struct SRSCarrier_List_Item_ExtIEs;
struct SRSConfiguration_ExtIEs;
struct SRSResource_ExtIEs;
struct SRSResourceSet_ExtIEs;
struct SRSResourceTrigger_ExtIEs;
struct SSBInfo_ExtIEs;
struct SSBInfoItem_ExtIEs;
struct SSB_ExtIEs;
struct SystemInformation_ExtIEs;
struct TDD_Config_EUTRA_Item_Item_ExtIEs;
struct TF_Configuration_ExtIEs;
struct TimeStamp_ExtIEs;
struct TRPMeasurementQuantitiesList_Item_ExtIEs;
struct TrpMeasurementResultItem_ExtIEs;
struct TrpMeasurementTimingQuality_ExtIEs;
struct TrpMeasurementAngleQuality_ExtIEs;
struct TRP_MeasurementRequestItem_ExtIEs;
struct TRP_MeasurementResponseItem_ExtIEs;
struct TRPInformationTRPResp_ExtIEs;
struct TRPInformation_ExtIEs;
struct TRPItem_ExtIEs;
struct TRPPositionDirect_ExtIEs;
struct TRPPositionReferenced_ExtIEs;
struct UL_AoA_ExtIEs;
struct UL_RTOAMeasurement_ExtIEs;
struct WLANMeasurementQuantitiesValue_ExtIEs;
struct WLANMeasurementResult_Item_ExtIEs;

/* ProtocolExtensionContainer */
typedef struct ProtocolExtensionContainer_2920P0 {
  A_SEQUENCE_OF(struct OTDOA_Information_Type_ItemExtIEs) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_2920P0_t;
typedef struct ProtocolExtensionContainer_2920P1 {
  A_SEQUENCE_OF(struct SemipersistentSRS_ExtIEs) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_2920P1_t;
typedef struct ProtocolExtensionContainer_2920P2 {
  A_SEQUENCE_OF(struct AperiodicSRS_ExtIEs) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_2920P2_t;
typedef struct ProtocolExtensionContainer_2920P3 {
  A_SEQUENCE_OF(struct ActiveULBWP_ExtIEs) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_2920P3_t;
typedef struct ProtocolExtensionContainer_2920P4 {
  A_SEQUENCE_OF(struct AdditionalPathListItem_ExtIEs) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_2920P4_t;
typedef struct ProtocolExtensionContainer_2920P5 {
  A_SEQUENCE_OF(struct Assistance_Information_ExtIEs) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_2920P5_t;
typedef struct ProtocolExtensionContainer_2920P6 {
  A_SEQUENCE_OF(struct AssistanceInformationFailureList_ExtIEs) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_2920P6_t;
typedef struct ProtocolExtensionContainer_2920P7 {
  A_SEQUENCE_OF(struct AssistanceInformationMetaData_ExtIEs) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_2920P7_t;
typedef struct ProtocolExtensionContainer_2920P8 {
  A_SEQUENCE_OF(struct CGI_EUTRA_ExtIEs) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_2920P8_t;
typedef struct ProtocolExtensionContainer_2920P9 {
  A_SEQUENCE_OF(struct CGI_NR_ExtIEs) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_2920P9_t;
typedef struct ProtocolExtensionContainer_2920P10 {
  A_SEQUENCE_OF(struct CriticalityDiagnostics_ExtIEs) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_2920P10_t;
typedef struct ProtocolExtensionContainer_2920P11 {
  A_SEQUENCE_OF(struct CriticalityDiagnostics_IE_List_ExtIEs) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_2920P11_t;
typedef struct ProtocolExtensionContainer_2920P12 {
  A_SEQUENCE_OF(struct DL_PRS_ExtIEs) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_2920P12_t;
typedef struct ProtocolExtensionContainer_2920P13 {
  A_SEQUENCE_OF(struct DLPRSResourceCoordinates_ExtIEs) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_2920P13_t;
typedef struct ProtocolExtensionContainer_2920P14 {
  A_SEQUENCE_OF(struct DLPRSResourceSetARP_ExtIEs) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_2920P14_t;
typedef struct ProtocolExtensionContainer_2920P15 {
  A_SEQUENCE_OF(struct DLPRSResourceARP_ExtIEs) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_2920P15_t;
typedef struct ProtocolExtensionContainer_2920P16 {
  A_SEQUENCE_OF(struct E_CID_MeasurementResult_ExtIEs) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_2920P16_t;
typedef struct ProtocolExtensionContainer_2920P17 {
  A_SEQUENCE_OF(struct GeographicalCoordinates_ExtIEs) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_2920P17_t;
typedef struct ProtocolExtensionContainer_2920P18 {
  A_SEQUENCE_OF(struct GNB_RxTxTimeDiff_ExtIEs) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_2920P18_t;
typedef struct ProtocolExtensionContainer_2920P19 {
  A_SEQUENCE_OF(struct LCS_to_GCS_TranslationAoA_ExtIEs) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_2920P19_t;
typedef struct ProtocolExtensionContainer_2920P20 {
  A_SEQUENCE_OF(struct LCS_to_GCS_TranslationItem_ExtIEs) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_2920P20_t;
typedef struct ProtocolExtensionContainer_2920P21 {
  A_SEQUENCE_OF(struct LocationUncertainty_ExtIEs) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_2920P21_t;
typedef struct ProtocolExtensionContainer_2920P22 {
  A_SEQUENCE_OF(struct MeasurementBeamInfo_ExtIEs) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_2920P22_t;
typedef struct ProtocolExtensionContainer_2920P23 {
  A_SEQUENCE_OF(struct MeasurementQuantitiesValue_ExtIEs) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_2920P23_t;
typedef struct ProtocolExtensionContainer_2920P24 {
  A_SEQUENCE_OF(struct NG_RANAccessPointPosition_ExtIEs) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_2920P24_t;
typedef struct ProtocolExtensionContainer_2920P25 {
  A_SEQUENCE_OF(struct NGRANHighAccuracyAccessPointPosition_ExtIEs) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_2920P25_t;
typedef struct ProtocolExtensionContainer_2920P26 {
  A_SEQUENCE_OF(struct NG_RAN_CGI_ExtIEs) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_2920P26_t;
typedef struct ProtocolExtensionContainer_2920P27 {
  A_SEQUENCE_OF(struct NR_PRS_Beam_Information_IEs) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_2920P27_t;
typedef struct ProtocolExtensionContainer_2920P28 {
  A_SEQUENCE_OF(struct NR_PRS_Beam_InformationItem_ExtIEs) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_2920P28_t;
typedef struct ProtocolExtensionContainer_2920P29 {
  A_SEQUENCE_OF(struct OTDOACells_ExtIEs) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_2920P29_t;
typedef struct ProtocolExtensionContainer_2920P30 {
  A_SEQUENCE_OF(struct OtherRATMeasurementQuantitiesValue_ExtIEs) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_2920P30_t;
typedef struct ProtocolExtensionContainer_2920P31 {
  A_SEQUENCE_OF(struct PathlossReferenceInformation_ExtIEs) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_2920P31_t;
typedef struct ProtocolExtensionContainer_2920P32 {
  A_SEQUENCE_OF(struct PosSIBs_ExtIEs) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_2920P32_t;
typedef struct ProtocolExtensionContainer_2920P33 {
  A_SEQUENCE_OF(struct PosSIB_Segments_ExtIEs) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_2920P33_t;
typedef struct ProtocolExtensionContainer_2920P34 {
  A_SEQUENCE_OF(struct PosSRSResource_Item_ExtIEs) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_2920P34_t;
typedef struct ProtocolExtensionContainer_2920P35 {
  A_SEQUENCE_OF(struct PosSRSResourceSet_Item_ExtIEs) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_2920P35_t;
typedef struct ProtocolExtensionContainer_2920P36 {
  A_SEQUENCE_OF(struct PosResourceSetTypePeriodic_ExtIEs) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_2920P36_t;
typedef struct ProtocolExtensionContainer_2920P37 {
  A_SEQUENCE_OF(struct PosResourceSetTypeSemi_persistent_ExtIEs) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_2920P37_t;
typedef struct ProtocolExtensionContainer_2920P38 {
  A_SEQUENCE_OF(struct PosResourceSetTypeAperiodic_ExtIEs) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_2920P38_t;
typedef struct ProtocolExtensionContainer_2920P39 {
  A_SEQUENCE_OF(struct PRSAngleItem_ExtIEs) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_2920P39_t;
typedef struct ProtocolExtensionContainer_2920P40 {
  A_SEQUENCE_OF(struct PRSInformationPos_ExtIEs) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_2920P40_t;
typedef struct ProtocolExtensionContainer_2920P41 {
  A_SEQUENCE_OF(struct PRSConfiguration_ExtIEs) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_2920P41_t;
typedef struct ProtocolExtensionContainer_2920P42 {
  A_SEQUENCE_OF(struct PRSFrequencyHoppingConfiguration_EUTRA_Item_IEs) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_2920P42_t;
typedef struct ProtocolExtensionContainer_2920P43 {
  A_SEQUENCE_OF(struct PRSMuting_ExtIEs) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_2920P43_t;
typedef struct ProtocolExtensionContainer_2920P44 {
  A_SEQUENCE_OF(struct PRSMutingOption1_ExtIEs) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_2920P44_t;
typedef struct ProtocolExtensionContainer_2920P45 {
  A_SEQUENCE_OF(struct PRSMutingOption2_ExtIEs) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_2920P45_t;
typedef struct ProtocolExtensionContainer_2920P46 {
  A_SEQUENCE_OF(struct PRSResource_Item_ExtIEs) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_2920P46_t;
typedef struct ProtocolExtensionContainer_2920P47 {
  A_SEQUENCE_OF(struct PRSResource_QCLSourceSSB_ExtIEs) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_2920P47_t;
typedef struct ProtocolExtensionContainer_2920P48 {
  A_SEQUENCE_OF(struct PRSResource_QCLSourcePRS_ExtIEs) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_2920P48_t;
typedef struct ProtocolExtensionContainer_2920P49 {
  A_SEQUENCE_OF(struct PRSResourceSet_Item_ExtIEs) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_2920P49_t;
typedef struct ProtocolExtensionContainer_2920P50 {
  A_SEQUENCE_OF(struct RelativeGeodeticLocation_ExtIEs) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_2920P50_t;
typedef struct ProtocolExtensionContainer_2920P51 {
  A_SEQUENCE_OF(struct RelativeCartesianLocation_ExtIEs) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_2920P51_t;
typedef struct ProtocolExtensionContainer_2920P52 {
  A_SEQUENCE_OF(struct RequestedSRSTransmissionCharacteristics_ExtIEs) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_2920P52_t;
typedef struct ProtocolExtensionContainer_2920P53 {
  A_SEQUENCE_OF(struct SRSResourceSet_Item_ExtIEs) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_2920P53_t;
typedef struct ProtocolExtensionContainer_2920P54 {
  A_SEQUENCE_OF(struct ResourceSetTypePeriodic_ExtIEs) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_2920P54_t;
typedef struct ProtocolExtensionContainer_2920P55 {
  A_SEQUENCE_OF(struct ResourceSetTypeSemi_persistent_ExtIEs) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_2920P55_t;
typedef struct ProtocolExtensionContainer_2920P56 {
  A_SEQUENCE_OF(struct ResourceSetTypeAperiodic_ExtIEs) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_2920P56_t;
typedef struct ProtocolExtensionContainer_2920P57 {
  A_SEQUENCE_OF(struct ResourceTypePeriodic_ExtIEs) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_2920P57_t;
typedef struct ProtocolExtensionContainer_2920P58 {
  A_SEQUENCE_OF(struct ResourceTypeSemi_persistent_ExtIEs) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_2920P58_t;
typedef struct ProtocolExtensionContainer_2920P59 {
  A_SEQUENCE_OF(struct ResourceTypeAperiodic_ExtIEs) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_2920P59_t;
typedef struct ProtocolExtensionContainer_2920P60 {
  A_SEQUENCE_OF(struct ResourceTypePeriodicPos_ExtIEs) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_2920P60_t;
typedef struct ProtocolExtensionContainer_2920P61 {
  A_SEQUENCE_OF(struct ResourceTypeSemi_persistentPos_ExtIEs) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_2920P61_t;
typedef struct ProtocolExtensionContainer_2920P62 {
  A_SEQUENCE_OF(struct ResourceTypeAperiodicPos_ExtIEs) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_2920P62_t;
typedef struct ProtocolExtensionContainer_2920P63 {
  A_SEQUENCE_OF(struct ResultCSI_RSRP_Item_ExtIEs) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_2920P63_t;
typedef struct ProtocolExtensionContainer_2920P64 {
  A_SEQUENCE_OF(struct ResultCSI_RSRP_PerCSI_RS_Item_ExtIEs) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_2920P64_t;
typedef struct ProtocolExtensionContainer_2920P65 {
  A_SEQUENCE_OF(struct ResultCSI_RSRQ_Item_ExtIEs) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_2920P65_t;
typedef struct ProtocolExtensionContainer_2920P66 {
  A_SEQUENCE_OF(struct ResultCSI_RSRQ_PerCSI_RS_Item_ExtIEs) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_2920P66_t;
typedef struct ProtocolExtensionContainer_2920P67 {
  A_SEQUENCE_OF(struct ResultEUTRA_Item_ExtIEs) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_2920P67_t;
typedef struct ProtocolExtensionContainer_2920P68 {
  A_SEQUENCE_OF(struct ResultRSRP_EUTRA_Item_ExtIEs) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_2920P68_t;
typedef struct ProtocolExtensionContainer_2920P69 {
  A_SEQUENCE_OF(struct ResultRSRQ_EUTRA_Item_ExtIEs) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_2920P69_t;
typedef struct ProtocolExtensionContainer_2920P70 {
  A_SEQUENCE_OF(struct ResultSS_RSRP_Item_ExtIEs) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_2920P70_t;
typedef struct ProtocolExtensionContainer_2920P71 {
  A_SEQUENCE_OF(struct ResultSS_RSRP_PerSSB_Item_ExtIEs) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_2920P71_t;
typedef struct ProtocolExtensionContainer_2920P72 {
  A_SEQUENCE_OF(struct ResultSS_RSRQ_Item_ExtIEs) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_2920P72_t;
typedef struct ProtocolExtensionContainer_2920P73 {
  A_SEQUENCE_OF(struct ResultSS_RSRQ_PerSSB_Item_ExtIEs) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_2920P73_t;
typedef struct ProtocolExtensionContainer_2920P74 {
  A_SEQUENCE_OF(struct ResultGERAN_Item_ExtIEs) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_2920P74_t;
typedef struct ProtocolExtensionContainer_2920P75 {
  A_SEQUENCE_OF(struct ResultNR_Item_ExtIEs) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_2920P75_t;
typedef struct ProtocolExtensionContainer_2920P76 {
  A_SEQUENCE_OF(struct ResultUTRAN_Item_ExtIEs) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_2920P76_t;
typedef struct ProtocolExtensionContainer_2920P77 {
  A_SEQUENCE_OF(struct SCS_SpecificCarrier_ExtIEs) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_2920P77_t;
typedef struct ProtocolExtensionContainer_2920P78 {
  A_SEQUENCE_OF(struct Search_window_information_ExtIEs) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_2920P78_t;
typedef struct ProtocolExtensionContainer_2920P79 {
  A_SEQUENCE_OF(struct SpatialDirectionInformation_ExtIEs) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_2920P79_t;
typedef struct ProtocolExtensionContainer_2920P80 {
  A_SEQUENCE_OF(struct SpatialRelationInfo_ExtIEs) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_2920P80_t;
typedef struct ProtocolExtensionContainer_2920P81 {
  A_SEQUENCE_OF(struct SpatialRelationforResourceIDItem_ExtIEs) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_2920P81_t;
typedef struct ProtocolExtensionContainer_2920P82 {
  A_SEQUENCE_OF(struct SpatialRelationPerSRSResource_ExtIEs) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_2920P82_t;
typedef struct ProtocolExtensionContainer_2920P83 {
  A_SEQUENCE_OF(struct SpatialRelationPerSRSResourceItem_ExtIEs) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_2920P83_t;
typedef struct ProtocolExtensionContainer_2920P84 {
  A_SEQUENCE_OF(struct SRSConfig_ExtIEs) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_2920P84_t;
typedef struct ProtocolExtensionContainer_2920P85 {
  A_SEQUENCE_OF(struct SRSCarrier_List_Item_ExtIEs) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_2920P85_t;
typedef struct ProtocolExtensionContainer_2920P86 {
  A_SEQUENCE_OF(struct SRSConfiguration_ExtIEs) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_2920P86_t;
typedef struct ProtocolExtensionContainer_2920P87 {
  A_SEQUENCE_OF(struct SRSResource_ExtIEs) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_2920P87_t;
typedef struct ProtocolExtensionContainer_2920P88 {
  A_SEQUENCE_OF(struct SRSResourceSet_ExtIEs) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_2920P88_t;
typedef struct ProtocolExtensionContainer_2920P89 {
  A_SEQUENCE_OF(struct SRSResourceTrigger_ExtIEs) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_2920P89_t;
typedef struct ProtocolExtensionContainer_2920P90 {
  A_SEQUENCE_OF(struct SSBInfo_ExtIEs) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_2920P90_t;
typedef struct ProtocolExtensionContainer_2920P91 {
  A_SEQUENCE_OF(struct SSBInfoItem_ExtIEs) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_2920P91_t;
typedef struct ProtocolExtensionContainer_2920P92 {
  A_SEQUENCE_OF(struct SSB_ExtIEs) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_2920P92_t;
typedef struct ProtocolExtensionContainer_2920P93 {
  A_SEQUENCE_OF(struct SystemInformation_ExtIEs) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_2920P93_t;
typedef struct ProtocolExtensionContainer_2920P94 {
  A_SEQUENCE_OF(struct TDD_Config_EUTRA_Item_Item_ExtIEs) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_2920P94_t;
typedef struct ProtocolExtensionContainer_2920P95 {
  A_SEQUENCE_OF(struct TF_Configuration_ExtIEs) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_2920P95_t;
typedef struct ProtocolExtensionContainer_2920P96 {
  A_SEQUENCE_OF(struct TimeStamp_ExtIEs) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_2920P96_t;
typedef struct ProtocolExtensionContainer_2920P97 {
  A_SEQUENCE_OF(struct TRPMeasurementQuantitiesList_Item_ExtIEs) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_2920P97_t;
typedef struct ProtocolExtensionContainer_2920P98 {
  A_SEQUENCE_OF(struct TrpMeasurementResultItem_ExtIEs) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_2920P98_t;
typedef struct ProtocolExtensionContainer_2920P99 {
  A_SEQUENCE_OF(struct TrpMeasurementTimingQuality_ExtIEs) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_2920P99_t;
typedef struct ProtocolExtensionContainer_2920P100 {
  A_SEQUENCE_OF(struct TrpMeasurementAngleQuality_ExtIEs) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_2920P100_t;
typedef struct ProtocolExtensionContainer_2920P101 {
  A_SEQUENCE_OF(struct TRP_MeasurementRequestItem_ExtIEs) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_2920P101_t;
typedef struct ProtocolExtensionContainer_2920P102 {
  A_SEQUENCE_OF(struct TRP_MeasurementResponseItem_ExtIEs) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_2920P102_t;
typedef struct ProtocolExtensionContainer_2920P103 {
  A_SEQUENCE_OF(struct TRPInformationTRPResp_ExtIEs) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_2920P103_t;
typedef struct ProtocolExtensionContainer_2920P104 {
  A_SEQUENCE_OF(struct TRPInformation_ExtIEs) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_2920P104_t;
typedef struct ProtocolExtensionContainer_2920P105 {
  A_SEQUENCE_OF(struct TRPItem_ExtIEs) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_2920P105_t;
typedef struct ProtocolExtensionContainer_2920P106 {
  A_SEQUENCE_OF(struct TRPPositionDirect_ExtIEs) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_2920P106_t;
typedef struct ProtocolExtensionContainer_2920P107 {
  A_SEQUENCE_OF(struct TRPPositionReferenced_ExtIEs) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_2920P107_t;
typedef struct ProtocolExtensionContainer_2920P108 {
  A_SEQUENCE_OF(struct UL_AoA_ExtIEs) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_2920P108_t;
typedef struct ProtocolExtensionContainer_2920P109 {
  A_SEQUENCE_OF(struct UL_RTOAMeasurement_ExtIEs) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_2920P109_t;
typedef struct ProtocolExtensionContainer_2920P110 {
  A_SEQUENCE_OF(struct WLANMeasurementQuantitiesValue_ExtIEs) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_2920P110_t;
typedef struct ProtocolExtensionContainer_2920P111 {
  A_SEQUENCE_OF(struct WLANMeasurementResult_Item_ExtIEs) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_2920P111_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_2920P0;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_2920P0_specs_1;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_2920P0_1[1];
extern asn_per_constraints_t
    asn_PER_type_ProtocolExtensionContainer_2920P0_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_2920P1;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_2920P1_specs_3;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_2920P1_3[1];
extern asn_per_constraints_t
    asn_PER_type_ProtocolExtensionContainer_2920P1_constr_3;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_2920P2;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_2920P2_specs_5;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_2920P2_5[1];
extern asn_per_constraints_t
    asn_PER_type_ProtocolExtensionContainer_2920P2_constr_5;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_2920P3;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_2920P3_specs_7;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_2920P3_7[1];
extern asn_per_constraints_t
    asn_PER_type_ProtocolExtensionContainer_2920P3_constr_7;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_2920P4;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_2920P4_specs_9;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_2920P4_9[1];
extern asn_per_constraints_t
    asn_PER_type_ProtocolExtensionContainer_2920P4_constr_9;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_2920P5;
extern asn_SET_OF_specifics_t
    asn_SPC_ProtocolExtensionContainer_2920P5_specs_11;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_2920P5_11[1];
extern asn_per_constraints_t
    asn_PER_type_ProtocolExtensionContainer_2920P5_constr_11;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_2920P6;
extern asn_SET_OF_specifics_t
    asn_SPC_ProtocolExtensionContainer_2920P6_specs_13;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_2920P6_13[1];
extern asn_per_constraints_t
    asn_PER_type_ProtocolExtensionContainer_2920P6_constr_13;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_2920P7;
extern asn_SET_OF_specifics_t
    asn_SPC_ProtocolExtensionContainer_2920P7_specs_15;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_2920P7_15[1];
extern asn_per_constraints_t
    asn_PER_type_ProtocolExtensionContainer_2920P7_constr_15;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_2920P8;
extern asn_SET_OF_specifics_t
    asn_SPC_ProtocolExtensionContainer_2920P8_specs_17;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_2920P8_17[1];
extern asn_per_constraints_t
    asn_PER_type_ProtocolExtensionContainer_2920P8_constr_17;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_2920P9;
extern asn_SET_OF_specifics_t
    asn_SPC_ProtocolExtensionContainer_2920P9_specs_19;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_2920P9_19[1];
extern asn_per_constraints_t
    asn_PER_type_ProtocolExtensionContainer_2920P9_constr_19;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_2920P10;
extern asn_SET_OF_specifics_t
    asn_SPC_ProtocolExtensionContainer_2920P10_specs_21;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_2920P10_21[1];
extern asn_per_constraints_t
    asn_PER_type_ProtocolExtensionContainer_2920P10_constr_21;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_2920P11;
extern asn_SET_OF_specifics_t
    asn_SPC_ProtocolExtensionContainer_2920P11_specs_23;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_2920P11_23[1];
extern asn_per_constraints_t
    asn_PER_type_ProtocolExtensionContainer_2920P11_constr_23;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_2920P12;
extern asn_SET_OF_specifics_t
    asn_SPC_ProtocolExtensionContainer_2920P12_specs_25;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_2920P12_25[1];
extern asn_per_constraints_t
    asn_PER_type_ProtocolExtensionContainer_2920P12_constr_25;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_2920P13;
extern asn_SET_OF_specifics_t
    asn_SPC_ProtocolExtensionContainer_2920P13_specs_27;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_2920P13_27[1];
extern asn_per_constraints_t
    asn_PER_type_ProtocolExtensionContainer_2920P13_constr_27;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_2920P14;
extern asn_SET_OF_specifics_t
    asn_SPC_ProtocolExtensionContainer_2920P14_specs_29;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_2920P14_29[1];
extern asn_per_constraints_t
    asn_PER_type_ProtocolExtensionContainer_2920P14_constr_29;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_2920P15;
extern asn_SET_OF_specifics_t
    asn_SPC_ProtocolExtensionContainer_2920P15_specs_31;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_2920P15_31[1];
extern asn_per_constraints_t
    asn_PER_type_ProtocolExtensionContainer_2920P15_constr_31;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_2920P16;
extern asn_SET_OF_specifics_t
    asn_SPC_ProtocolExtensionContainer_2920P16_specs_33;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_2920P16_33[1];
extern asn_per_constraints_t
    asn_PER_type_ProtocolExtensionContainer_2920P16_constr_33;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_2920P17;
extern asn_SET_OF_specifics_t
    asn_SPC_ProtocolExtensionContainer_2920P17_specs_35;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_2920P17_35[1];
extern asn_per_constraints_t
    asn_PER_type_ProtocolExtensionContainer_2920P17_constr_35;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_2920P18;
extern asn_SET_OF_specifics_t
    asn_SPC_ProtocolExtensionContainer_2920P18_specs_37;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_2920P18_37[1];
extern asn_per_constraints_t
    asn_PER_type_ProtocolExtensionContainer_2920P18_constr_37;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_2920P19;
extern asn_SET_OF_specifics_t
    asn_SPC_ProtocolExtensionContainer_2920P19_specs_39;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_2920P19_39[1];
extern asn_per_constraints_t
    asn_PER_type_ProtocolExtensionContainer_2920P19_constr_39;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_2920P20;
extern asn_SET_OF_specifics_t
    asn_SPC_ProtocolExtensionContainer_2920P20_specs_41;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_2920P20_41[1];
extern asn_per_constraints_t
    asn_PER_type_ProtocolExtensionContainer_2920P20_constr_41;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_2920P21;
extern asn_SET_OF_specifics_t
    asn_SPC_ProtocolExtensionContainer_2920P21_specs_43;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_2920P21_43[1];
extern asn_per_constraints_t
    asn_PER_type_ProtocolExtensionContainer_2920P21_constr_43;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_2920P22;
extern asn_SET_OF_specifics_t
    asn_SPC_ProtocolExtensionContainer_2920P22_specs_45;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_2920P22_45[1];
extern asn_per_constraints_t
    asn_PER_type_ProtocolExtensionContainer_2920P22_constr_45;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_2920P23;
extern asn_SET_OF_specifics_t
    asn_SPC_ProtocolExtensionContainer_2920P23_specs_47;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_2920P23_47[1];
extern asn_per_constraints_t
    asn_PER_type_ProtocolExtensionContainer_2920P23_constr_47;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_2920P24;
extern asn_SET_OF_specifics_t
    asn_SPC_ProtocolExtensionContainer_2920P24_specs_49;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_2920P24_49[1];
extern asn_per_constraints_t
    asn_PER_type_ProtocolExtensionContainer_2920P24_constr_49;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_2920P25;
extern asn_SET_OF_specifics_t
    asn_SPC_ProtocolExtensionContainer_2920P25_specs_51;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_2920P25_51[1];
extern asn_per_constraints_t
    asn_PER_type_ProtocolExtensionContainer_2920P25_constr_51;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_2920P26;
extern asn_SET_OF_specifics_t
    asn_SPC_ProtocolExtensionContainer_2920P26_specs_53;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_2920P26_53[1];
extern asn_per_constraints_t
    asn_PER_type_ProtocolExtensionContainer_2920P26_constr_53;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_2920P27;
extern asn_SET_OF_specifics_t
    asn_SPC_ProtocolExtensionContainer_2920P27_specs_55;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_2920P27_55[1];
extern asn_per_constraints_t
    asn_PER_type_ProtocolExtensionContainer_2920P27_constr_55;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_2920P28;
extern asn_SET_OF_specifics_t
    asn_SPC_ProtocolExtensionContainer_2920P28_specs_57;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_2920P28_57[1];
extern asn_per_constraints_t
    asn_PER_type_ProtocolExtensionContainer_2920P28_constr_57;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_2920P29;
extern asn_SET_OF_specifics_t
    asn_SPC_ProtocolExtensionContainer_2920P29_specs_59;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_2920P29_59[1];
extern asn_per_constraints_t
    asn_PER_type_ProtocolExtensionContainer_2920P29_constr_59;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_2920P30;
extern asn_SET_OF_specifics_t
    asn_SPC_ProtocolExtensionContainer_2920P30_specs_61;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_2920P30_61[1];
extern asn_per_constraints_t
    asn_PER_type_ProtocolExtensionContainer_2920P30_constr_61;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_2920P31;
extern asn_SET_OF_specifics_t
    asn_SPC_ProtocolExtensionContainer_2920P31_specs_63;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_2920P31_63[1];
extern asn_per_constraints_t
    asn_PER_type_ProtocolExtensionContainer_2920P31_constr_63;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_2920P32;
extern asn_SET_OF_specifics_t
    asn_SPC_ProtocolExtensionContainer_2920P32_specs_65;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_2920P32_65[1];
extern asn_per_constraints_t
    asn_PER_type_ProtocolExtensionContainer_2920P32_constr_65;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_2920P33;
extern asn_SET_OF_specifics_t
    asn_SPC_ProtocolExtensionContainer_2920P33_specs_67;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_2920P33_67[1];
extern asn_per_constraints_t
    asn_PER_type_ProtocolExtensionContainer_2920P33_constr_67;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_2920P34;
extern asn_SET_OF_specifics_t
    asn_SPC_ProtocolExtensionContainer_2920P34_specs_69;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_2920P34_69[1];
extern asn_per_constraints_t
    asn_PER_type_ProtocolExtensionContainer_2920P34_constr_69;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_2920P35;
extern asn_SET_OF_specifics_t
    asn_SPC_ProtocolExtensionContainer_2920P35_specs_71;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_2920P35_71[1];
extern asn_per_constraints_t
    asn_PER_type_ProtocolExtensionContainer_2920P35_constr_71;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_2920P36;
extern asn_SET_OF_specifics_t
    asn_SPC_ProtocolExtensionContainer_2920P36_specs_73;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_2920P36_73[1];
extern asn_per_constraints_t
    asn_PER_type_ProtocolExtensionContainer_2920P36_constr_73;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_2920P37;
extern asn_SET_OF_specifics_t
    asn_SPC_ProtocolExtensionContainer_2920P37_specs_75;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_2920P37_75[1];
extern asn_per_constraints_t
    asn_PER_type_ProtocolExtensionContainer_2920P37_constr_75;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_2920P38;
extern asn_SET_OF_specifics_t
    asn_SPC_ProtocolExtensionContainer_2920P38_specs_77;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_2920P38_77[1];
extern asn_per_constraints_t
    asn_PER_type_ProtocolExtensionContainer_2920P38_constr_77;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_2920P39;
extern asn_SET_OF_specifics_t
    asn_SPC_ProtocolExtensionContainer_2920P39_specs_79;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_2920P39_79[1];
extern asn_per_constraints_t
    asn_PER_type_ProtocolExtensionContainer_2920P39_constr_79;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_2920P40;
extern asn_SET_OF_specifics_t
    asn_SPC_ProtocolExtensionContainer_2920P40_specs_81;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_2920P40_81[1];
extern asn_per_constraints_t
    asn_PER_type_ProtocolExtensionContainer_2920P40_constr_81;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_2920P41;
extern asn_SET_OF_specifics_t
    asn_SPC_ProtocolExtensionContainer_2920P41_specs_83;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_2920P41_83[1];
extern asn_per_constraints_t
    asn_PER_type_ProtocolExtensionContainer_2920P41_constr_83;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_2920P42;
extern asn_SET_OF_specifics_t
    asn_SPC_ProtocolExtensionContainer_2920P42_specs_85;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_2920P42_85[1];
extern asn_per_constraints_t
    asn_PER_type_ProtocolExtensionContainer_2920P42_constr_85;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_2920P43;
extern asn_SET_OF_specifics_t
    asn_SPC_ProtocolExtensionContainer_2920P43_specs_87;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_2920P43_87[1];
extern asn_per_constraints_t
    asn_PER_type_ProtocolExtensionContainer_2920P43_constr_87;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_2920P44;
extern asn_SET_OF_specifics_t
    asn_SPC_ProtocolExtensionContainer_2920P44_specs_89;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_2920P44_89[1];
extern asn_per_constraints_t
    asn_PER_type_ProtocolExtensionContainer_2920P44_constr_89;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_2920P45;
extern asn_SET_OF_specifics_t
    asn_SPC_ProtocolExtensionContainer_2920P45_specs_91;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_2920P45_91[1];
extern asn_per_constraints_t
    asn_PER_type_ProtocolExtensionContainer_2920P45_constr_91;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_2920P46;
extern asn_SET_OF_specifics_t
    asn_SPC_ProtocolExtensionContainer_2920P46_specs_93;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_2920P46_93[1];
extern asn_per_constraints_t
    asn_PER_type_ProtocolExtensionContainer_2920P46_constr_93;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_2920P47;
extern asn_SET_OF_specifics_t
    asn_SPC_ProtocolExtensionContainer_2920P47_specs_95;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_2920P47_95[1];
extern asn_per_constraints_t
    asn_PER_type_ProtocolExtensionContainer_2920P47_constr_95;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_2920P48;
extern asn_SET_OF_specifics_t
    asn_SPC_ProtocolExtensionContainer_2920P48_specs_97;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_2920P48_97[1];
extern asn_per_constraints_t
    asn_PER_type_ProtocolExtensionContainer_2920P48_constr_97;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_2920P49;
extern asn_SET_OF_specifics_t
    asn_SPC_ProtocolExtensionContainer_2920P49_specs_99;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_2920P49_99[1];
extern asn_per_constraints_t
    asn_PER_type_ProtocolExtensionContainer_2920P49_constr_99;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_2920P50;
extern asn_SET_OF_specifics_t
    asn_SPC_ProtocolExtensionContainer_2920P50_specs_101;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_2920P50_101[1];
extern asn_per_constraints_t
    asn_PER_type_ProtocolExtensionContainer_2920P50_constr_101;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_2920P51;
extern asn_SET_OF_specifics_t
    asn_SPC_ProtocolExtensionContainer_2920P51_specs_103;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_2920P51_103[1];
extern asn_per_constraints_t
    asn_PER_type_ProtocolExtensionContainer_2920P51_constr_103;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_2920P52;
extern asn_SET_OF_specifics_t
    asn_SPC_ProtocolExtensionContainer_2920P52_specs_105;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_2920P52_105[1];
extern asn_per_constraints_t
    asn_PER_type_ProtocolExtensionContainer_2920P52_constr_105;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_2920P53;
extern asn_SET_OF_specifics_t
    asn_SPC_ProtocolExtensionContainer_2920P53_specs_107;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_2920P53_107[1];
extern asn_per_constraints_t
    asn_PER_type_ProtocolExtensionContainer_2920P53_constr_107;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_2920P54;
extern asn_SET_OF_specifics_t
    asn_SPC_ProtocolExtensionContainer_2920P54_specs_109;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_2920P54_109[1];
extern asn_per_constraints_t
    asn_PER_type_ProtocolExtensionContainer_2920P54_constr_109;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_2920P55;
extern asn_SET_OF_specifics_t
    asn_SPC_ProtocolExtensionContainer_2920P55_specs_111;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_2920P55_111[1];
extern asn_per_constraints_t
    asn_PER_type_ProtocolExtensionContainer_2920P55_constr_111;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_2920P56;
extern asn_SET_OF_specifics_t
    asn_SPC_ProtocolExtensionContainer_2920P56_specs_113;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_2920P56_113[1];
extern asn_per_constraints_t
    asn_PER_type_ProtocolExtensionContainer_2920P56_constr_113;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_2920P57;
extern asn_SET_OF_specifics_t
    asn_SPC_ProtocolExtensionContainer_2920P57_specs_115;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_2920P57_115[1];
extern asn_per_constraints_t
    asn_PER_type_ProtocolExtensionContainer_2920P57_constr_115;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_2920P58;
extern asn_SET_OF_specifics_t
    asn_SPC_ProtocolExtensionContainer_2920P58_specs_117;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_2920P58_117[1];
extern asn_per_constraints_t
    asn_PER_type_ProtocolExtensionContainer_2920P58_constr_117;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_2920P59;
extern asn_SET_OF_specifics_t
    asn_SPC_ProtocolExtensionContainer_2920P59_specs_119;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_2920P59_119[1];
extern asn_per_constraints_t
    asn_PER_type_ProtocolExtensionContainer_2920P59_constr_119;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_2920P60;
extern asn_SET_OF_specifics_t
    asn_SPC_ProtocolExtensionContainer_2920P60_specs_121;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_2920P60_121[1];
extern asn_per_constraints_t
    asn_PER_type_ProtocolExtensionContainer_2920P60_constr_121;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_2920P61;
extern asn_SET_OF_specifics_t
    asn_SPC_ProtocolExtensionContainer_2920P61_specs_123;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_2920P61_123[1];
extern asn_per_constraints_t
    asn_PER_type_ProtocolExtensionContainer_2920P61_constr_123;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_2920P62;
extern asn_SET_OF_specifics_t
    asn_SPC_ProtocolExtensionContainer_2920P62_specs_125;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_2920P62_125[1];
extern asn_per_constraints_t
    asn_PER_type_ProtocolExtensionContainer_2920P62_constr_125;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_2920P63;
extern asn_SET_OF_specifics_t
    asn_SPC_ProtocolExtensionContainer_2920P63_specs_127;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_2920P63_127[1];
extern asn_per_constraints_t
    asn_PER_type_ProtocolExtensionContainer_2920P63_constr_127;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_2920P64;
extern asn_SET_OF_specifics_t
    asn_SPC_ProtocolExtensionContainer_2920P64_specs_129;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_2920P64_129[1];
extern asn_per_constraints_t
    asn_PER_type_ProtocolExtensionContainer_2920P64_constr_129;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_2920P65;
extern asn_SET_OF_specifics_t
    asn_SPC_ProtocolExtensionContainer_2920P65_specs_131;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_2920P65_131[1];
extern asn_per_constraints_t
    asn_PER_type_ProtocolExtensionContainer_2920P65_constr_131;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_2920P66;
extern asn_SET_OF_specifics_t
    asn_SPC_ProtocolExtensionContainer_2920P66_specs_133;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_2920P66_133[1];
extern asn_per_constraints_t
    asn_PER_type_ProtocolExtensionContainer_2920P66_constr_133;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_2920P67;
extern asn_SET_OF_specifics_t
    asn_SPC_ProtocolExtensionContainer_2920P67_specs_135;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_2920P67_135[1];
extern asn_per_constraints_t
    asn_PER_type_ProtocolExtensionContainer_2920P67_constr_135;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_2920P68;
extern asn_SET_OF_specifics_t
    asn_SPC_ProtocolExtensionContainer_2920P68_specs_137;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_2920P68_137[1];
extern asn_per_constraints_t
    asn_PER_type_ProtocolExtensionContainer_2920P68_constr_137;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_2920P69;
extern asn_SET_OF_specifics_t
    asn_SPC_ProtocolExtensionContainer_2920P69_specs_139;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_2920P69_139[1];
extern asn_per_constraints_t
    asn_PER_type_ProtocolExtensionContainer_2920P69_constr_139;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_2920P70;
extern asn_SET_OF_specifics_t
    asn_SPC_ProtocolExtensionContainer_2920P70_specs_141;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_2920P70_141[1];
extern asn_per_constraints_t
    asn_PER_type_ProtocolExtensionContainer_2920P70_constr_141;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_2920P71;
extern asn_SET_OF_specifics_t
    asn_SPC_ProtocolExtensionContainer_2920P71_specs_143;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_2920P71_143[1];
extern asn_per_constraints_t
    asn_PER_type_ProtocolExtensionContainer_2920P71_constr_143;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_2920P72;
extern asn_SET_OF_specifics_t
    asn_SPC_ProtocolExtensionContainer_2920P72_specs_145;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_2920P72_145[1];
extern asn_per_constraints_t
    asn_PER_type_ProtocolExtensionContainer_2920P72_constr_145;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_2920P73;
extern asn_SET_OF_specifics_t
    asn_SPC_ProtocolExtensionContainer_2920P73_specs_147;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_2920P73_147[1];
extern asn_per_constraints_t
    asn_PER_type_ProtocolExtensionContainer_2920P73_constr_147;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_2920P74;
extern asn_SET_OF_specifics_t
    asn_SPC_ProtocolExtensionContainer_2920P74_specs_149;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_2920P74_149[1];
extern asn_per_constraints_t
    asn_PER_type_ProtocolExtensionContainer_2920P74_constr_149;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_2920P75;
extern asn_SET_OF_specifics_t
    asn_SPC_ProtocolExtensionContainer_2920P75_specs_151;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_2920P75_151[1];
extern asn_per_constraints_t
    asn_PER_type_ProtocolExtensionContainer_2920P75_constr_151;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_2920P76;
extern asn_SET_OF_specifics_t
    asn_SPC_ProtocolExtensionContainer_2920P76_specs_153;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_2920P76_153[1];
extern asn_per_constraints_t
    asn_PER_type_ProtocolExtensionContainer_2920P76_constr_153;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_2920P77;
extern asn_SET_OF_specifics_t
    asn_SPC_ProtocolExtensionContainer_2920P77_specs_155;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_2920P77_155[1];
extern asn_per_constraints_t
    asn_PER_type_ProtocolExtensionContainer_2920P77_constr_155;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_2920P78;
extern asn_SET_OF_specifics_t
    asn_SPC_ProtocolExtensionContainer_2920P78_specs_157;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_2920P78_157[1];
extern asn_per_constraints_t
    asn_PER_type_ProtocolExtensionContainer_2920P78_constr_157;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_2920P79;
extern asn_SET_OF_specifics_t
    asn_SPC_ProtocolExtensionContainer_2920P79_specs_159;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_2920P79_159[1];
extern asn_per_constraints_t
    asn_PER_type_ProtocolExtensionContainer_2920P79_constr_159;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_2920P80;
extern asn_SET_OF_specifics_t
    asn_SPC_ProtocolExtensionContainer_2920P80_specs_161;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_2920P80_161[1];
extern asn_per_constraints_t
    asn_PER_type_ProtocolExtensionContainer_2920P80_constr_161;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_2920P81;
extern asn_SET_OF_specifics_t
    asn_SPC_ProtocolExtensionContainer_2920P81_specs_163;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_2920P81_163[1];
extern asn_per_constraints_t
    asn_PER_type_ProtocolExtensionContainer_2920P81_constr_163;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_2920P82;
extern asn_SET_OF_specifics_t
    asn_SPC_ProtocolExtensionContainer_2920P82_specs_165;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_2920P82_165[1];
extern asn_per_constraints_t
    asn_PER_type_ProtocolExtensionContainer_2920P82_constr_165;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_2920P83;
extern asn_SET_OF_specifics_t
    asn_SPC_ProtocolExtensionContainer_2920P83_specs_167;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_2920P83_167[1];
extern asn_per_constraints_t
    asn_PER_type_ProtocolExtensionContainer_2920P83_constr_167;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_2920P84;
extern asn_SET_OF_specifics_t
    asn_SPC_ProtocolExtensionContainer_2920P84_specs_169;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_2920P84_169[1];
extern asn_per_constraints_t
    asn_PER_type_ProtocolExtensionContainer_2920P84_constr_169;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_2920P85;
extern asn_SET_OF_specifics_t
    asn_SPC_ProtocolExtensionContainer_2920P85_specs_171;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_2920P85_171[1];
extern asn_per_constraints_t
    asn_PER_type_ProtocolExtensionContainer_2920P85_constr_171;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_2920P86;
extern asn_SET_OF_specifics_t
    asn_SPC_ProtocolExtensionContainer_2920P86_specs_173;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_2920P86_173[1];
extern asn_per_constraints_t
    asn_PER_type_ProtocolExtensionContainer_2920P86_constr_173;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_2920P87;
extern asn_SET_OF_specifics_t
    asn_SPC_ProtocolExtensionContainer_2920P87_specs_175;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_2920P87_175[1];
extern asn_per_constraints_t
    asn_PER_type_ProtocolExtensionContainer_2920P87_constr_175;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_2920P88;
extern asn_SET_OF_specifics_t
    asn_SPC_ProtocolExtensionContainer_2920P88_specs_177;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_2920P88_177[1];
extern asn_per_constraints_t
    asn_PER_type_ProtocolExtensionContainer_2920P88_constr_177;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_2920P89;
extern asn_SET_OF_specifics_t
    asn_SPC_ProtocolExtensionContainer_2920P89_specs_179;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_2920P89_179[1];
extern asn_per_constraints_t
    asn_PER_type_ProtocolExtensionContainer_2920P89_constr_179;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_2920P90;
extern asn_SET_OF_specifics_t
    asn_SPC_ProtocolExtensionContainer_2920P90_specs_181;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_2920P90_181[1];
extern asn_per_constraints_t
    asn_PER_type_ProtocolExtensionContainer_2920P90_constr_181;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_2920P91;
extern asn_SET_OF_specifics_t
    asn_SPC_ProtocolExtensionContainer_2920P91_specs_183;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_2920P91_183[1];
extern asn_per_constraints_t
    asn_PER_type_ProtocolExtensionContainer_2920P91_constr_183;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_2920P92;
extern asn_SET_OF_specifics_t
    asn_SPC_ProtocolExtensionContainer_2920P92_specs_185;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_2920P92_185[1];
extern asn_per_constraints_t
    asn_PER_type_ProtocolExtensionContainer_2920P92_constr_185;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_2920P93;
extern asn_SET_OF_specifics_t
    asn_SPC_ProtocolExtensionContainer_2920P93_specs_187;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_2920P93_187[1];
extern asn_per_constraints_t
    asn_PER_type_ProtocolExtensionContainer_2920P93_constr_187;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_2920P94;
extern asn_SET_OF_specifics_t
    asn_SPC_ProtocolExtensionContainer_2920P94_specs_189;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_2920P94_189[1];
extern asn_per_constraints_t
    asn_PER_type_ProtocolExtensionContainer_2920P94_constr_189;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_2920P95;
extern asn_SET_OF_specifics_t
    asn_SPC_ProtocolExtensionContainer_2920P95_specs_191;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_2920P95_191[1];
extern asn_per_constraints_t
    asn_PER_type_ProtocolExtensionContainer_2920P95_constr_191;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_2920P96;
extern asn_SET_OF_specifics_t
    asn_SPC_ProtocolExtensionContainer_2920P96_specs_193;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_2920P96_193[1];
extern asn_per_constraints_t
    asn_PER_type_ProtocolExtensionContainer_2920P96_constr_193;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_2920P97;
extern asn_SET_OF_specifics_t
    asn_SPC_ProtocolExtensionContainer_2920P97_specs_195;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_2920P97_195[1];
extern asn_per_constraints_t
    asn_PER_type_ProtocolExtensionContainer_2920P97_constr_195;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_2920P98;
extern asn_SET_OF_specifics_t
    asn_SPC_ProtocolExtensionContainer_2920P98_specs_197;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_2920P98_197[1];
extern asn_per_constraints_t
    asn_PER_type_ProtocolExtensionContainer_2920P98_constr_197;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_2920P99;
extern asn_SET_OF_specifics_t
    asn_SPC_ProtocolExtensionContainer_2920P99_specs_199;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_2920P99_199[1];
extern asn_per_constraints_t
    asn_PER_type_ProtocolExtensionContainer_2920P99_constr_199;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_2920P100;
extern asn_SET_OF_specifics_t
    asn_SPC_ProtocolExtensionContainer_2920P100_specs_201;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_2920P100_201[1];
extern asn_per_constraints_t
    asn_PER_type_ProtocolExtensionContainer_2920P100_constr_201;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_2920P101;
extern asn_SET_OF_specifics_t
    asn_SPC_ProtocolExtensionContainer_2920P101_specs_203;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_2920P101_203[1];
extern asn_per_constraints_t
    asn_PER_type_ProtocolExtensionContainer_2920P101_constr_203;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_2920P102;
extern asn_SET_OF_specifics_t
    asn_SPC_ProtocolExtensionContainer_2920P102_specs_205;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_2920P102_205[1];
extern asn_per_constraints_t
    asn_PER_type_ProtocolExtensionContainer_2920P102_constr_205;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_2920P103;
extern asn_SET_OF_specifics_t
    asn_SPC_ProtocolExtensionContainer_2920P103_specs_207;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_2920P103_207[1];
extern asn_per_constraints_t
    asn_PER_type_ProtocolExtensionContainer_2920P103_constr_207;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_2920P104;
extern asn_SET_OF_specifics_t
    asn_SPC_ProtocolExtensionContainer_2920P104_specs_209;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_2920P104_209[1];
extern asn_per_constraints_t
    asn_PER_type_ProtocolExtensionContainer_2920P104_constr_209;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_2920P105;
extern asn_SET_OF_specifics_t
    asn_SPC_ProtocolExtensionContainer_2920P105_specs_211;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_2920P105_211[1];
extern asn_per_constraints_t
    asn_PER_type_ProtocolExtensionContainer_2920P105_constr_211;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_2920P106;
extern asn_SET_OF_specifics_t
    asn_SPC_ProtocolExtensionContainer_2920P106_specs_213;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_2920P106_213[1];
extern asn_per_constraints_t
    asn_PER_type_ProtocolExtensionContainer_2920P106_constr_213;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_2920P107;
extern asn_SET_OF_specifics_t
    asn_SPC_ProtocolExtensionContainer_2920P107_specs_215;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_2920P107_215[1];
extern asn_per_constraints_t
    asn_PER_type_ProtocolExtensionContainer_2920P107_constr_215;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_2920P108;
extern asn_SET_OF_specifics_t
    asn_SPC_ProtocolExtensionContainer_2920P108_specs_217;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_2920P108_217[1];
extern asn_per_constraints_t
    asn_PER_type_ProtocolExtensionContainer_2920P108_constr_217;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_2920P109;
extern asn_SET_OF_specifics_t
    asn_SPC_ProtocolExtensionContainer_2920P109_specs_219;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_2920P109_219[1];
extern asn_per_constraints_t
    asn_PER_type_ProtocolExtensionContainer_2920P109_constr_219;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_2920P110;
extern asn_SET_OF_specifics_t
    asn_SPC_ProtocolExtensionContainer_2920P110_specs_221;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_2920P110_221[1];
extern asn_per_constraints_t
    asn_PER_type_ProtocolExtensionContainer_2920P110_constr_221;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_2920P111;
extern asn_SET_OF_specifics_t
    asn_SPC_ProtocolExtensionContainer_2920P111_specs_223;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_2920P111_223[1];
extern asn_per_constraints_t
    asn_PER_type_ProtocolExtensionContainer_2920P111_constr_223;

#ifdef __cplusplus
}
#endif

#endif /* _ProtocolExtensionContainer_H_ */
#include <asn_internal.h>
