/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NRPPA-Containers"
 * 	found in "38455.asn"
 * 	`asn1c -no-gen-OER -fcompound-names -no-gen-example -findirect-choice
 * -fno-include-deps -D nrppa`
 */

#ifndef _ProtocolIE_Field_H_
#define _ProtocolIE_Field_H_

#include <asn_application.h>

/* Including external dependencies */
#include "ProtocolIE-ID.h"
#include "Criticality.h"
#include <ANY.h>
#include <asn_ioc.h>
#include "OTDOA-Information-Type-Item.h"
#include "Presence.h"
#include <OPEN_TYPE.h>
#include <constr_CHOICE.h>
#include <constr_SEQUENCE.h>
#include "MeasurementQuantities-Item.h"
#include "ResultSS-RSRP.h"
#include "ResultSS-RSRQ.h"
#include "ResultCSI-RSRP.h"
#include "ResultCSI-RSRQ.h"
#include "UL-AoA.h"
#include "TDD-Config-EUTRA-Item.h"
#include "OtherRATMeasurementQuantities-Item.h"
#include "ResultNR.h"
#include "ResultEUTRA.h"
#include "WLANMeasurementQuantities-Item.h"
#include "UE-Measurement-ID.h"
#include "ReportCharacteristics.h"
#include "MeasurementPeriodicity.h"
#include "MeasurementQuantities.h"
#include "OtherRATMeasurementQuantities.h"
#include "WLANMeasurementQuantities.h"
#include "E-CID-MeasurementResult.h"
#include "CriticalityDiagnostics.h"
#include "Cell-Portion-ID.h"
#include "OtherRATMeasurementResult.h"
#include "WLANMeasurementResult.h"
#include "Cause.h"
#include "OTDOA-Information-Type.h"
#include "OTDOACells.h"
#include "Assistance-Information.h"
#include "Broadcast.h"
#include "PositioningBroadcastCells.h"
#include "AssistanceInformationFailureList.h"
#include "RequestedSRSTransmissionCharacteristics.h"
#include "SRSConfiguration.h"
#include "SFNInitialisationTime.h"
#include "Measurement-ID.h"
#include "TRP-MeasurementRequestList.h"
#include "TRPMeasurementQuantities.h"
#include "MeasurementBeamInfoRequest.h"
#include "SystemFrameNumber.h"
#include "SlotNumber.h"
#include "TRP-MeasurementResponseList.h"
#include "TRPList.h"
#include "TRPInformationTypeList.h"
#include "TRPInformationList.h"
#include "SRSType.h"
#include "ActivationTime.h"
#include "AbortTransmission.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum OTDOA_Information_TypeIEs__value_PR {
  OTDOA_Information_TypeIEs__value_PR_NOTHING, /* No components present */
  OTDOA_Information_TypeIEs__value_PR_OTDOA_Information_Type_Item
} OTDOA_Information_TypeIEs__value_PR;
typedef enum SRSType_ExtIEs__value_PR {
  SRSType_ExtIEs__value_PR_NOTHING /* No components present */

} SRSType_ExtIEs__value_PR;
typedef enum AbortTransmission_ExtIEs__value_PR {
  AbortTransmission_ExtIEs__value_PR_NOTHING /* No components present */

} AbortTransmission_ExtIEs__value_PR;
typedef enum Cause_ExtensionIE__value_PR {
  Cause_ExtensionIE__value_PR_NOTHING /* No components present */

} Cause_ExtensionIE__value_PR;
typedef enum DL_PRSMutingPattern_ExtIEs__value_PR {
  DL_PRSMutingPattern_ExtIEs__value_PR_NOTHING /* No components present */

} DL_PRSMutingPattern_ExtIEs__value_PR;
typedef enum DL_PRSResourceSetARPLocation_ExtIEs__value_PR {
  DL_PRSResourceSetARPLocation_ExtIEs__value_PR_NOTHING /* No components present
                                                         */

} DL_PRSResourceSetARPLocation_ExtIEs__value_PR;
typedef enum DL_PRSResourceARPLocation_ExtIEs__value_PR {
  DL_PRSResourceARPLocation_ExtIEs__value_PR_NOTHING /* No components present */

} DL_PRSResourceARPLocation_ExtIEs__value_PR;
typedef enum GNBRxTxTimeDiffMeas_ExtIEs__value_PR {
  GNBRxTxTimeDiffMeas_ExtIEs__value_PR_NOTHING /* No components present */

} GNBRxTxTimeDiffMeas_ExtIEs__value_PR;
typedef enum MeasurementQuantities_ItemIEs__value_PR {
  MeasurementQuantities_ItemIEs__value_PR_NOTHING, /* No components present */
  MeasurementQuantities_ItemIEs__value_PR_MeasurementQuantities_Item
} MeasurementQuantities_ItemIEs__value_PR;
typedef enum MeasuredResultsValue_ExtensionIE__value_PR {
  MeasuredResultsValue_ExtensionIE__value_PR_NOTHING, /* No components present
                                                       */
  MeasuredResultsValue_ExtensionIE__value_PR_ResultSS_RSRP,
  MeasuredResultsValue_ExtensionIE__value_PR_ResultSS_RSRQ,
  MeasuredResultsValue_ExtensionIE__value_PR_ResultCSI_RSRP,
  MeasuredResultsValue_ExtensionIE__value_PR_ResultCSI_RSRQ,
  MeasuredResultsValue_ExtensionIE__value_PR_UL_AoA
} MeasuredResultsValue_ExtensionIE__value_PR;
typedef enum NG_RANCell_ExtensionIE__value_PR {
  NG_RANCell_ExtensionIE__value_PR_NOTHING /* No components present */

} NG_RANCell_ExtensionIE__value_PR;
typedef enum OTDOACell_Information_Item_ExtensionIE__value_PR {
  OTDOACell_Information_Item_ExtensionIE__value_PR_NOTHING, /* No components
                                                               present */
  OTDOACell_Information_Item_ExtensionIE__value_PR_TDD_Config_EUTRA_Item
} OTDOACell_Information_Item_ExtensionIE__value_PR;
typedef enum OtherRATMeasurementQuantities_ItemIEs__value_PR {
  OtherRATMeasurementQuantities_ItemIEs__value_PR_NOTHING, /* No components
                                                              present */
  OtherRATMeasurementQuantities_ItemIEs__value_PR_OtherRATMeasurementQuantities_Item
} OtherRATMeasurementQuantities_ItemIEs__value_PR;
typedef enum OtherRATMeasuredResultsValue_ExtensionIE__value_PR {
  OtherRATMeasuredResultsValue_ExtensionIE__value_PR_NOTHING, /* No components
                                                                 present */
  OtherRATMeasuredResultsValue_ExtensionIE__value_PR_ResultNR,
  OtherRATMeasuredResultsValue_ExtensionIE__value_PR_ResultEUTRA
} OtherRATMeasuredResultsValue_ExtensionIE__value_PR;
typedef enum PathlossReferenceSignal_ExtensionIE__value_PR {
  PathlossReferenceSignal_ExtensionIE__value_PR_NOTHING /* No components present
                                                         */

} PathlossReferenceSignal_ExtensionIE__value_PR;
typedef enum PosResourceSetType_ExtIEs__value_PR {
  PosResourceSetType_ExtIEs__value_PR_NOTHING /* No components present */

} PosResourceSetType_ExtIEs__value_PR;
typedef enum PRSMutingConfiguration_EUTRA_ExtensionIE__value_PR {
  PRSMutingConfiguration_EUTRA_ExtensionIE__value_PR_NOTHING /* No components
                                                                present */

} PRSMutingConfiguration_EUTRA_ExtensionIE__value_PR;
typedef enum ReferenceSignal_ExtensionIE__value_PR {
  ReferenceSignal_ExtensionIE__value_PR_NOTHING /* No components present */

} ReferenceSignal_ExtensionIE__value_PR;
typedef enum ReferencePoint_ExtIEs__value_PR {
  ReferencePoint_ExtIEs__value_PR_NOTHING /* No components present */

} ReferencePoint_ExtIEs__value_PR;
typedef enum ResourceSetType_ExtIEs__value_PR {
  ResourceSetType_ExtIEs__value_PR_NOTHING /* No components present */

} ResourceSetType_ExtIEs__value_PR;
typedef enum ResourceType_ExtIEs__value_PR {
  ResourceType_ExtIEs__value_PR_NOTHING /* No components present */

} ResourceType_ExtIEs__value_PR;
typedef enum ResourceTypePos_ExtIEs__value_PR {
  ResourceTypePos_ExtIEs__value_PR_NOTHING /* No components present */

} ResourceTypePos_ExtIEs__value_PR;
typedef enum SpatialInformationPos_ExtIEs__value_PR {
  SpatialInformationPos_ExtIEs__value_PR_NOTHING /* No components present */

} SpatialInformationPos_ExtIEs__value_PR;
typedef enum TimeStampSlotIndex_ExtIEs__value_PR {
  TimeStampSlotIndex_ExtIEs__value_PR_NOTHING /* No components present */

} TimeStampSlotIndex_ExtIEs__value_PR;
typedef enum TransmissionComb_ExtIEs__value_PR {
  TransmissionComb_ExtIEs__value_PR_NOTHING /* No components present */

} TransmissionComb_ExtIEs__value_PR;
typedef enum TransmissionCombPos_ExtIEs__value_PR {
  TransmissionCombPos_ExtIEs__value_PR_NOTHING /* No components present */

} TransmissionCombPos_ExtIEs__value_PR;
typedef enum TrpMeasuredResultsValue_ExtIEs__value_PR {
  TrpMeasuredResultsValue_ExtIEs__value_PR_NOTHING /* No components present */

} TrpMeasuredResultsValue_ExtIEs__value_PR;
typedef enum TrpMeasurementQuality_ExtIEs__value_PR {
  TrpMeasurementQuality_ExtIEs__value_PR_NOTHING /* No components present */

} TrpMeasurementQuality_ExtIEs__value_PR;
typedef enum TRPInformationItem_ExtIEs__value_PR {
  TRPInformationItem_ExtIEs__value_PR_NOTHING /* No components present */

} TRPInformationItem_ExtIEs__value_PR;
typedef enum TRPPositionDefinitionType_ExtIEs__value_PR {
  TRPPositionDefinitionType_ExtIEs__value_PR_NOTHING /* No components present */

} TRPPositionDefinitionType_ExtIEs__value_PR;
typedef enum TRPPositionDirectAccuracy_ExtIEs__value_PR {
  TRPPositionDirectAccuracy_ExtIEs__value_PR_NOTHING /* No components present */

} TRPPositionDirectAccuracy_ExtIEs__value_PR;
typedef enum TRPReferencePointType_ExtIEs__value_PR {
  TRPReferencePointType_ExtIEs__value_PR_NOTHING /* No components present */

} TRPReferencePointType_ExtIEs__value_PR;
typedef enum WLANMeasurementQuantities_ItemIEs__value_PR {
  WLANMeasurementQuantities_ItemIEs__value_PR_NOTHING, /* No components present
                                                        */
  WLANMeasurementQuantities_ItemIEs__value_PR_WLANMeasurementQuantities_Item
} WLANMeasurementQuantities_ItemIEs__value_PR;
typedef enum E_CIDMeasurementInitiationRequest_IEs__value_PR {
  E_CIDMeasurementInitiationRequest_IEs__value_PR_NOTHING, /* No components
                                                              present */
  E_CIDMeasurementInitiationRequest_IEs__value_PR_UE_Measurement_ID,
  E_CIDMeasurementInitiationRequest_IEs__value_PR_ReportCharacteristics,
  E_CIDMeasurementInitiationRequest_IEs__value_PR_MeasurementPeriodicity,
  E_CIDMeasurementInitiationRequest_IEs__value_PR_MeasurementQuantities,
  E_CIDMeasurementInitiationRequest_IEs__value_PR_OtherRATMeasurementQuantities,
  E_CIDMeasurementInitiationRequest_IEs__value_PR_WLANMeasurementQuantities
} E_CIDMeasurementInitiationRequest_IEs__value_PR;
typedef enum E_CIDMeasurementInitiationResponse_IEs__value_PR {
  E_CIDMeasurementInitiationResponse_IEs__value_PR_NOTHING, /* No components
                                                               present */
  E_CIDMeasurementInitiationResponse_IEs__value_PR_UE_Measurement_ID,
  E_CIDMeasurementInitiationResponse_IEs__value_PR_UE_Measurement_ID_1,
  E_CIDMeasurementInitiationResponse_IEs__value_PR_E_CID_MeasurementResult,
  E_CIDMeasurementInitiationResponse_IEs__value_PR_CriticalityDiagnostics,
  E_CIDMeasurementInitiationResponse_IEs__value_PR_Cell_Portion_ID,
  E_CIDMeasurementInitiationResponse_IEs__value_PR_OtherRATMeasurementResult,
  E_CIDMeasurementInitiationResponse_IEs__value_PR_WLANMeasurementResult
} E_CIDMeasurementInitiationResponse_IEs__value_PR;
typedef enum E_CIDMeasurementInitiationFailure_IEs__value_PR {
  E_CIDMeasurementInitiationFailure_IEs__value_PR_NOTHING, /* No components
                                                              present */
  E_CIDMeasurementInitiationFailure_IEs__value_PR_UE_Measurement_ID,
  E_CIDMeasurementInitiationFailure_IEs__value_PR_Cause,
  E_CIDMeasurementInitiationFailure_IEs__value_PR_CriticalityDiagnostics
} E_CIDMeasurementInitiationFailure_IEs__value_PR;
typedef enum E_CIDMeasurementFailureIndication_IEs__value_PR {
  E_CIDMeasurementFailureIndication_IEs__value_PR_NOTHING, /* No components
                                                              present */
  E_CIDMeasurementFailureIndication_IEs__value_PR_UE_Measurement_ID,
  E_CIDMeasurementFailureIndication_IEs__value_PR_UE_Measurement_ID_1,
  E_CIDMeasurementFailureIndication_IEs__value_PR_Cause
} E_CIDMeasurementFailureIndication_IEs__value_PR;
typedef enum E_CIDMeasurementReport_IEs__value_PR {
  E_CIDMeasurementReport_IEs__value_PR_NOTHING, /* No components present */
  E_CIDMeasurementReport_IEs__value_PR_UE_Measurement_ID,
  E_CIDMeasurementReport_IEs__value_PR_UE_Measurement_ID_1,
  E_CIDMeasurementReport_IEs__value_PR_E_CID_MeasurementResult,
  E_CIDMeasurementReport_IEs__value_PR_Cell_Portion_ID
} E_CIDMeasurementReport_IEs__value_PR;
typedef enum E_CIDMeasurementTerminationCommand_IEs__value_PR {
  E_CIDMeasurementTerminationCommand_IEs__value_PR_NOTHING, /* No components
                                                               present */
  E_CIDMeasurementTerminationCommand_IEs__value_PR_UE_Measurement_ID,
  E_CIDMeasurementTerminationCommand_IEs__value_PR_UE_Measurement_ID_1
} E_CIDMeasurementTerminationCommand_IEs__value_PR;
typedef enum OTDOAInformationRequest_IEs__value_PR {
  OTDOAInformationRequest_IEs__value_PR_NOTHING, /* No components present */
  OTDOAInformationRequest_IEs__value_PR_OTDOA_Information_Type
} OTDOAInformationRequest_IEs__value_PR;
typedef enum OTDOAInformationResponse_IEs__value_PR {
  OTDOAInformationResponse_IEs__value_PR_NOTHING, /* No components present */
  OTDOAInformationResponse_IEs__value_PR_OTDOACells,
  OTDOAInformationResponse_IEs__value_PR_CriticalityDiagnostics
} OTDOAInformationResponse_IEs__value_PR;
typedef enum OTDOAInformationFailure_IEs__value_PR {
  OTDOAInformationFailure_IEs__value_PR_NOTHING, /* No components present */
  OTDOAInformationFailure_IEs__value_PR_Cause,
  OTDOAInformationFailure_IEs__value_PR_CriticalityDiagnostics
} OTDOAInformationFailure_IEs__value_PR;
typedef enum AssistanceInformationControl_IEs__value_PR {
  AssistanceInformationControl_IEs__value_PR_NOTHING, /* No components present
                                                       */
  AssistanceInformationControl_IEs__value_PR_Assistance_Information,
  AssistanceInformationControl_IEs__value_PR_Broadcast,
  AssistanceInformationControl_IEs__value_PR_PositioningBroadcastCells
} AssistanceInformationControl_IEs__value_PR;
typedef enum AssistanceInformationFeedback_IEs__value_PR {
  AssistanceInformationFeedback_IEs__value_PR_NOTHING, /* No components present
                                                        */
  AssistanceInformationFeedback_IEs__value_PR_AssistanceInformationFailureList,
  AssistanceInformationFeedback_IEs__value_PR_PositioningBroadcastCells,
  AssistanceInformationFeedback_IEs__value_PR_CriticalityDiagnostics
} AssistanceInformationFeedback_IEs__value_PR;
typedef enum ErrorIndication_IEs__value_PR {
  ErrorIndication_IEs__value_PR_NOTHING, /* No components present */
  ErrorIndication_IEs__value_PR_Cause,
  ErrorIndication_IEs__value_PR_CriticalityDiagnostics
} ErrorIndication_IEs__value_PR;
typedef enum PositioningInformationRequest_IEs__value_PR {
  PositioningInformationRequest_IEs__value_PR_NOTHING, /* No components present
                                                        */
  PositioningInformationRequest_IEs__value_PR_RequestedSRSTransmissionCharacteristics
} PositioningInformationRequest_IEs__value_PR;
typedef enum PositioningInformationResponse_IEs__value_PR {
  PositioningInformationResponse_IEs__value_PR_NOTHING, /* No components present
                                                         */
  PositioningInformationResponse_IEs__value_PR_SRSConfiguration,
  PositioningInformationResponse_IEs__value_PR_SFNInitialisationTime,
  PositioningInformationResponse_IEs__value_PR_CriticalityDiagnostics
} PositioningInformationResponse_IEs__value_PR;
typedef enum PositioningInformationFailure_IEs__value_PR {
  PositioningInformationFailure_IEs__value_PR_NOTHING, /* No components present
                                                        */
  PositioningInformationFailure_IEs__value_PR_Cause,
  PositioningInformationFailure_IEs__value_PR_CriticalityDiagnostics
} PositioningInformationFailure_IEs__value_PR;
typedef enum PositioningInformationUpdate_IEs__value_PR {
  PositioningInformationUpdate_IEs__value_PR_NOTHING, /* No components present
                                                       */
  PositioningInformationUpdate_IEs__value_PR_SRSConfiguration,
  PositioningInformationUpdate_IEs__value_PR_SFNInitialisationTime
} PositioningInformationUpdate_IEs__value_PR;
typedef enum MeasurementRequest_IEs__value_PR {
  MeasurementRequest_IEs__value_PR_NOTHING, /* No components present */
  MeasurementRequest_IEs__value_PR_Measurement_ID,
  MeasurementRequest_IEs__value_PR_TRP_MeasurementRequestList,
  MeasurementRequest_IEs__value_PR_ReportCharacteristics,
  MeasurementRequest_IEs__value_PR_MeasurementPeriodicity,
  MeasurementRequest_IEs__value_PR_TRPMeasurementQuantities,
  MeasurementRequest_IEs__value_PR_SRSConfiguration,
  MeasurementRequest_IEs__value_PR_SFNInitialisationTime,
  MeasurementRequest_IEs__value_PR_MeasurementBeamInfoRequest,
  MeasurementRequest_IEs__value_PR_SystemFrameNumber,
  MeasurementRequest_IEs__value_PR_SlotNumber
} MeasurementRequest_IEs__value_PR;
typedef enum MeasurementResponse_IEs__value_PR {
  MeasurementResponse_IEs__value_PR_NOTHING, /* No components present */
  MeasurementResponse_IEs__value_PR_Measurement_ID,
  MeasurementResponse_IEs__value_PR_Measurement_ID_1,
  MeasurementResponse_IEs__value_PR_TRP_MeasurementResponseList,
  MeasurementResponse_IEs__value_PR_CriticalityDiagnostics
} MeasurementResponse_IEs__value_PR;
typedef enum MeasurementFailure_IEs__value_PR {
  MeasurementFailure_IEs__value_PR_NOTHING, /* No components present */
  MeasurementFailure_IEs__value_PR_Measurement_ID,
  MeasurementFailure_IEs__value_PR_Cause,
  MeasurementFailure_IEs__value_PR_CriticalityDiagnostics
} MeasurementFailure_IEs__value_PR;
typedef enum MeasurementReport_IEs__value_PR {
  MeasurementReport_IEs__value_PR_NOTHING, /* No components present */
  MeasurementReport_IEs__value_PR_Measurement_ID,
  MeasurementReport_IEs__value_PR_Measurement_ID_1,
  MeasurementReport_IEs__value_PR_TRP_MeasurementResponseList
} MeasurementReport_IEs__value_PR;
typedef enum MeasurementUpdate_IEs__value_PR {
  MeasurementUpdate_IEs__value_PR_NOTHING, /* No components present */
  MeasurementUpdate_IEs__value_PR_Measurement_ID,
  MeasurementUpdate_IEs__value_PR_Measurement_ID_1,
  MeasurementUpdate_IEs__value_PR_SRSConfiguration
} MeasurementUpdate_IEs__value_PR;
typedef enum MeasurementAbort_IEs__value_PR {
  MeasurementAbort_IEs__value_PR_NOTHING, /* No components present */
  MeasurementAbort_IEs__value_PR_Measurement_ID,
  MeasurementAbort_IEs__value_PR_Measurement_ID_1
} MeasurementAbort_IEs__value_PR;
typedef enum MeasurementFailureIndication_IEs__value_PR {
  MeasurementFailureIndication_IEs__value_PR_NOTHING, /* No components present
                                                       */
  MeasurementFailureIndication_IEs__value_PR_Measurement_ID,
  MeasurementFailureIndication_IEs__value_PR_Measurement_ID_1,
  MeasurementFailureIndication_IEs__value_PR_Cause
} MeasurementFailureIndication_IEs__value_PR;
typedef enum TRPInformationRequest_IEs__value_PR {
  TRPInformationRequest_IEs__value_PR_NOTHING, /* No components present */
  TRPInformationRequest_IEs__value_PR_TRPList,
  TRPInformationRequest_IEs__value_PR_TRPInformationTypeList
} TRPInformationRequest_IEs__value_PR;
typedef enum TRPInformationResponse_IEs__value_PR {
  TRPInformationResponse_IEs__value_PR_NOTHING, /* No components present */
  TRPInformationResponse_IEs__value_PR_TRPInformationList,
  TRPInformationResponse_IEs__value_PR_CriticalityDiagnostics
} TRPInformationResponse_IEs__value_PR;
typedef enum TRPInformationFailure_IEs__value_PR {
  TRPInformationFailure_IEs__value_PR_NOTHING, /* No components present */
  TRPInformationFailure_IEs__value_PR_Cause,
  TRPInformationFailure_IEs__value_PR_CriticalityDiagnostics
} TRPInformationFailure_IEs__value_PR;
typedef enum PositioningActivationRequestIEs__value_PR {
  PositioningActivationRequestIEs__value_PR_NOTHING, /* No components present */
  PositioningActivationRequestIEs__value_PR_SRSType,
  PositioningActivationRequestIEs__value_PR_ActivationTime
} PositioningActivationRequestIEs__value_PR;
typedef enum PositioningActivationResponseIEs__value_PR {
  PositioningActivationResponseIEs__value_PR_NOTHING, /* No components present
                                                       */
  PositioningActivationResponseIEs__value_PR_CriticalityDiagnostics,
  PositioningActivationResponseIEs__value_PR_SystemFrameNumber,
  PositioningActivationResponseIEs__value_PR_SlotNumber
} PositioningActivationResponseIEs__value_PR;
typedef enum PositioningActivationFailureIEs__value_PR {
  PositioningActivationFailureIEs__value_PR_NOTHING, /* No components present */
  PositioningActivationFailureIEs__value_PR_Cause,
  PositioningActivationFailureIEs__value_PR_CriticalityDiagnostics
} PositioningActivationFailureIEs__value_PR;
typedef enum PositioningDeactivationIEs__value_PR {
  PositioningDeactivationIEs__value_PR_NOTHING, /* No components present */
  PositioningDeactivationIEs__value_PR_AbortTransmission
} PositioningDeactivationIEs__value_PR;

/* ProtocolIE-Field */
typedef struct OTDOA_Information_TypeIEs {
  ProtocolIE_ID_t id;
  Criticality_t criticality;
  struct OTDOA_Information_TypeIEs__value {
    OTDOA_Information_TypeIEs__value_PR present;
    union OTDOA_Information_TypeIEs__value_u {
      OTDOA_Information_Type_Item_t OTDOA_Information_Type_Item;
    } choice;

    /* Context for parsing across buffer boundaries */
    asn_struct_ctx_t _asn_ctx;
  } value;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} OTDOA_Information_TypeIEs_t;
typedef struct SRSType_ExtIEs {
  ProtocolIE_ID_t id;
  Criticality_t criticality;
  struct SRSType_ExtIEs__value {
    SRSType_ExtIEs__value_PR present;
    union SRSType_ExtIEs__value_u {
    } choice;

    /* Context for parsing across buffer boundaries */
    asn_struct_ctx_t _asn_ctx;
  } value;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} SRSType_ExtIEs_t;
typedef struct AbortTransmission_ExtIEs {
  ProtocolIE_ID_t id;
  Criticality_t criticality;
  struct AbortTransmission_ExtIEs__value {
    AbortTransmission_ExtIEs__value_PR present;
    union AbortTransmission_ExtIEs__value_u {
    } choice;

    /* Context for parsing across buffer boundaries */
    asn_struct_ctx_t _asn_ctx;
  } value;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} AbortTransmission_ExtIEs_t;
typedef struct Cause_ExtensionIE {
  ProtocolIE_ID_t id;
  Criticality_t criticality;
  struct Cause_ExtensionIE__value {
    Cause_ExtensionIE__value_PR present;
    union Cause_ExtensionIE__value_u {
    } choice;

    /* Context for parsing across buffer boundaries */
    asn_struct_ctx_t _asn_ctx;
  } value;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} Cause_ExtensionIE_t;
typedef struct DL_PRSMutingPattern_ExtIEs {
  ProtocolIE_ID_t id;
  Criticality_t criticality;
  struct DL_PRSMutingPattern_ExtIEs__value {
    DL_PRSMutingPattern_ExtIEs__value_PR present;
    union DL_PRSMutingPattern_ExtIEs__value_u {
    } choice;

    /* Context for parsing across buffer boundaries */
    asn_struct_ctx_t _asn_ctx;
  } value;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} DL_PRSMutingPattern_ExtIEs_t;
typedef struct DL_PRSResourceSetARPLocation_ExtIEs {
  ProtocolIE_ID_t id;
  Criticality_t criticality;
  struct DL_PRSResourceSetARPLocation_ExtIEs__value {
    DL_PRSResourceSetARPLocation_ExtIEs__value_PR present;
    union DL_PRSResourceSetARPLocation_ExtIEs__value_u {
    } choice;

    /* Context for parsing across buffer boundaries */
    asn_struct_ctx_t _asn_ctx;
  } value;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} DL_PRSResourceSetARPLocation_ExtIEs_t;
typedef struct DL_PRSResourceARPLocation_ExtIEs {
  ProtocolIE_ID_t id;
  Criticality_t criticality;
  struct DL_PRSResourceARPLocation_ExtIEs__value {
    DL_PRSResourceARPLocation_ExtIEs__value_PR present;
    union DL_PRSResourceARPLocation_ExtIEs__value_u {
    } choice;

    /* Context for parsing across buffer boundaries */
    asn_struct_ctx_t _asn_ctx;
  } value;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} DL_PRSResourceARPLocation_ExtIEs_t;
typedef struct GNBRxTxTimeDiffMeas_ExtIEs {
  ProtocolIE_ID_t id;
  Criticality_t criticality;
  struct GNBRxTxTimeDiffMeas_ExtIEs__value {
    GNBRxTxTimeDiffMeas_ExtIEs__value_PR present;
    union GNBRxTxTimeDiffMeas_ExtIEs__value_u {
    } choice;

    /* Context for parsing across buffer boundaries */
    asn_struct_ctx_t _asn_ctx;
  } value;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} GNBRxTxTimeDiffMeas_ExtIEs_t;
typedef struct MeasurementQuantities_ItemIEs {
  ProtocolIE_ID_t id;
  Criticality_t criticality;
  struct MeasurementQuantities_ItemIEs__value {
    MeasurementQuantities_ItemIEs__value_PR present;
    union MeasurementQuantities_ItemIEs__value_u {
      MeasurementQuantities_Item_t MeasurementQuantities_Item;
    } choice;

    /* Context for parsing across buffer boundaries */
    asn_struct_ctx_t _asn_ctx;
  } value;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} MeasurementQuantities_ItemIEs_t;
typedef struct MeasuredResultsValue_ExtensionIE {
  ProtocolIE_ID_t id;
  Criticality_t criticality;
  struct MeasuredResultsValue_ExtensionIE__value {
    MeasuredResultsValue_ExtensionIE__value_PR present;
    union MeasuredResultsValue_ExtensionIE__value_u {
      ResultSS_RSRP_t ResultSS_RSRP;
      ResultSS_RSRQ_t ResultSS_RSRQ;
      ResultCSI_RSRP_t ResultCSI_RSRP;
      ResultCSI_RSRQ_t ResultCSI_RSRQ;
      UL_AoA_t UL_AoA;
    } choice;

    /* Context for parsing across buffer boundaries */
    asn_struct_ctx_t _asn_ctx;
  } value;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} MeasuredResultsValue_ExtensionIE_t;
typedef struct NG_RANCell_ExtensionIE {
  ProtocolIE_ID_t id;
  Criticality_t criticality;
  struct NG_RANCell_ExtensionIE__value {
    NG_RANCell_ExtensionIE__value_PR present;
    union NG_RANCell_ExtensionIE__value_u {
    } choice;

    /* Context for parsing across buffer boundaries */
    asn_struct_ctx_t _asn_ctx;
  } value;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} NG_RANCell_ExtensionIE_t;
typedef struct OTDOACell_Information_Item_ExtensionIE {
  ProtocolIE_ID_t id;
  Criticality_t criticality;
  struct OTDOACell_Information_Item_ExtensionIE__value {
    OTDOACell_Information_Item_ExtensionIE__value_PR present;
    union OTDOACell_Information_Item_ExtensionIE__value_u {
      TDD_Config_EUTRA_Item_t TDD_Config_EUTRA_Item;
    } choice;

    /* Context for parsing across buffer boundaries */
    asn_struct_ctx_t _asn_ctx;
  } value;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} OTDOACell_Information_Item_ExtensionIE_t;
typedef struct OtherRATMeasurementQuantities_ItemIEs {
  ProtocolIE_ID_t id;
  Criticality_t criticality;
  struct OtherRATMeasurementQuantities_ItemIEs__value {
    OtherRATMeasurementQuantities_ItemIEs__value_PR present;
    union OtherRATMeasurementQuantities_ItemIEs__value_u {
      OtherRATMeasurementQuantities_Item_t OtherRATMeasurementQuantities_Item;
    } choice;

    /* Context for parsing across buffer boundaries */
    asn_struct_ctx_t _asn_ctx;
  } value;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} OtherRATMeasurementQuantities_ItemIEs_t;
typedef struct OtherRATMeasuredResultsValue_ExtensionIE {
  ProtocolIE_ID_t id;
  Criticality_t criticality;
  struct OtherRATMeasuredResultsValue_ExtensionIE__value {
    OtherRATMeasuredResultsValue_ExtensionIE__value_PR present;
    union OtherRATMeasuredResultsValue_ExtensionIE__value_u {
      ResultNR_t ResultNR;
      ResultEUTRA_t ResultEUTRA;
    } choice;

    /* Context for parsing across buffer boundaries */
    asn_struct_ctx_t _asn_ctx;
  } value;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} OtherRATMeasuredResultsValue_ExtensionIE_t;
typedef struct PathlossReferenceSignal_ExtensionIE {
  ProtocolIE_ID_t id;
  Criticality_t criticality;
  struct PathlossReferenceSignal_ExtensionIE__value {
    PathlossReferenceSignal_ExtensionIE__value_PR present;
    union PathlossReferenceSignal_ExtensionIE__value_u {
    } choice;

    /* Context for parsing across buffer boundaries */
    asn_struct_ctx_t _asn_ctx;
  } value;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} PathlossReferenceSignal_ExtensionIE_t;
typedef struct PosResourceSetType_ExtIEs {
  ProtocolIE_ID_t id;
  Criticality_t criticality;
  struct PosResourceSetType_ExtIEs__value {
    PosResourceSetType_ExtIEs__value_PR present;
    union PosResourceSetType_ExtIEs__value_u {
    } choice;

    /* Context for parsing across buffer boundaries */
    asn_struct_ctx_t _asn_ctx;
  } value;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} PosResourceSetType_ExtIEs_t;
typedef struct PRSMutingConfiguration_EUTRA_ExtensionIE {
  ProtocolIE_ID_t id;
  Criticality_t criticality;
  struct PRSMutingConfiguration_EUTRA_ExtensionIE__value {
    PRSMutingConfiguration_EUTRA_ExtensionIE__value_PR present;
    union PRSMutingConfiguration_EUTRA_ExtensionIE__value_u {
    } choice;

    /* Context for parsing across buffer boundaries */
    asn_struct_ctx_t _asn_ctx;
  } value;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} PRSMutingConfiguration_EUTRA_ExtensionIE_t;
typedef struct ReferenceSignal_ExtensionIE {
  ProtocolIE_ID_t id;
  Criticality_t criticality;
  struct ReferenceSignal_ExtensionIE__value {
    ReferenceSignal_ExtensionIE__value_PR present;
    union ReferenceSignal_ExtensionIE__value_u {
    } choice;

    /* Context for parsing across buffer boundaries */
    asn_struct_ctx_t _asn_ctx;
  } value;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} ReferenceSignal_ExtensionIE_t;
typedef struct ReferencePoint_ExtIEs {
  ProtocolIE_ID_t id;
  Criticality_t criticality;
  struct ReferencePoint_ExtIEs__value {
    ReferencePoint_ExtIEs__value_PR present;
    union ReferencePoint_ExtIEs__value_u {
    } choice;

    /* Context for parsing across buffer boundaries */
    asn_struct_ctx_t _asn_ctx;
  } value;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} ReferencePoint_ExtIEs_t;
typedef struct ResourceSetType_ExtIEs {
  ProtocolIE_ID_t id;
  Criticality_t criticality;
  struct ResourceSetType_ExtIEs__value {
    ResourceSetType_ExtIEs__value_PR present;
    union ResourceSetType_ExtIEs__value_u {
    } choice;

    /* Context for parsing across buffer boundaries */
    asn_struct_ctx_t _asn_ctx;
  } value;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} ResourceSetType_ExtIEs_t;
typedef struct ResourceType_ExtIEs {
  ProtocolIE_ID_t id;
  Criticality_t criticality;
  struct ResourceType_ExtIEs__value {
    ResourceType_ExtIEs__value_PR present;
    union ResourceType_ExtIEs__value_u {
    } choice;

    /* Context for parsing across buffer boundaries */
    asn_struct_ctx_t _asn_ctx;
  } value;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} ResourceType_ExtIEs_t;
typedef struct ResourceTypePos_ExtIEs {
  ProtocolIE_ID_t id;
  Criticality_t criticality;
  struct ResourceTypePos_ExtIEs__value {
    ResourceTypePos_ExtIEs__value_PR present;
    union ResourceTypePos_ExtIEs__value_u {
    } choice;

    /* Context for parsing across buffer boundaries */
    asn_struct_ctx_t _asn_ctx;
  } value;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} ResourceTypePos_ExtIEs_t;
typedef struct SpatialInformationPos_ExtIEs {
  ProtocolIE_ID_t id;
  Criticality_t criticality;
  struct SpatialInformationPos_ExtIEs__value {
    SpatialInformationPos_ExtIEs__value_PR present;
    union SpatialInformationPos_ExtIEs__value_u {
    } choice;

    /* Context for parsing across buffer boundaries */
    asn_struct_ctx_t _asn_ctx;
  } value;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} SpatialInformationPos_ExtIEs_t;
typedef struct TimeStampSlotIndex_ExtIEs {
  ProtocolIE_ID_t id;
  Criticality_t criticality;
  struct TimeStampSlotIndex_ExtIEs__value {
    TimeStampSlotIndex_ExtIEs__value_PR present;
    union TimeStampSlotIndex_ExtIEs__value_u {
    } choice;

    /* Context for parsing across buffer boundaries */
    asn_struct_ctx_t _asn_ctx;
  } value;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} TimeStampSlotIndex_ExtIEs_t;
typedef struct TransmissionComb_ExtIEs {
  ProtocolIE_ID_t id;
  Criticality_t criticality;
  struct TransmissionComb_ExtIEs__value {
    TransmissionComb_ExtIEs__value_PR present;
    union TransmissionComb_ExtIEs__value_u {
    } choice;

    /* Context for parsing across buffer boundaries */
    asn_struct_ctx_t _asn_ctx;
  } value;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} TransmissionComb_ExtIEs_t;
typedef struct TransmissionCombPos_ExtIEs {
  ProtocolIE_ID_t id;
  Criticality_t criticality;
  struct TransmissionCombPos_ExtIEs__value {
    TransmissionCombPos_ExtIEs__value_PR present;
    union TransmissionCombPos_ExtIEs__value_u {
    } choice;

    /* Context for parsing across buffer boundaries */
    asn_struct_ctx_t _asn_ctx;
  } value;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} TransmissionCombPos_ExtIEs_t;
typedef struct TrpMeasuredResultsValue_ExtIEs {
  ProtocolIE_ID_t id;
  Criticality_t criticality;
  struct TrpMeasuredResultsValue_ExtIEs__value {
    TrpMeasuredResultsValue_ExtIEs__value_PR present;
    union TrpMeasuredResultsValue_ExtIEs__value_u {
    } choice;

    /* Context for parsing across buffer boundaries */
    asn_struct_ctx_t _asn_ctx;
  } value;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} TrpMeasuredResultsValue_ExtIEs_t;
typedef struct TrpMeasurementQuality_ExtIEs {
  ProtocolIE_ID_t id;
  Criticality_t criticality;
  struct TrpMeasurementQuality_ExtIEs__value {
    TrpMeasurementQuality_ExtIEs__value_PR present;
    union TrpMeasurementQuality_ExtIEs__value_u {
    } choice;

    /* Context for parsing across buffer boundaries */
    asn_struct_ctx_t _asn_ctx;
  } value;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} TrpMeasurementQuality_ExtIEs_t;
typedef struct TRPInformationItem_ExtIEs {
  ProtocolIE_ID_t id;
  Criticality_t criticality;
  struct TRPInformationItem_ExtIEs__value {
    TRPInformationItem_ExtIEs__value_PR present;
    union TRPInformationItem_ExtIEs__value_u {
    } choice;

    /* Context for parsing across buffer boundaries */
    asn_struct_ctx_t _asn_ctx;
  } value;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} TRPInformationItem_ExtIEs_t;
typedef struct TRPPositionDefinitionType_ExtIEs {
  ProtocolIE_ID_t id;
  Criticality_t criticality;
  struct TRPPositionDefinitionType_ExtIEs__value {
    TRPPositionDefinitionType_ExtIEs__value_PR present;
    union TRPPositionDefinitionType_ExtIEs__value_u {
    } choice;

    /* Context for parsing across buffer boundaries */
    asn_struct_ctx_t _asn_ctx;
  } value;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} TRPPositionDefinitionType_ExtIEs_t;
typedef struct TRPPositionDirectAccuracy_ExtIEs {
  ProtocolIE_ID_t id;
  Criticality_t criticality;
  struct TRPPositionDirectAccuracy_ExtIEs__value {
    TRPPositionDirectAccuracy_ExtIEs__value_PR present;
    union TRPPositionDirectAccuracy_ExtIEs__value_u {
    } choice;

    /* Context for parsing across buffer boundaries */
    asn_struct_ctx_t _asn_ctx;
  } value;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} TRPPositionDirectAccuracy_ExtIEs_t;
typedef struct TRPReferencePointType_ExtIEs {
  ProtocolIE_ID_t id;
  Criticality_t criticality;
  struct TRPReferencePointType_ExtIEs__value {
    TRPReferencePointType_ExtIEs__value_PR present;
    union TRPReferencePointType_ExtIEs__value_u {
    } choice;

    /* Context for parsing across buffer boundaries */
    asn_struct_ctx_t _asn_ctx;
  } value;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} TRPReferencePointType_ExtIEs_t;
typedef struct WLANMeasurementQuantities_ItemIEs {
  ProtocolIE_ID_t id;
  Criticality_t criticality;
  struct WLANMeasurementQuantities_ItemIEs__value {
    WLANMeasurementQuantities_ItemIEs__value_PR present;
    union WLANMeasurementQuantities_ItemIEs__value_u {
      WLANMeasurementQuantities_Item_t WLANMeasurementQuantities_Item;
    } choice;

    /* Context for parsing across buffer boundaries */
    asn_struct_ctx_t _asn_ctx;
  } value;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} WLANMeasurementQuantities_ItemIEs_t;
typedef struct E_CIDMeasurementInitiationRequest_IEs {
  ProtocolIE_ID_t id;
  Criticality_t criticality;
  struct E_CIDMeasurementInitiationRequest_IEs__value {
    E_CIDMeasurementInitiationRequest_IEs__value_PR present;
    union E_CIDMeasurementInitiationRequest_IEs__value_u {
      UE_Measurement_ID_t UE_Measurement_ID;
      ReportCharacteristics_t ReportCharacteristics;
      MeasurementPeriodicity_t MeasurementPeriodicity;
      MeasurementQuantities_t MeasurementQuantities;
      OtherRATMeasurementQuantities_t OtherRATMeasurementQuantities;
      WLANMeasurementQuantities_t WLANMeasurementQuantities;
    } choice;

    /* Context for parsing across buffer boundaries */
    asn_struct_ctx_t _asn_ctx;
  } value;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} E_CIDMeasurementInitiationRequest_IEs_t;
typedef struct E_CIDMeasurementInitiationResponse_IEs {
  ProtocolIE_ID_t id;
  Criticality_t criticality;
  struct E_CIDMeasurementInitiationResponse_IEs__value {
    E_CIDMeasurementInitiationResponse_IEs__value_PR present;
    union E_CIDMeasurementInitiationResponse_IEs__value_u {
      UE_Measurement_ID_t UE_Measurement_ID;
      UE_Measurement_ID_t UE_Measurement_ID_1;
      E_CID_MeasurementResult_t E_CID_MeasurementResult;
      CriticalityDiagnostics_t CriticalityDiagnostics;
      Cell_Portion_ID_t Cell_Portion_ID;
      OtherRATMeasurementResult_t OtherRATMeasurementResult;
      WLANMeasurementResult_t WLANMeasurementResult;
    } choice;

    /* Context for parsing across buffer boundaries */
    asn_struct_ctx_t _asn_ctx;
  } value;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} E_CIDMeasurementInitiationResponse_IEs_t;
typedef struct E_CIDMeasurementInitiationFailure_IEs {
  ProtocolIE_ID_t id;
  Criticality_t criticality;
  struct E_CIDMeasurementInitiationFailure_IEs__value {
    E_CIDMeasurementInitiationFailure_IEs__value_PR present;
    union E_CIDMeasurementInitiationFailure_IEs__value_u {
      UE_Measurement_ID_t UE_Measurement_ID;
      Cause_t Cause;
      CriticalityDiagnostics_t CriticalityDiagnostics;
    } choice;

    /* Context for parsing across buffer boundaries */
    asn_struct_ctx_t _asn_ctx;
  } value;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} E_CIDMeasurementInitiationFailure_IEs_t;
typedef struct E_CIDMeasurementFailureIndication_IEs {
  ProtocolIE_ID_t id;
  Criticality_t criticality;
  struct E_CIDMeasurementFailureIndication_IEs__value {
    E_CIDMeasurementFailureIndication_IEs__value_PR present;
    union E_CIDMeasurementFailureIndication_IEs__value_u {
      UE_Measurement_ID_t UE_Measurement_ID;
      UE_Measurement_ID_t UE_Measurement_ID_1;
      Cause_t Cause;
    } choice;

    /* Context for parsing across buffer boundaries */
    asn_struct_ctx_t _asn_ctx;
  } value;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} E_CIDMeasurementFailureIndication_IEs_t;
typedef struct E_CIDMeasurementReport_IEs {
  ProtocolIE_ID_t id;
  Criticality_t criticality;
  struct E_CIDMeasurementReport_IEs__value {
    E_CIDMeasurementReport_IEs__value_PR present;
    union E_CIDMeasurementReport_IEs__value_u {
      UE_Measurement_ID_t UE_Measurement_ID;
      UE_Measurement_ID_t UE_Measurement_ID_1;
      E_CID_MeasurementResult_t E_CID_MeasurementResult;
      Cell_Portion_ID_t Cell_Portion_ID;
    } choice;

    /* Context for parsing across buffer boundaries */
    asn_struct_ctx_t _asn_ctx;
  } value;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} E_CIDMeasurementReport_IEs_t;
typedef struct E_CIDMeasurementTerminationCommand_IEs {
  ProtocolIE_ID_t id;
  Criticality_t criticality;
  struct E_CIDMeasurementTerminationCommand_IEs__value {
    E_CIDMeasurementTerminationCommand_IEs__value_PR present;
    union E_CIDMeasurementTerminationCommand_IEs__value_u {
      UE_Measurement_ID_t UE_Measurement_ID;
      UE_Measurement_ID_t UE_Measurement_ID_1;
    } choice;

    /* Context for parsing across buffer boundaries */
    asn_struct_ctx_t _asn_ctx;
  } value;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} E_CIDMeasurementTerminationCommand_IEs_t;
typedef struct OTDOAInformationRequest_IEs {
  ProtocolIE_ID_t id;
  Criticality_t criticality;
  struct OTDOAInformationRequest_IEs__value {
    OTDOAInformationRequest_IEs__value_PR present;
    union OTDOAInformationRequest_IEs__value_u {
      OTDOA_Information_Type_t OTDOA_Information_Type;
    } choice;

    /* Context for parsing across buffer boundaries */
    asn_struct_ctx_t _asn_ctx;
  } value;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} OTDOAInformationRequest_IEs_t;
typedef struct OTDOAInformationResponse_IEs {
  ProtocolIE_ID_t id;
  Criticality_t criticality;
  struct OTDOAInformationResponse_IEs__value {
    OTDOAInformationResponse_IEs__value_PR present;
    union OTDOAInformationResponse_IEs__value_u {
      OTDOACells_t OTDOACells;
      CriticalityDiagnostics_t CriticalityDiagnostics;
    } choice;

    /* Context for parsing across buffer boundaries */
    asn_struct_ctx_t _asn_ctx;
  } value;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} OTDOAInformationResponse_IEs_t;
typedef struct OTDOAInformationFailure_IEs {
  ProtocolIE_ID_t id;
  Criticality_t criticality;
  struct OTDOAInformationFailure_IEs__value {
    OTDOAInformationFailure_IEs__value_PR present;
    union OTDOAInformationFailure_IEs__value_u {
      Cause_t Cause;
      CriticalityDiagnostics_t CriticalityDiagnostics;
    } choice;

    /* Context for parsing across buffer boundaries */
    asn_struct_ctx_t _asn_ctx;
  } value;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} OTDOAInformationFailure_IEs_t;
typedef struct AssistanceInformationControl_IEs {
  ProtocolIE_ID_t id;
  Criticality_t criticality;
  struct AssistanceInformationControl_IEs__value {
    AssistanceInformationControl_IEs__value_PR present;
    union AssistanceInformationControl_IEs__value_u {
      Assistance_Information_t Assistance_Information;
      Broadcast_t Broadcast;
      PositioningBroadcastCells_t PositioningBroadcastCells;
    } choice;

    /* Context for parsing across buffer boundaries */
    asn_struct_ctx_t _asn_ctx;
  } value;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} AssistanceInformationControl_IEs_t;
typedef struct AssistanceInformationFeedback_IEs {
  ProtocolIE_ID_t id;
  Criticality_t criticality;
  struct AssistanceInformationFeedback_IEs__value {
    AssistanceInformationFeedback_IEs__value_PR present;
    union AssistanceInformationFeedback_IEs__value_u {
      AssistanceInformationFailureList_t AssistanceInformationFailureList;
      PositioningBroadcastCells_t PositioningBroadcastCells;
      CriticalityDiagnostics_t CriticalityDiagnostics;
    } choice;

    /* Context for parsing across buffer boundaries */
    asn_struct_ctx_t _asn_ctx;
  } value;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} AssistanceInformationFeedback_IEs_t;
typedef struct ErrorIndication_IEs {
  ProtocolIE_ID_t id;
  Criticality_t criticality;
  struct ErrorIndication_IEs__value {
    ErrorIndication_IEs__value_PR present;
    union ErrorIndication_IEs__value_u {
      Cause_t Cause;
      CriticalityDiagnostics_t CriticalityDiagnostics;
    } choice;

    /* Context for parsing across buffer boundaries */
    asn_struct_ctx_t _asn_ctx;
  } value;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} ErrorIndication_IEs_t;
typedef struct PositioningInformationRequest_IEs {
  ProtocolIE_ID_t id;
  Criticality_t criticality;
  struct PositioningInformationRequest_IEs__value {
    PositioningInformationRequest_IEs__value_PR present;
    union PositioningInformationRequest_IEs__value_u {
      RequestedSRSTransmissionCharacteristics_t
          RequestedSRSTransmissionCharacteristics;
    } choice;

    /* Context for parsing across buffer boundaries */
    asn_struct_ctx_t _asn_ctx;
  } value;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} PositioningInformationRequest_IEs_t;
typedef struct PositioningInformationResponse_IEs {
  ProtocolIE_ID_t id;
  Criticality_t criticality;
  struct PositioningInformationResponse_IEs__value {
    PositioningInformationResponse_IEs__value_PR present;
    union PositioningInformationResponse_IEs__value_u {
      SRSConfiguration_t SRSConfiguration;
      SFNInitialisationTime_t SFNInitialisationTime;
      CriticalityDiagnostics_t CriticalityDiagnostics;
    } choice;

    /* Context for parsing across buffer boundaries */
    asn_struct_ctx_t _asn_ctx;
  } value;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} PositioningInformationResponse_IEs_t;
typedef struct PositioningInformationFailure_IEs {
  ProtocolIE_ID_t id;
  Criticality_t criticality;
  struct PositioningInformationFailure_IEs__value {
    PositioningInformationFailure_IEs__value_PR present;
    union PositioningInformationFailure_IEs__value_u {
      Cause_t Cause;
      CriticalityDiagnostics_t CriticalityDiagnostics;
    } choice;

    /* Context for parsing across buffer boundaries */
    asn_struct_ctx_t _asn_ctx;
  } value;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} PositioningInformationFailure_IEs_t;
typedef struct PositioningInformationUpdate_IEs {
  ProtocolIE_ID_t id;
  Criticality_t criticality;
  struct PositioningInformationUpdate_IEs__value {
    PositioningInformationUpdate_IEs__value_PR present;
    union PositioningInformationUpdate_IEs__value_u {
      SRSConfiguration_t SRSConfiguration;
      SFNInitialisationTime_t SFNInitialisationTime;
    } choice;

    /* Context for parsing across buffer boundaries */
    asn_struct_ctx_t _asn_ctx;
  } value;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} PositioningInformationUpdate_IEs_t;
typedef struct MeasurementRequest_IEs {
  ProtocolIE_ID_t id;
  Criticality_t criticality;
  struct MeasurementRequest_IEs__value {
    MeasurementRequest_IEs__value_PR present;
    union MeasurementRequest_IEs__value_u {
      Measurement_ID_t Measurement_ID;
      TRP_MeasurementRequestList_t TRP_MeasurementRequestList;
      ReportCharacteristics_t ReportCharacteristics;
      MeasurementPeriodicity_t MeasurementPeriodicity;
      TRPMeasurementQuantities_t TRPMeasurementQuantities;
      SRSConfiguration_t SRSConfiguration;
      SFNInitialisationTime_t SFNInitialisationTime;
      MeasurementBeamInfoRequest_t MeasurementBeamInfoRequest;
      SystemFrameNumber_t SystemFrameNumber;
      SlotNumber_t SlotNumber;
    } choice;

    /* Context for parsing across buffer boundaries */
    asn_struct_ctx_t _asn_ctx;
  } value;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} MeasurementRequest_IEs_t;
typedef struct MeasurementResponse_IEs {
  ProtocolIE_ID_t id;
  Criticality_t criticality;
  struct MeasurementResponse_IEs__value {
    MeasurementResponse_IEs__value_PR present;
    union MeasurementResponse_IEs__value_u {
      Measurement_ID_t Measurement_ID;
      Measurement_ID_t Measurement_ID_1;
      TRP_MeasurementResponseList_t TRP_MeasurementResponseList;
      CriticalityDiagnostics_t CriticalityDiagnostics;
    } choice;

    /* Context for parsing across buffer boundaries */
    asn_struct_ctx_t _asn_ctx;
  } value;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} MeasurementResponse_IEs_t;
typedef struct MeasurementFailure_IEs {
  ProtocolIE_ID_t id;
  Criticality_t criticality;
  struct MeasurementFailure_IEs__value {
    MeasurementFailure_IEs__value_PR present;
    union MeasurementFailure_IEs__value_u {
      Measurement_ID_t Measurement_ID;
      Cause_t Cause;
      CriticalityDiagnostics_t CriticalityDiagnostics;
    } choice;

    /* Context for parsing across buffer boundaries */
    asn_struct_ctx_t _asn_ctx;
  } value;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} MeasurementFailure_IEs_t;
typedef struct MeasurementReport_IEs {
  ProtocolIE_ID_t id;
  Criticality_t criticality;
  struct MeasurementReport_IEs__value {
    MeasurementReport_IEs__value_PR present;
    union MeasurementReport_IEs__value_u {
      Measurement_ID_t Measurement_ID;
      Measurement_ID_t Measurement_ID_1;
      TRP_MeasurementResponseList_t TRP_MeasurementResponseList;
    } choice;

    /* Context for parsing across buffer boundaries */
    asn_struct_ctx_t _asn_ctx;
  } value;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} MeasurementReport_IEs_t;
typedef struct MeasurementUpdate_IEs {
  ProtocolIE_ID_t id;
  Criticality_t criticality;
  struct MeasurementUpdate_IEs__value {
    MeasurementUpdate_IEs__value_PR present;
    union MeasurementUpdate_IEs__value_u {
      Measurement_ID_t Measurement_ID;
      Measurement_ID_t Measurement_ID_1;
      SRSConfiguration_t SRSConfiguration;
    } choice;

    /* Context for parsing across buffer boundaries */
    asn_struct_ctx_t _asn_ctx;
  } value;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} MeasurementUpdate_IEs_t;
typedef struct MeasurementAbort_IEs {
  ProtocolIE_ID_t id;
  Criticality_t criticality;
  struct MeasurementAbort_IEs__value {
    MeasurementAbort_IEs__value_PR present;
    union MeasurementAbort_IEs__value_u {
      Measurement_ID_t Measurement_ID;
      Measurement_ID_t Measurement_ID_1;
    } choice;

    /* Context for parsing across buffer boundaries */
    asn_struct_ctx_t _asn_ctx;
  } value;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} MeasurementAbort_IEs_t;
typedef struct MeasurementFailureIndication_IEs {
  ProtocolIE_ID_t id;
  Criticality_t criticality;
  struct MeasurementFailureIndication_IEs__value {
    MeasurementFailureIndication_IEs__value_PR present;
    union MeasurementFailureIndication_IEs__value_u {
      Measurement_ID_t Measurement_ID;
      Measurement_ID_t Measurement_ID_1;
      Cause_t Cause;
    } choice;

    /* Context for parsing across buffer boundaries */
    asn_struct_ctx_t _asn_ctx;
  } value;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} MeasurementFailureIndication_IEs_t;
typedef struct TRPInformationRequest_IEs {
  ProtocolIE_ID_t id;
  Criticality_t criticality;
  struct TRPInformationRequest_IEs__value {
    TRPInformationRequest_IEs__value_PR present;
    union TRPInformationRequest_IEs__value_u {
      TRPList_t TRPList;
      TRPInformationTypeList_t TRPInformationTypeList;
    } choice;

    /* Context for parsing across buffer boundaries */
    asn_struct_ctx_t _asn_ctx;
  } value;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} TRPInformationRequest_IEs_t;
typedef struct TRPInformationResponse_IEs {
  ProtocolIE_ID_t id;
  Criticality_t criticality;
  struct TRPInformationResponse_IEs__value {
    TRPInformationResponse_IEs__value_PR present;
    union TRPInformationResponse_IEs__value_u {
      TRPInformationList_t TRPInformationList;
      CriticalityDiagnostics_t CriticalityDiagnostics;
    } choice;

    /* Context for parsing across buffer boundaries */
    asn_struct_ctx_t _asn_ctx;
  } value;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} TRPInformationResponse_IEs_t;
typedef struct TRPInformationFailure_IEs {
  ProtocolIE_ID_t id;
  Criticality_t criticality;
  struct TRPInformationFailure_IEs__value {
    TRPInformationFailure_IEs__value_PR present;
    union TRPInformationFailure_IEs__value_u {
      Cause_t Cause;
      CriticalityDiagnostics_t CriticalityDiagnostics;
    } choice;

    /* Context for parsing across buffer boundaries */
    asn_struct_ctx_t _asn_ctx;
  } value;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} TRPInformationFailure_IEs_t;
typedef struct PositioningActivationRequestIEs {
  ProtocolIE_ID_t id;
  Criticality_t criticality;
  struct PositioningActivationRequestIEs__value {
    PositioningActivationRequestIEs__value_PR present;
    union PositioningActivationRequestIEs__value_u {
      SRSType_t SRSType;
      ActivationTime_t ActivationTime;
    } choice;

    /* Context for parsing across buffer boundaries */
    asn_struct_ctx_t _asn_ctx;
  } value;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} PositioningActivationRequestIEs_t;
typedef struct PositioningActivationResponseIEs {
  ProtocolIE_ID_t id;
  Criticality_t criticality;
  struct PositioningActivationResponseIEs__value {
    PositioningActivationResponseIEs__value_PR present;
    union PositioningActivationResponseIEs__value_u {
      CriticalityDiagnostics_t CriticalityDiagnostics;
      SystemFrameNumber_t SystemFrameNumber;
      SlotNumber_t SlotNumber;
    } choice;

    /* Context for parsing across buffer boundaries */
    asn_struct_ctx_t _asn_ctx;
  } value;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} PositioningActivationResponseIEs_t;
typedef struct PositioningActivationFailureIEs {
  ProtocolIE_ID_t id;
  Criticality_t criticality;
  struct PositioningActivationFailureIEs__value {
    PositioningActivationFailureIEs__value_PR present;
    union PositioningActivationFailureIEs__value_u {
      Cause_t Cause;
      CriticalityDiagnostics_t CriticalityDiagnostics;
    } choice;

    /* Context for parsing across buffer boundaries */
    asn_struct_ctx_t _asn_ctx;
  } value;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} PositioningActivationFailureIEs_t;
typedef struct PositioningDeactivationIEs {
  ProtocolIE_ID_t id;
  Criticality_t criticality;
  struct PositioningDeactivationIEs__value {
    PositioningDeactivationIEs__value_PR present;
    union PositioningDeactivationIEs__value_u {
      AbortTransmission_t AbortTransmission;
    } choice;

    /* Context for parsing across buffer boundaries */
    asn_struct_ctx_t _asn_ctx;
  } value;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} PositioningDeactivationIEs_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_OTDOA_Information_TypeIEs;
extern asn_SEQUENCE_specifics_t asn_SPC_OTDOA_Information_TypeIEs_specs_1;
extern asn_TYPE_member_t asn_MBR_OTDOA_Information_TypeIEs_1[3];
extern asn_TYPE_descriptor_t asn_DEF_SRSType_ExtIEs;
extern asn_SEQUENCE_specifics_t asn_SPC_SRSType_ExtIEs_specs_5;
extern asn_TYPE_member_t asn_MBR_SRSType_ExtIEs_5[3];
extern asn_TYPE_descriptor_t asn_DEF_AbortTransmission_ExtIEs;
extern asn_SEQUENCE_specifics_t asn_SPC_AbortTransmission_ExtIEs_specs_9;
extern asn_TYPE_member_t asn_MBR_AbortTransmission_ExtIEs_9[3];
extern asn_TYPE_descriptor_t asn_DEF_Cause_ExtensionIE;
extern asn_SEQUENCE_specifics_t asn_SPC_Cause_ExtensionIE_specs_13;
extern asn_TYPE_member_t asn_MBR_Cause_ExtensionIE_13[3];
extern asn_TYPE_descriptor_t asn_DEF_DL_PRSMutingPattern_ExtIEs;
extern asn_SEQUENCE_specifics_t asn_SPC_DL_PRSMutingPattern_ExtIEs_specs_17;
extern asn_TYPE_member_t asn_MBR_DL_PRSMutingPattern_ExtIEs_17[3];
extern asn_TYPE_descriptor_t asn_DEF_DL_PRSResourceSetARPLocation_ExtIEs;
extern asn_SEQUENCE_specifics_t
    asn_SPC_DL_PRSResourceSetARPLocation_ExtIEs_specs_21;
extern asn_TYPE_member_t asn_MBR_DL_PRSResourceSetARPLocation_ExtIEs_21[3];
extern asn_TYPE_descriptor_t asn_DEF_DL_PRSResourceARPLocation_ExtIEs;
extern asn_SEQUENCE_specifics_t
    asn_SPC_DL_PRSResourceARPLocation_ExtIEs_specs_25;
extern asn_TYPE_member_t asn_MBR_DL_PRSResourceARPLocation_ExtIEs_25[3];
extern asn_TYPE_descriptor_t asn_DEF_GNBRxTxTimeDiffMeas_ExtIEs;
extern asn_SEQUENCE_specifics_t asn_SPC_GNBRxTxTimeDiffMeas_ExtIEs_specs_29;
extern asn_TYPE_member_t asn_MBR_GNBRxTxTimeDiffMeas_ExtIEs_29[3];
extern asn_TYPE_descriptor_t asn_DEF_MeasurementQuantities_ItemIEs;
extern asn_SEQUENCE_specifics_t asn_SPC_MeasurementQuantities_ItemIEs_specs_33;
extern asn_TYPE_member_t asn_MBR_MeasurementQuantities_ItemIEs_33[3];
extern asn_TYPE_descriptor_t asn_DEF_MeasuredResultsValue_ExtensionIE;
extern asn_SEQUENCE_specifics_t
    asn_SPC_MeasuredResultsValue_ExtensionIE_specs_37;
extern asn_TYPE_member_t asn_MBR_MeasuredResultsValue_ExtensionIE_37[3];
extern asn_TYPE_descriptor_t asn_DEF_NG_RANCell_ExtensionIE;
extern asn_SEQUENCE_specifics_t asn_SPC_NG_RANCell_ExtensionIE_specs_41;
extern asn_TYPE_member_t asn_MBR_NG_RANCell_ExtensionIE_41[3];
extern asn_TYPE_descriptor_t asn_DEF_OTDOACell_Information_Item_ExtensionIE;
extern asn_SEQUENCE_specifics_t
    asn_SPC_OTDOACell_Information_Item_ExtensionIE_specs_45;
extern asn_TYPE_member_t asn_MBR_OTDOACell_Information_Item_ExtensionIE_45[3];
extern asn_TYPE_descriptor_t asn_DEF_OtherRATMeasurementQuantities_ItemIEs;
extern asn_SEQUENCE_specifics_t
    asn_SPC_OtherRATMeasurementQuantities_ItemIEs_specs_49;
extern asn_TYPE_member_t asn_MBR_OtherRATMeasurementQuantities_ItemIEs_49[3];
extern asn_TYPE_descriptor_t asn_DEF_OtherRATMeasuredResultsValue_ExtensionIE;
extern asn_SEQUENCE_specifics_t
    asn_SPC_OtherRATMeasuredResultsValue_ExtensionIE_specs_53;
extern asn_TYPE_member_t asn_MBR_OtherRATMeasuredResultsValue_ExtensionIE_53[3];
extern asn_TYPE_descriptor_t asn_DEF_PathlossReferenceSignal_ExtensionIE;
extern asn_SEQUENCE_specifics_t
    asn_SPC_PathlossReferenceSignal_ExtensionIE_specs_57;
extern asn_TYPE_member_t asn_MBR_PathlossReferenceSignal_ExtensionIE_57[3];
extern asn_TYPE_descriptor_t asn_DEF_PosResourceSetType_ExtIEs;
extern asn_SEQUENCE_specifics_t asn_SPC_PosResourceSetType_ExtIEs_specs_61;
extern asn_TYPE_member_t asn_MBR_PosResourceSetType_ExtIEs_61[3];
extern asn_TYPE_descriptor_t asn_DEF_PRSMutingConfiguration_EUTRA_ExtensionIE;
extern asn_SEQUENCE_specifics_t
    asn_SPC_PRSMutingConfiguration_EUTRA_ExtensionIE_specs_65;
extern asn_TYPE_member_t asn_MBR_PRSMutingConfiguration_EUTRA_ExtensionIE_65[3];
extern asn_TYPE_descriptor_t asn_DEF_ReferenceSignal_ExtensionIE;
extern asn_SEQUENCE_specifics_t asn_SPC_ReferenceSignal_ExtensionIE_specs_69;
extern asn_TYPE_member_t asn_MBR_ReferenceSignal_ExtensionIE_69[3];
extern asn_TYPE_descriptor_t asn_DEF_ReferencePoint_ExtIEs;
extern asn_SEQUENCE_specifics_t asn_SPC_ReferencePoint_ExtIEs_specs_73;
extern asn_TYPE_member_t asn_MBR_ReferencePoint_ExtIEs_73[3];
extern asn_TYPE_descriptor_t asn_DEF_ResourceSetType_ExtIEs;
extern asn_SEQUENCE_specifics_t asn_SPC_ResourceSetType_ExtIEs_specs_77;
extern asn_TYPE_member_t asn_MBR_ResourceSetType_ExtIEs_77[3];
extern asn_TYPE_descriptor_t asn_DEF_ResourceType_ExtIEs;
extern asn_SEQUENCE_specifics_t asn_SPC_ResourceType_ExtIEs_specs_81;
extern asn_TYPE_member_t asn_MBR_ResourceType_ExtIEs_81[3];
extern asn_TYPE_descriptor_t asn_DEF_ResourceTypePos_ExtIEs;
extern asn_SEQUENCE_specifics_t asn_SPC_ResourceTypePos_ExtIEs_specs_85;
extern asn_TYPE_member_t asn_MBR_ResourceTypePos_ExtIEs_85[3];
extern asn_TYPE_descriptor_t asn_DEF_SpatialInformationPos_ExtIEs;
extern asn_SEQUENCE_specifics_t asn_SPC_SpatialInformationPos_ExtIEs_specs_89;
extern asn_TYPE_member_t asn_MBR_SpatialInformationPos_ExtIEs_89[3];
extern asn_TYPE_descriptor_t asn_DEF_TimeStampSlotIndex_ExtIEs;
extern asn_SEQUENCE_specifics_t asn_SPC_TimeStampSlotIndex_ExtIEs_specs_93;
extern asn_TYPE_member_t asn_MBR_TimeStampSlotIndex_ExtIEs_93[3];
extern asn_TYPE_descriptor_t asn_DEF_TransmissionComb_ExtIEs;
extern asn_SEQUENCE_specifics_t asn_SPC_TransmissionComb_ExtIEs_specs_97;
extern asn_TYPE_member_t asn_MBR_TransmissionComb_ExtIEs_97[3];
extern asn_TYPE_descriptor_t asn_DEF_TransmissionCombPos_ExtIEs;
extern asn_SEQUENCE_specifics_t asn_SPC_TransmissionCombPos_ExtIEs_specs_101;
extern asn_TYPE_member_t asn_MBR_TransmissionCombPos_ExtIEs_101[3];
extern asn_TYPE_descriptor_t asn_DEF_TrpMeasuredResultsValue_ExtIEs;
extern asn_SEQUENCE_specifics_t
    asn_SPC_TrpMeasuredResultsValue_ExtIEs_specs_105;
extern asn_TYPE_member_t asn_MBR_TrpMeasuredResultsValue_ExtIEs_105[3];
extern asn_TYPE_descriptor_t asn_DEF_TrpMeasurementQuality_ExtIEs;
extern asn_SEQUENCE_specifics_t asn_SPC_TrpMeasurementQuality_ExtIEs_specs_109;
extern asn_TYPE_member_t asn_MBR_TrpMeasurementQuality_ExtIEs_109[3];
extern asn_TYPE_descriptor_t asn_DEF_TRPInformationItem_ExtIEs;
extern asn_SEQUENCE_specifics_t asn_SPC_TRPInformationItem_ExtIEs_specs_113;
extern asn_TYPE_member_t asn_MBR_TRPInformationItem_ExtIEs_113[3];
extern asn_TYPE_descriptor_t asn_DEF_TRPPositionDefinitionType_ExtIEs;
extern asn_SEQUENCE_specifics_t
    asn_SPC_TRPPositionDefinitionType_ExtIEs_specs_117;
extern asn_TYPE_member_t asn_MBR_TRPPositionDefinitionType_ExtIEs_117[3];
extern asn_TYPE_descriptor_t asn_DEF_TRPPositionDirectAccuracy_ExtIEs;
extern asn_SEQUENCE_specifics_t
    asn_SPC_TRPPositionDirectAccuracy_ExtIEs_specs_121;
extern asn_TYPE_member_t asn_MBR_TRPPositionDirectAccuracy_ExtIEs_121[3];
extern asn_TYPE_descriptor_t asn_DEF_TRPReferencePointType_ExtIEs;
extern asn_SEQUENCE_specifics_t asn_SPC_TRPReferencePointType_ExtIEs_specs_125;
extern asn_TYPE_member_t asn_MBR_TRPReferencePointType_ExtIEs_125[3];
extern asn_TYPE_descriptor_t asn_DEF_WLANMeasurementQuantities_ItemIEs;
extern asn_SEQUENCE_specifics_t
    asn_SPC_WLANMeasurementQuantities_ItemIEs_specs_129;
extern asn_TYPE_member_t asn_MBR_WLANMeasurementQuantities_ItemIEs_129[3];
extern asn_TYPE_descriptor_t asn_DEF_E_CIDMeasurementInitiationRequest_IEs;
extern asn_SEQUENCE_specifics_t
    asn_SPC_E_CIDMeasurementInitiationRequest_IEs_specs_133;
extern asn_TYPE_member_t asn_MBR_E_CIDMeasurementInitiationRequest_IEs_133[3];
extern asn_TYPE_descriptor_t asn_DEF_E_CIDMeasurementInitiationResponse_IEs;
extern asn_SEQUENCE_specifics_t
    asn_SPC_E_CIDMeasurementInitiationResponse_IEs_specs_137;
extern asn_TYPE_member_t asn_MBR_E_CIDMeasurementInitiationResponse_IEs_137[3];
extern asn_TYPE_descriptor_t asn_DEF_E_CIDMeasurementInitiationFailure_IEs;
extern asn_SEQUENCE_specifics_t
    asn_SPC_E_CIDMeasurementInitiationFailure_IEs_specs_141;
extern asn_TYPE_member_t asn_MBR_E_CIDMeasurementInitiationFailure_IEs_141[3];
extern asn_TYPE_descriptor_t asn_DEF_E_CIDMeasurementFailureIndication_IEs;
extern asn_SEQUENCE_specifics_t
    asn_SPC_E_CIDMeasurementFailureIndication_IEs_specs_145;
extern asn_TYPE_member_t asn_MBR_E_CIDMeasurementFailureIndication_IEs_145[3];
extern asn_TYPE_descriptor_t asn_DEF_E_CIDMeasurementReport_IEs;
extern asn_SEQUENCE_specifics_t asn_SPC_E_CIDMeasurementReport_IEs_specs_149;
extern asn_TYPE_member_t asn_MBR_E_CIDMeasurementReport_IEs_149[3];
extern asn_TYPE_descriptor_t asn_DEF_E_CIDMeasurementTerminationCommand_IEs;
extern asn_SEQUENCE_specifics_t
    asn_SPC_E_CIDMeasurementTerminationCommand_IEs_specs_153;
extern asn_TYPE_member_t asn_MBR_E_CIDMeasurementTerminationCommand_IEs_153[3];
extern asn_TYPE_descriptor_t asn_DEF_OTDOAInformationRequest_IEs;
extern asn_SEQUENCE_specifics_t asn_SPC_OTDOAInformationRequest_IEs_specs_157;
extern asn_TYPE_member_t asn_MBR_OTDOAInformationRequest_IEs_157[3];
extern asn_TYPE_descriptor_t asn_DEF_OTDOAInformationResponse_IEs;
extern asn_SEQUENCE_specifics_t asn_SPC_OTDOAInformationResponse_IEs_specs_161;
extern asn_TYPE_member_t asn_MBR_OTDOAInformationResponse_IEs_161[3];
extern asn_TYPE_descriptor_t asn_DEF_OTDOAInformationFailure_IEs;
extern asn_SEQUENCE_specifics_t asn_SPC_OTDOAInformationFailure_IEs_specs_165;
extern asn_TYPE_member_t asn_MBR_OTDOAInformationFailure_IEs_165[3];
extern asn_TYPE_descriptor_t asn_DEF_AssistanceInformationControl_IEs;
extern asn_SEQUENCE_specifics_t
    asn_SPC_AssistanceInformationControl_IEs_specs_169;
extern asn_TYPE_member_t asn_MBR_AssistanceInformationControl_IEs_169[3];
extern asn_TYPE_descriptor_t asn_DEF_AssistanceInformationFeedback_IEs;
extern asn_SEQUENCE_specifics_t
    asn_SPC_AssistanceInformationFeedback_IEs_specs_173;
extern asn_TYPE_member_t asn_MBR_AssistanceInformationFeedback_IEs_173[3];
extern asn_TYPE_descriptor_t asn_DEF_ErrorIndication_IEs;
extern asn_SEQUENCE_specifics_t asn_SPC_ErrorIndication_IEs_specs_177;
extern asn_TYPE_member_t asn_MBR_ErrorIndication_IEs_177[3];
extern asn_TYPE_descriptor_t asn_DEF_PositioningInformationRequest_IEs;
extern asn_SEQUENCE_specifics_t
    asn_SPC_PositioningInformationRequest_IEs_specs_181;
extern asn_TYPE_member_t asn_MBR_PositioningInformationRequest_IEs_181[3];
extern asn_TYPE_descriptor_t asn_DEF_PositioningInformationResponse_IEs;
extern asn_SEQUENCE_specifics_t
    asn_SPC_PositioningInformationResponse_IEs_specs_185;
extern asn_TYPE_member_t asn_MBR_PositioningInformationResponse_IEs_185[3];
extern asn_TYPE_descriptor_t asn_DEF_PositioningInformationFailure_IEs;
extern asn_SEQUENCE_specifics_t
    asn_SPC_PositioningInformationFailure_IEs_specs_189;
extern asn_TYPE_member_t asn_MBR_PositioningInformationFailure_IEs_189[3];
extern asn_TYPE_descriptor_t asn_DEF_PositioningInformationUpdate_IEs;
extern asn_SEQUENCE_specifics_t
    asn_SPC_PositioningInformationUpdate_IEs_specs_193;
extern asn_TYPE_member_t asn_MBR_PositioningInformationUpdate_IEs_193[3];
extern asn_TYPE_descriptor_t asn_DEF_MeasurementRequest_IEs;
extern asn_SEQUENCE_specifics_t asn_SPC_MeasurementRequest_IEs_specs_197;
extern asn_TYPE_member_t asn_MBR_MeasurementRequest_IEs_197[3];
extern asn_TYPE_descriptor_t asn_DEF_MeasurementResponse_IEs;
extern asn_SEQUENCE_specifics_t asn_SPC_MeasurementResponse_IEs_specs_201;
extern asn_TYPE_member_t asn_MBR_MeasurementResponse_IEs_201[3];
extern asn_TYPE_descriptor_t asn_DEF_MeasurementFailure_IEs;
extern asn_SEQUENCE_specifics_t asn_SPC_MeasurementFailure_IEs_specs_205;
extern asn_TYPE_member_t asn_MBR_MeasurementFailure_IEs_205[3];
extern asn_TYPE_descriptor_t asn_DEF_MeasurementReport_IEs;
extern asn_SEQUENCE_specifics_t asn_SPC_MeasurementReport_IEs_specs_209;
extern asn_TYPE_member_t asn_MBR_MeasurementReport_IEs_209[3];
extern asn_TYPE_descriptor_t asn_DEF_MeasurementUpdate_IEs;
extern asn_SEQUENCE_specifics_t asn_SPC_MeasurementUpdate_IEs_specs_213;
extern asn_TYPE_member_t asn_MBR_MeasurementUpdate_IEs_213[3];
extern asn_TYPE_descriptor_t asn_DEF_MeasurementAbort_IEs;
extern asn_SEQUENCE_specifics_t asn_SPC_MeasurementAbort_IEs_specs_217;
extern asn_TYPE_member_t asn_MBR_MeasurementAbort_IEs_217[3];
extern asn_TYPE_descriptor_t asn_DEF_MeasurementFailureIndication_IEs;
extern asn_SEQUENCE_specifics_t
    asn_SPC_MeasurementFailureIndication_IEs_specs_221;
extern asn_TYPE_member_t asn_MBR_MeasurementFailureIndication_IEs_221[3];
extern asn_TYPE_descriptor_t asn_DEF_TRPInformationRequest_IEs;
extern asn_SEQUENCE_specifics_t asn_SPC_TRPInformationRequest_IEs_specs_225;
extern asn_TYPE_member_t asn_MBR_TRPInformationRequest_IEs_225[3];
extern asn_TYPE_descriptor_t asn_DEF_TRPInformationResponse_IEs;
extern asn_SEQUENCE_specifics_t asn_SPC_TRPInformationResponse_IEs_specs_229;
extern asn_TYPE_member_t asn_MBR_TRPInformationResponse_IEs_229[3];
extern asn_TYPE_descriptor_t asn_DEF_TRPInformationFailure_IEs;
extern asn_SEQUENCE_specifics_t asn_SPC_TRPInformationFailure_IEs_specs_233;
extern asn_TYPE_member_t asn_MBR_TRPInformationFailure_IEs_233[3];
extern asn_TYPE_descriptor_t asn_DEF_PositioningActivationRequestIEs;
extern asn_SEQUENCE_specifics_t
    asn_SPC_PositioningActivationRequestIEs_specs_237;
extern asn_TYPE_member_t asn_MBR_PositioningActivationRequestIEs_237[3];
extern asn_TYPE_descriptor_t asn_DEF_PositioningActivationResponseIEs;
extern asn_SEQUENCE_specifics_t
    asn_SPC_PositioningActivationResponseIEs_specs_241;
extern asn_TYPE_member_t asn_MBR_PositioningActivationResponseIEs_241[3];
extern asn_TYPE_descriptor_t asn_DEF_PositioningActivationFailureIEs;
extern asn_SEQUENCE_specifics_t
    asn_SPC_PositioningActivationFailureIEs_specs_245;
extern asn_TYPE_member_t asn_MBR_PositioningActivationFailureIEs_245[3];
extern asn_TYPE_descriptor_t asn_DEF_PositioningDeactivationIEs;
extern asn_SEQUENCE_specifics_t asn_SPC_PositioningDeactivationIEs_specs_249;
extern asn_TYPE_member_t asn_MBR_PositioningDeactivationIEs_249[3];

#ifdef __cplusplus
}
#endif

#endif /* _ProtocolIE_Field_H_ */
#include <asn_internal.h>
