/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NRPPA-Containers"
 * 	found in "e2ap-v01.01.asn1"
 * 	`asn1c -gen-PER -fcompound-names -findirect-choice -fno-include-deps`
 */

#include "ProtocolIE-Single-Container.h"

/*
 * This type is implemented using ProtocolIE_Field_2909P0,
 * so here we adjust the DEF accordingly.
 */
static const ber_tlv_tag_t asn_DEF_ProtocolIE_Single_Container_2907P0_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Single_Container_2907P0 = {
	"ProtocolIE-Single-Container",
	"ProtocolIE-Single-Container",
	&asn_OP_SEQUENCE,
	asn_DEF_ProtocolIE_Single_Container_2907P0_tags_1,
	sizeof(asn_DEF_ProtocolIE_Single_Container_2907P0_tags_1)
		/sizeof(asn_DEF_ProtocolIE_Single_Container_2907P0_tags_1[0]), /* 1 */
	asn_DEF_ProtocolIE_Single_Container_2907P0_tags_1,	/* Same as above */
	sizeof(asn_DEF_ProtocolIE_Single_Container_2907P0_tags_1)
		/sizeof(asn_DEF_ProtocolIE_Single_Container_2907P0_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_ProtocolIE_Field_2909P0_1,
	3,	/* Elements count */
	&asn_SPC_ProtocolIE_Field_2909P0_specs_1	/* Additional specs */
};

