/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NRPPA-IEs"
 * 	found in "e2ap-v01.01.asn1"
 * 	`asn1c -gen-PER -fcompound-names -findirect-choice -fno-include-deps`
 */

#ifndef	_ResultCSI_RSRP_H_
#define	_ResultCSI_RSRP_H_


#include <asn_application.h>

/* Including external dependencies */
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct ResultCSI_RSRP_Item;

/* ResultCSI-RSRP */
typedef struct ResultCSI_RSRP {
	A_SEQUENCE_OF(struct ResultCSI_RSRP_Item) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ResultCSI_RSRP_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ResultCSI_RSRP;

#ifdef __cplusplus
}
#endif

#endif	/* _ResultCSI_RSRP_H_ */
#include <asn_internal.h>
