/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NRPPA-IEs"
 * 	found in "38455.asn"
 * 	`asn1c -no-gen-OER -fcompound-names -no-gen-example -findirect-choice
 * -fno-include-deps -D nrppa`
 */

#ifndef _SpatialRelationInfo_H_
#define _SpatialRelationInfo_H_

#include <asn_application.h>

/* Including external dependencies */
#include "SpatialRelationforResourceID.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct ProtocolExtensionContainer;

/* SpatialRelationInfo */
typedef struct SpatialRelationInfo {
  SpatialRelationforResourceID_t spatialRelationforResourceID;
  struct ProtocolExtensionContainer* iE_Extensions; /* OPTIONAL */
  /*
   * This type is extensible,
   * possible extensions are below.
   */

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} SpatialRelationInfo_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SpatialRelationInfo;
extern asn_SEQUENCE_specifics_t asn_SPC_SpatialRelationInfo_specs_1;
extern asn_TYPE_member_t asn_MBR_SpatialRelationInfo_1[2];

#ifdef __cplusplus
}
#endif

#endif /* _SpatialRelationInfo_H_ */
#include <asn_internal.h>
