/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NRPPA-IEs"
 * 	found in "38455.asn"
 * 	`asn1c -no-gen-OER -fcompound-names -no-gen-example -findirect-choice
 * -fno-include-deps -D nrppa`
 */

#ifndef _TP_Type_EUTRA_H_
#define _TP_Type_EUTRA_H_

#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum TP_Type_EUTRA {
  TP_Type_EUTRA_prs_only_tp = 0
  /*
   * Enumeration is extensible
   */
} e_TP_Type_EUTRA;

/* TP-Type-EUTRA */
typedef long TP_Type_EUTRA_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_TP_Type_EUTRA_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_TP_Type_EUTRA;
extern const asn_INTEGER_specifics_t asn_SPC_TP_Type_EUTRA_specs_1;
asn_struct_free_f TP_Type_EUTRA_free;
asn_struct_print_f TP_Type_EUTRA_print;
asn_constr_check_f TP_Type_EUTRA_constraint;
ber_type_decoder_f TP_Type_EUTRA_decode_ber;
der_type_encoder_f TP_Type_EUTRA_encode_der;
xer_type_decoder_f TP_Type_EUTRA_decode_xer;
xer_type_encoder_f TP_Type_EUTRA_encode_xer;
per_type_decoder_f TP_Type_EUTRA_decode_uper;
per_type_encoder_f TP_Type_EUTRA_encode_uper;
per_type_decoder_f TP_Type_EUTRA_decode_aper;
per_type_encoder_f TP_Type_EUTRA_encode_aper;

#ifdef __cplusplus
}
#endif

#endif /* _TP_Type_EUTRA_H_ */
#include <asn_internal.h>
