/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NRPPA-IEs"
 * 	found in "38455.asn"
 * 	`asn1c -no-gen-OER -fcompound-names -no-gen-example -findirect-choice
 * -fno-include-deps -D nrppa`
 */

#ifndef _TRPInformationList_H_
#define _TRPInformationList_H_

#include <asn_application.h>

/* Including external dependencies */
#include <asn_SEQUENCE_OF.h>
#include "TRP-ID.h"
#include "TRPInformation.h"
#include <constr_SEQUENCE.h>
#include <constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct ProtocolExtensionContainer;

/* Forward definitions */
typedef struct TRPInformationList__Member {
  TRP_ID_t tRP_ID;
  TRPInformation_t tRPInformation;
  struct ProtocolExtensionContainer* iE_Extensions; /* OPTIONAL */
  /*
   * This type is extensible,
   * possible extensions are below.
   */

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} TRPInformationList__Member;

/* TRPInformationList */
typedef struct TRPInformationList {
  A_SEQUENCE_OF(TRPInformationList__Member) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} TRPInformationList_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_TRPInformationList;
extern asn_SET_OF_specifics_t asn_SPC_TRPInformationList_specs_1;
extern asn_TYPE_member_t asn_MBR_TRPInformationList_1[1];
extern asn_per_constraints_t asn_PER_type_TRPInformationList_constr_1;

#ifdef __cplusplus
}
#endif

#endif /* _TRPInformationList_H_ */
#include <asn_internal.h>
