/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NRPPA-IEs"
 * 	found in "38455.asn"
 * 	`asn1c -no-gen-OER -fcompound-names -no-gen-example -findirect-choice
 * -fno-include-deps -D nrppa`
 */

#ifndef _TRPMeasurementQuantities_Item_H_
#define _TRPMeasurementQuantities_Item_H_

#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum TRPMeasurementQuantities_Item {
  TRPMeasurementQuantities_Item_gNB_RxTxTimeDiff = 0,
  TRPMeasurementQuantities_Item_uL_SRS_RSRP      = 1,
  TRPMeasurementQuantities_Item_uL_AoA           = 2,
  TRPMeasurementQuantities_Item_uL_RTOA          = 3
  /*
   * Enumeration is extensible
   */
} e_TRPMeasurementQuantities_Item;

/* TRPMeasurementQuantities-Item */
typedef long TRPMeasurementQuantities_Item_t;

/* Implementation */
extern asn_per_constraints_t
    asn_PER_type_TRPMeasurementQuantities_Item_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_TRPMeasurementQuantities_Item;
extern const asn_INTEGER_specifics_t
    asn_SPC_TRPMeasurementQuantities_Item_specs_1;
asn_struct_free_f TRPMeasurementQuantities_Item_free;
asn_struct_print_f TRPMeasurementQuantities_Item_print;
asn_constr_check_f TRPMeasurementQuantities_Item_constraint;
ber_type_decoder_f TRPMeasurementQuantities_Item_decode_ber;
der_type_encoder_f TRPMeasurementQuantities_Item_encode_der;
xer_type_decoder_f TRPMeasurementQuantities_Item_decode_xer;
xer_type_encoder_f TRPMeasurementQuantities_Item_encode_xer;
per_type_decoder_f TRPMeasurementQuantities_Item_decode_uper;
per_type_encoder_f TRPMeasurementQuantities_Item_encode_uper;
per_type_decoder_f TRPMeasurementQuantities_Item_decode_aper;
per_type_encoder_f TRPMeasurementQuantities_Item_encode_aper;

#ifdef __cplusplus
}
#endif

#endif /* _TRPMeasurementQuantities_Item_H_ */
#include <asn_internal.h>
