/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NRPPA-IEs"
 * 	found in "38455.asn"
 * 	`asn1c -no-gen-OER -fcompound-names -no-gen-example -findirect-choice
 * -fno-include-deps -D nrppa`
 */

#include "TRPPositionDirect.h"

#include "ProtocolExtensionContainer.h"
asn_TYPE_member_t asn_MBR_TRPPositionDirect_1[] = {
    {ATF_NOFLAGS,
     0,
     offsetof(struct TRPPositionDirect, accuracy),
     (ASN_TAG_CLASS_CONTEXT | (0 << 2)),
     +1, /* EXPLICIT tag at current level */
     &asn_DEF_TRPPositionDirectAccuracy,
     0,
     {0, 0, 0},
     0,
     0, /* No default value */
     "accuracy"},
    {ATF_POINTER,
     1,
     offsetof(struct TRPPositionDirect, iE_extensions),
     (ASN_TAG_CLASS_CONTEXT | (1 << 2)),
     -1, /* IMPLICIT tag at current level */
     &asn_DEF_ProtocolExtensionContainer_2816P97,
     0,
     {0, 0, 0},
     0,
     0, /* No default value */
     "iE-extensions"},
};
static const int asn_MAP_TRPPositionDirect_oms_1[]            = {1};
static const ber_tlv_tag_t asn_DEF_TRPPositionDirect_tags_1[] = {
    (ASN_TAG_CLASS_UNIVERSAL | (16 << 2))};
static const asn_TYPE_tag2member_t asn_MAP_TRPPositionDirect_tag2el_1[] = {
    {(ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0}, /* accuracy */
    {(ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0}  /* iE-extensions */
};
asn_SEQUENCE_specifics_t asn_SPC_TRPPositionDirect_specs_1 = {
    sizeof(struct TRPPositionDirect),
    offsetof(struct TRPPositionDirect, _asn_ctx),
    asn_MAP_TRPPositionDirect_tag2el_1,
    2,                               /* Count of tags in the map */
    asn_MAP_TRPPositionDirect_oms_1, /* Optional members */
    1,
    0, /* Root/Additions */
    2, /* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_TRPPositionDirect = {
    "TRPPositionDirect",
    "TRPPositionDirect",
    &asn_OP_SEQUENCE,
    asn_DEF_TRPPositionDirect_tags_1,
    sizeof(asn_DEF_TRPPositionDirect_tags_1) /
        sizeof(asn_DEF_TRPPositionDirect_tags_1[0]), /* 1 */
    asn_DEF_TRPPositionDirect_tags_1,                /* Same as above */
    sizeof(asn_DEF_TRPPositionDirect_tags_1) /
        sizeof(asn_DEF_TRPPositionDirect_tags_1[0]), /* 1 */
    {0, 0, SEQUENCE_constraint},
    asn_MBR_TRPPositionDirect_1,
    2,                                 /* Elements count */
    &asn_SPC_TRPPositionDirect_specs_1 /* Additional specs */
};
