/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NRPPA-IEs"
 * 	found in "38455.asn"
 * 	`asn1c -no-gen-OER -fcompound-names -no-gen-example -findirect-choice
 * -fno-include-deps -D nrppa`
 */

#ifndef _UL_RTOAMeasurement_H_
#define _UL_RTOAMeasurement_H_

#include <asn_application.h>

/* Including external dependencies */
#include "ULRTOAMeas.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct AdditionalPathList;

/* UL-RTOAMeasurement */
typedef struct UL_RTOAMeasurement {
  ULRTOAMeas_t uLRTOAmeas;
  struct AdditionalPathList* additionalPathList; /* OPTIONAL */
  /*
   * This type is extensible,
   * possible extensions are below.
   */

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} UL_RTOAMeasurement_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_UL_RTOAMeasurement;
extern asn_SEQUENCE_specifics_t asn_SPC_UL_RTOAMeasurement_specs_1;
extern asn_TYPE_member_t asn_MBR_UL_RTOAMeasurement_1[2];

#ifdef __cplusplus
}
#endif

#endif /* _UL_RTOAMeasurement_H_ */
#include <asn_internal.h>
