/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NRPPA-IEs"
 * 	found in "38455.asn"
 * 	`asn1c -no-gen-OER -fcompound-names -no-gen-example -findirect-choice
 * -fno-include-deps -D nrppa`
 */

#ifndef _ULRTOAMeas_H_
#define _ULRTOAMeas_H_

#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ULRTOAMeas_PR {
  ULRTOAMeas_PR_NOTHING, /* No components present */
  ULRTOAMeas_PR_k0,
  ULRTOAMeas_PR_k1,
  ULRTOAMeas_PR_k2,
  ULRTOAMeas_PR_k3,
  ULRTOAMeas_PR_k4,
  ULRTOAMeas_PR_k5
  /* Extensions may appear below */

} ULRTOAMeas_PR;

/* ULRTOAMeas */
typedef struct ULRTOAMeas {
  ULRTOAMeas_PR present;
  union ULRTOAMeas_u {
    long k0;
    long k1;
    long k2;
    long k3;
    long k4;
    long k5;
    /*
     * This type is extensible,
     * possible extensions are below.
     */
  } choice;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} ULRTOAMeas_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ULRTOAMeas;
extern asn_CHOICE_specifics_t asn_SPC_ULRTOAMeas_specs_1;
extern asn_TYPE_member_t asn_MBR_ULRTOAMeas_1[6];
extern asn_per_constraints_t asn_PER_type_ULRTOAMeas_constr_1;

#ifdef __cplusplus
}
#endif

#endif /* _ULRTOAMeas_H_ */
#include <asn_internal.h>
