/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NRPPA-IEs"
 * 	found in "e2ap-v01.01.asn1"
 * 	`asn1c -gen-PER -fcompound-names -findirect-choice -fno-include-deps`
 */

#ifndef	_ValueRSRQ_NR_H_
#define	_ValueRSRQ_NR_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ValueRSRQ-NR */
typedef long	 ValueRSRQ_NR_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_ValueRSRQ_NR_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_ValueRSRQ_NR;
asn_struct_free_f ValueRSRQ_NR_free;
asn_struct_print_f ValueRSRQ_NR_print;
asn_constr_check_f ValueRSRQ_NR_constraint;
ber_type_decoder_f ValueRSRQ_NR_decode_ber;
der_type_encoder_f ValueRSRQ_NR_encode_der;
xer_type_decoder_f ValueRSRQ_NR_decode_xer;
xer_type_encoder_f ValueRSRQ_NR_encode_xer;
oer_type_decoder_f ValueRSRQ_NR_decode_oer;
oer_type_encoder_f ValueRSRQ_NR_encode_oer;
per_type_decoder_f ValueRSRQ_NR_decode_uper;
per_type_encoder_f ValueRSRQ_NR_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _ValueRSRQ_NR_H_ */
#include <asn_internal.h>
