/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NRPPA-IEs"
 * 	found in "e2ap-v01.01.asn1"
 * 	`asn1c -gen-PER -fcompound-names -findirect-choice -fno-include-deps`
 */

#ifndef	_WLANMeasurementQuantities_H_
#define	_WLANMeasurementQuantities_H_


#include <asn_application.h>

/* Including external dependencies */
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct ProtocolIE_Single_Container;

/* WLANMeasurementQuantities */
typedef struct WLANMeasurementQuantities {
	A_SEQUENCE_OF(struct ProtocolIE_Single_Container) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} WLANMeasurementQuantities_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_WLANMeasurementQuantities;

#ifdef __cplusplus
}
#endif

#endif	/* _WLANMeasurementQuantities_H_ */
#include <asn_internal.h>
