/**
 * LMF Location
 * LMF Location Service. © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA,
 * ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 1.1.5
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

/*
 * CancelLocationApiImpl.h
 *
 *
 */

#ifndef CANCEL_LOCATION_API_IMPL_H_
#define CANCEL_LOCATION_API_IMPL_H_

#include <memory>
#include <optional>
#include <pistache/endpoint.h>
#include <pistache/http.h>
#include <pistache/router.h>

#include <CancelLocationApi.h>

#include "CancelLocData.h"
#include "ProblemDetails.h"
#include "RedirectResponse.h"
#include "lmf_app.hpp"
#include <string>

namespace oai {
namespace lmf_server {
namespace api {

using namespace oai::lmf_server::model;
using namespace oai::lmf::app;

class CancelLocationApiImpl : public oai::lmf_server::api::CancelLocationApi {
public:
  CancelLocationApiImpl(std::shared_ptr<Pistache::Rest::Router>,
                        lmf_app *lmf_app_inst, std::string address);
  ~CancelLocationApiImpl() {}

  void cancel_location(const CancelLocData &cancelLocData,
                       Pistache::Http::ResponseWriter &response);

private:
  lmf_app *m_lmf_app;
  std::string m_address;
};

} // namespace api
} // namespace lmf_server
} // namespace oai

#endif
