/**
 * LMF Location
 * LMF Location Service. © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA,
 * ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 1.1.5
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

#include "LocationContextTransferApiImpl.h"

namespace oai {
namespace lmf_server {
namespace api {

using namespace oai::lmf_server::model;

LocationContextTransferApiImpl::LocationContextTransferApiImpl(
    const std::shared_ptr<Pistache::Rest::Router>& rtr)
    : LocationContextTransferApi(rtr) {}

void LocationContextTransferApiImpl::location_context_transfer(
    const LocContextData& locContextData,
    Pistache::Http::ResponseWriter& response) {
  response.send(Pistache::Http::Code::Ok, "Do some magic\n");
}

}  // namespace api
}  // namespace lmf_server
}  // namespace oai
