/**
 * LMF Location
 * LMF Location Service. © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA,
 * ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 1.1.5
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

#include "LocationContextTransferApiImpl.h"
#include "logger.hpp"

namespace oai {
namespace lmf_server {
namespace api {

//
using namespace oai::lmf_server::model;

LocationContextTransferApiImpl::LocationContextTransferApiImpl(
    std::shared_ptr<Pistache::Rest::Router> rtr, lmf_app *lmf_app_inst,
    std::string address)
    : LocationContextTransferApi(rtr), m_lmf_app(lmf_app_inst),
      m_address(address) {}

void LocationContextTransferApiImpl::location_context_transfer(
    const LocContextData &locContextData,
    Pistache::Http::ResponseWriter &response) {
  Pistache::Http::Code code = {};
  nlohmann::json json_data = {};
  m_lmf_app->handle_location_context_transfer(locContextData, json_data, code);

  // lmf --> amf
  Logger::lmf_server().debug("Location context transfer response:\n %s",
                             json_data.dump().c_str());

  Logger::lmf_server().info(
      "Send Location context transfer response to AMF (Code %d)", code);

  response.send(code, json_data.dump().c_str());
  // response.send(Pistache::Http::Code::Ok, "Do some magic\n");
}

} // namespace api
} // namespace lmf_server
} // namespace oai
