/**
 * LMF Location
 * LMF Location Service. © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA,
 * ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 1.1.5
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

/*
 * LocationContextTransferApiImpl.h
 *
 *
 */

#ifndef LOCATION_CONTEXT_TRANSFER_API_IMPL_H_
#define LOCATION_CONTEXT_TRANSFER_API_IMPL_H_

#include <pistache/endpoint.h>
#include <pistache/http.h>
#include <pistache/router.h>
#include <memory>
#include <optional>

#include <LocationContextTransferApi.h>

#include "LocContextData.h"
#include "ProblemDetails.h"
#include "RedirectResponse.h"
#include <string>

namespace oai::lmf::api {

using namespace oai::model::lmf;

class LocationContextTransferApiImpl
    : public oai::lmf::api::LocationContextTransferApi {
 public:
  explicit LocationContextTransferApiImpl(
      const std::shared_ptr<Pistache::Rest::Router>& rtr);
  ~LocationContextTransferApiImpl() override = default;

  void location_context_transfer(
      const LocContextData& locContextData,
      Pistache::Http::ResponseWriter& response);
};

}  // namespace oai::lmf::api

#endif
