#/*
# * SPDX-License-Identifier: LicenseRef-CSSL-1.0
# */

#---------------------------------------------------------------------
#
# Dockerfile for the Open-Air-Interface LMF service
#   Valid for Ubuntu-20.04 (focal),
#             Ubuntu-22.04 (jammy)
# The port exposed by container are 8080/tcp , 9090/tcp change it according to your setup
#
#---------------------------------------------------------------------

#---------------------------------------------------------------------
# BASE IMAGE
#---------------------------------------------------------------------
ARG BASE_IMAGE=ubuntu:jammy
FROM $BASE_IMAGE AS oai-lmf-base

ENV DEBIAN_FRONTEND=noninteractive
ENV TZ=Europe/Paris
ENV IS_DOCKERFILE=1
RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get upgrade --yes && \
    DEBIAN_FRONTEND=noninteractive apt-get install --yes \
      psmisc \
      git \
      liblapacke-dev \
      libopenblas-dev \
  && rm -rf /var/lib/apt/lists/*

# Some GIT configuration command quite useful
RUN git config --global https.postBuffer 123289600 && \
    git config --global http.sslverify false

# Copying source code
WORKDIR /openair-lmf
COPY ./build/scripts /openair-lmf/build/scripts/
COPY ./build/common-build /openair-lmf/build/common-build/
COPY ./build/lmf/CMakeLists.txt /openair-lmf/build/lmf/CMakeLists.txt

# Installing all the needed libraries/packages to build and run LMF
WORKDIR /openair-lmf/build/scripts
RUN ./build_lmf --install-deps --force && \
    ldconfig

#---------------------------------------------------------------------
# BUILDER IMAGE
#---------------------------------------------------------------------
FROM oai-lmf-base AS oai-lmf-builder
# Copying source code
COPY . /openair-lmf
# Building LMF
WORKDIR /openair-lmf/build/scripts
RUN ./build_lmf --clean --Verbose --build-type Release --jobs && \
    ldd /openair-lmf/build/lmf/build/lmf && \
    mv /openair-lmf/build/lmf/build/lmf /openair-lmf/build/lmf/build/oai_lmf


#---------------------------------------------------------------------
# TARGET IMAGE
#---------------------------------------------------------------------
FROM $BASE_IMAGE AS oai-lmf
ARG TARGETPLATFORM
ARG VERSION=v4.47.1
ENV TARGETPLATFORM=${TARGETPLATFORM}

ENV DEBIAN_FRONTEND=noninteractive
ENV TZ=Europe/Paris
# We install some debug tools for the moment in addition of mandatory libraries
RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get upgrade --yes && \
    DEBIAN_FRONTEND=noninteractive apt-get install --yes \
      python3 \
      python3-jinja2 \
      psmisc \
      net-tools \
      iputils-ping \
      bc \
      tzdata \
      liblapacke \
      libopenblas0 \
      wget \
# Ubuntu 20 --> libasan5
# Ubuntu 22 --> libasan6
#      libasan? \
      libconfig++9v5 \
# Ubuntu 20 --> libnettle7
# Ubuntu 22 --> libnettle8
      libnettle? \
# Ubuntu 20 --> libhogweed5
# Ubuntu 22 --> libhogweed6
      libhogweed? \
# Ubuntu 20 --> libldap-2.4-2
# Ubuntu 22 --> libldap-2.5-0
      libldap-2.?-? \
      libkrb5-3 \
      libgssapi-krb5-2 \
      libcurl?-gnutls \
      librtmp1 \
      libpsl5 \
# Ubuntu 20 --> boost71
# Ubuntu 22 --> boost74
      libboost-thread1.7?.0 \
      libboost-chrono1.7?.0 \
  && rm -rf /var/lib/apt/lists/*

# Copying executable and generated libraries
WORKDIR /openair-lmf/bin
COPY --from=oai-lmf-builder \
    /openair-lmf/build/lmf/build/oai_lmf \
    /openair-lmf/scripts/healthcheck.sh \
    ./

RUN echo "Target platform is: ${TARGETPLATFORM}" && \
    case "${TARGETPLATFORM}" in \
      "linux/amd64") BINARY="yq_linux_amd64"; ;; \
      "linux/arm64") BINARY="yq_linux_arm64"; ;; \
      *) echo "Unsupported platform"; exit 1; ;; \
    esac && \
    wget https://github.com/mikefarah/yq/releases/download/${VERSION}/${BINARY} -O /usr/bin/yq && \
    chmod +x /usr/bin/yq


COPY --from=oai-lmf-builder \
# Copying only the packages built from source
    /usr/local/lib/libnghttp2.so.14 \
    /usr/local/lib/libnghttp2_asio.so.1 \
    /usr/local/lib/libpistache.so \
    /usr/local/lib/libspdlog.so \
    /usr/local/lib/libfmt.so \
    /usr/local/lib/libyaml-cpp.so.0.? \
    /usr/local/lib/libcpr.so.1 \
    /usr/local/lib/

RUN ldconfig && \
    ldd /openair-lmf/bin/oai_lmf

WORKDIR /openair-lmf/etc
COPY --from=oai-lmf-builder \
    /openair-lmf/etc/config.yaml \
    .

WORKDIR /openair-lmf

ARG GIT_COMMIT

LABEL org.opencontainers.image.authors="OpenAirInterface <contact@openairinterface.org>" \
      org.opencontainers.image.vendor="OpenAirInterface Software Alliance" \
      org.opencontainers.image.licenses="Collaborative Standards Software License v1.0 (CSSL v1.0)" \
      org.opencontainers.image.title="OAI LMF" \
      org.opencontainers.image.description="OpenAirInterface Location Management Function" \
      org.opencontainers.image.revision="commit:${GIT_COMMIT}"

EXPOSE 80/tcp

# healthcheck
HEALTHCHECK --interval=10s \
            --timeout=15s \
            --retries=6 \
    CMD /openair-lmf/bin/healthcheck.sh

CMD ["/openair-lmf/bin/oai_lmf", "-c" , "/openair-lmf/etc/config.yaml", "-o"]
