#/*
# * Licensed to the OpenAirInterface (OAI) Software Alliance under one or more
# * contributor license agreements.  See the NOTICE file distributed with
# * this work for additional information regarding copyright ownership.
# * The OpenAirInterface Software Alliance licenses this file to You under
# * the OAI Public License, Version 1.1  (the "License"); you may not use this file
# * except in compliance with the License.
# * You may obtain a copy of the License at
# *
# *      http://www.openairinterface.org/?page_id=698
# *
# * Unless required by applicable law or agreed to in writing, software
# * distributed under the License is distributed on an "AS IS" BASIS,
# * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# * See the License for the specific language governing permissions and
# * limitations under the License.
# *-------------------------------------------------------------------------------
# * For more information about the OpenAirInterface (OAI) Software Alliance:
# *      contact@openairinterface.org
# */
#---------------------------------------------------------------------
#
# Dockerfile for the Open-Air-Interface LMF service
#   Valid for Ubuntu-18.04 (bionic)
#
#---------------------------------------------------------------------

#---------------------------------------------------------------------
# BUILDER IMAGE
#---------------------------------------------------------------------
FROM ubuntu:bionic as oai-lmf-builder

ARG NEEDED_GIT_PROXY

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get upgrade --yes && \
    DEBIAN_FRONTEND=noninteractive apt-get install --yes \
      psmisc \
      software-properties-common \
      git \
  && rm -rf /var/lib/apt/lists/*

# Some GIT configuration command quite useful
RUN /bin/bash -c "if [[ -v NEEDED_GIT_PROXY ]]; then git config --global http.proxy $NEEDED_GIT_PROXY; fi"
RUN git config --global https.postBuffer 123289600 && \
    git config --global http.sslverify false

# Copying source code
WORKDIR /openair-lmf
COPY . /openair-lmf

# Installing and Building LMF
WORKDIR /openair-lmf/build/scripts
RUN ./build_lmf --install-deps --force
RUN ./build_lmf --clean --Verbose --build-type Release --jobs && \
    ldd /openair-lmf/build/lmf/build/lmf && \
    mv /openair-lmf/build/lmf/build/lmf /openair-lmf/build/lmf/build/oai_lmf

#---------------------------------------------------------------------
# TARGET IMAGE
#---------------------------------------------------------------------
FROM ubuntu:bionic as oai-lmf
ENV DEBIAN_FRONTEND=noninteractive
ENV TZ=Europe/Paris
# We install some debug tools for the moment in addition of mandatory libraries
RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get upgrade --yes && \
    DEBIAN_FRONTEND=noninteractive apt-get install --yes \
      psmisc \
      net-tools \
      tzdata \
      bc \
      perl \
      libasan4 \
      libnettle6 \
      libnghttp2-14 \
      libhogweed4 \
      libldap-2.4-2 \
      libgssapi-krb5-2 \
      librtmp1 \
      libpsl5 \
      libconfig++9v5 \
  && rm -rf /var/lib/apt/lists/*

# Copying executable and generated libraries
WORKDIR /openair-lmf/bin
COPY --from=oai-lmf-builder \
    /openair-lmf/build/lmf/build/oai_lmf \
    /openair-lmf/scripts/entrypoint.sh \
    ./

COPY --from=oai-lmf-builder \
    /usr/local/lib/libpistache.so \
    /usr/lib/libboost_system.so.1.67.0 \
    /usr/local/lib/libnghttp2_asio.so.1 \
    /usr/lib/x86_64-linux-gnu/libcurl-gnutls.so.4 \
    /usr/local/lib/

RUN ldconfig && \
    ldd /openair-lmf/bin/oai_lmf

WORKDIR /openair-lmf/etc
COPY --from=oai-lmf-builder /openair-lmf/etc/lmf.conf .

WORKDIR /openair-lmf

EXPOSE 80/tcp

ENTRYPOINT ["/bin/bash","/openair-lmf/bin/entrypoint.sh"]
CMD ["/openair-lmf/bin/oai_lmf", "-c" , "/openair-lmf/etc/lmf.conf", "-o"]
