#/*
# * Licensed to the OpenAirInterface (OAI) Software Alliance under one or more
# * contributor license agreements.  See the NOTICE file distributed with
# * this work for additional information regarding copyright ownership.
# * The OpenAirInterface Software Alliance licenses this file to You under
# * the OAI Public License, Version 1.1  (the "License"); you may not use this file
# * except in compliance with the License.
# * You may obtain a copy of the License at
# *
# *      http://www.openairinterface.org/?page_id=698
# *
# * Unless required by applicable law or agreed to in writing, software
# * distributed under the License is distributed on an "AS IS" BASIS,
# * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# * See the License for the specific language governing permissions and
# * limitations under the License.
# *-------------------------------------------------------------------------------
# * For more information about the OpenAirInterface (OAI) Software Alliance:
# *      contact@openairinterface.org
# */
#---------------------------------------------------------------------
#
# Dockerfile for the Open-Air-Interface LMF service
#   Valid for UBI 8.6 | RHEL 8.6
#
#---------------------------------------------------------------------

#---------------------------------------------------------------------
# BUILDER IMAGE
#---------------------------------------------------------------------
FROM registry.access.redhat.com/ubi8/ubi:latest AS oai-lmf-builder

# Copy the entitlements
COPY ./etc-pki-entitlement /etc/pki/entitlement

# Copy the subscription manager configurations
COPY ./rhsm-conf /etc/rhsm
COPY ./rhsm-ca /etc/rhsm/ca

RUN rm -f /etc/rhsm-host && \
    yum repolist --disablerepo=* && \
    subscription-manager repos --enable codeready-builder-for-rhel-8-x86_64-rpms && \
    yum update -y && \
    yum install -y \
        psmisc \
        git \
        diffutils \
        file \
        gcc-c++ \
        ninja-build \
        boost-devel \
        openssl-devel \
        openssl \
        wget \
        libasan && \
    echo "/usr/local/lib" > /etc/ld.so.conf.d/local-lib.conf && \
    echo "/usr/local/lib64" >> /etc/ld.so.conf.d/local-lib.conf

# Some GIT configuration command quite useful
RUN git config --global https.postBuffer 123289600 && \
    git config --global http.sslverify false

# Copying source code
WORKDIR /openair-lmf
COPY . /openair-lmf

# Installing all the needed libraries/packages to build and run LMF
WORKDIR /openair-lmf/build/scripts
RUN ./build_lmf --install-deps --force

# Building LMF
WORKDIR /openair-lmf/build/scripts
RUN ldconfig && \
    ./build_lmf --clean --Verbose --build-type Release --jobs && \
    ldd /openair-lmf/build/lmf/build/lmf && \
    mv /openair-lmf/build/lmf/build/lmf /openair-lmf/build/lmf/build/oai_lmf && \
    # Remove entitlements and Subscription Manager configs
    rm -rf /etc/pki/entitlement && \
    rm -rf /etc/rhsm

#---------------------------------------------------------------------
# TARGET IMAGE
#---------------------------------------------------------------------
FROM registry.access.redhat.com/ubi8/ubi-minimal:latest as oai-lmf
ENV TZ=Europe/Paris

# Copy the entitlements
COPY ./etc-pki-entitlement /etc/pki/entitlement
# Copy the subscription manager configurations
COPY ./rhsm-conf /etc/rhsm
COPY ./rhsm-ca /etc/rhsm/ca


RUN rm -f /etc/rhsm-host && \
    microdnf update -y && \
    microdnf install -y \
      tzdata \
      procps-ng \
      psmisc \
      net-tools \
      libicu \
      boost \
      libevent \
      findutils \
      libconfig && \
    microdnf clean all -y && \
    rm -rf /var/cache/yum /var/cache/dnf && \
    # Remove entitlements and Subscription Manager configs
    rm -rf /etc/pki/entitlement && \
    rm -rf /etc/rhsm

# Copying executable and generated libraries
WORKDIR /openair-lmf/bin
COPY --from=oai-lmf-builder \
    /openair-lmf/build/lmf/build/oai_lmf \
    /openair-lmf/scripts/entrypoint.sh \
    /openair-lmf/scripts/healthcheck.sh \
    ./

COPY --from=oai-lmf-builder \
    /usr/local/lib64/libpistache.so.0 \
    /usr/local/lib/libnghttp2_asio.so \
    /usr/local/lib/libnghttp2_asio.so.1 \
    /openair-lmf/build/lmf/build/nas/libNAS.so \
    /usr/lib64/

RUN ldconfig -v && \
    ldd /openair-lmf/bin/oai_lmf

# Copying template configuration files
# The configuration folder will be flat
WORKDIR /openair-lmf/etc
COPY --from=oai-lmf-builder /openair-lmf/etc/lmf.conf .

WORKDIR /openair-lmf

# expose ports
EXPOSE 80/tcp 9090/tcp 8805/udp
# healthcheck
HEALTHCHECK --interval=10s \
            --timeout=15s \
            --retries=6 \
    CMD /openair-lmf/bin/healthcheck.sh

ENTRYPOINT ["/bin/bash","/openair-lmf/bin/entrypoint.sh"]
CMD ["/openair-lmf/bin/oai_lmf", "-c" , "/openair-lmf/etc/lmf.conf", "-o"]
