#/*
# * Licensed to the OpenAirInterface (OAI) Software Alliance under one or more
# * contributor license agreements.  See the NOTICE file distributed with
# * this work for additional information regarding copyright ownership.
# * The OpenAirInterface Software Alliance licenses this file to You under
# * the OAI Public License, Version 1.1  (the "License"); you may not use this file
# * except in compliance with the License.
# * You may obtain a copy of the License at
# *
# *      http://www.openairinterface.org/?page_id=698
# *
# * Unless required by applicable law or agreed to in writing, software
# * distributed under the License is distributed on an "AS IS" BASIS,
# * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# * See the License for the specific language governing permissions and
# * limitations under the License.
# *-------------------------------------------------------------------------------
# * For more information about the OpenAirInterface (OAI) Software Alliance:
# *      contact@openairinterface.org
# */
#---------------------------------------------------------------------
#
# Dockerfile for the Open-Air-Interface LMF service
#   Valid for RHEL 8.2
#
#---------------------------------------------------------------------

#---------------------------------------------------------------------
# BUILDER IMAGE
#---------------------------------------------------------------------
FROM registry.access.redhat.com/ubi8/ubi:latest AS oai-lmf-builder

ARG NEEDED_GIT_PROXY

# Copy the entitlements
COPY ./etc-pki-entitlement /etc/pki/entitlement

# Copy the subscription manager configurations
COPY ./rhsm-conf /etc/rhsm
COPY ./rhsm-ca /etc/rhsm/ca

RUN rm -f /etc/rhsm-host && \
    yum repolist --disablerepo=* && \
    subscription-manager repos --enable codeready-builder-for-rhel-8-x86_64-rpms && \
    yum update -y && \
    yum install -y \
        psmisc \
        git \
        diffutils \
        file \
        gcc-c++ \
        boost-devel \
        openssl-devel \
        openssl \
        libasan && \
    echo "/usr/local/lib" > /etc/ld.so.conf.d/local-lib.conf && \
    echo "/usr/local/lib64" >> /etc/ld.so.conf.d/local-lib.conf

# Some GIT configuration command quite useful
RUN /bin/bash -c "if [[ -v NEEDED_GIT_PROXY ]]; then git config --global http.proxy $NEEDED_GIT_PROXY; fi"
RUN git config --global https.postBuffer 123289600 && \
    git config --global http.sslverify false

# Copying source code
WORKDIR /openair-lmf
COPY . /openair-lmf

# Installing and Building LMF
WORKDIR /openair-lmf/build/scripts
RUN ./build_lmf --install-deps --force
RUN ./build_lmf --clean --Verbose --build-type Release --jobs && \
    ldd /openair-lmf/build/lmf/build/lmf && \
    mv /openair-lmf/build/lmf/build/lmf /openair-lmf/build/lmf/build/oai_lmf

#---------------------------------------------------------------------
# TARGET IMAGE
#---------------------------------------------------------------------
FROM registry.access.redhat.com/ubi8/ubi:latest as oai-lmf
ENV TZ=Europe/Paris
# We install some debug tools for the moment in addition of mandatory libraries
RUN yum update -y && \
    yum install -y --enablerepo="ubi-8-codeready-builder" \
      tzdata \
      procps-ng \
      psmisc \
      net-tools \
      nettle \
      libasan \
      libevent && \
    yum clean all -y && \
    rm -rf /var/cache/yum /var/cache/dnf && \
    echo "/usr/local/lib" > /etc/ld.so.conf.d/local-lib.conf && \
    echo "/usr/local/lib64" >> /etc/ld.so.conf.d/local-lib.conf

# Copying executable and generated libraries
WORKDIR /openair-lmf/bin
COPY --from=oai-lmf-builder \
    /openair-lmf/build/lmf/build/oai_lmf \
    /openair-lmf/scripts/entrypoint.sh \
    ./

WORKDIR /usr/local/lib64
COPY --from=oai-lmf-builder \
    /usr/local/lib64/libpistache.so.0 \
    /lib64/libboost_system.so.1.66.0 \
    /lib64/libboost_thread.so.1.66.0 \
    /lib64/libboost_date_time.so.1.66.0 \
    /lib64/libconfig++.so.9 \
    /lib64/libnghttp2.so.14 \
    /usr/local/lib/libnghttp2_asio.so.1 \
    ./

RUN ldconfig -v && \
    ldd /openair-lmf/bin/oai_lmf

WORKDIR /openair-lmf/etc
COPY --from=oai-lmf-builder /openair-lmf/etc/lmf.conf .

WORKDIR /openair-lmf

EXPOSE 80/tcp

ENTRYPOINT ["/bin/bash","/openair-lmf/bin/entrypoint.sh"]
CMD ["/openair-lmf/bin/oai_lmf", "-c" , "/openair-lmf/etc/lmf.conf", "-o"]
