#/*
# * Licensed to the OpenAirInterface (OAI) Software Alliance under one or more
# * contributor license agreements.  See the NOTICE file distributed with
# * this work for additional information regarding copyright ownership.
# * The OpenAirInterface Software Alliance licenses this file to You under
# * the OAI Public License, Version 1.1  (the "License"); you may not use this file
# * except in compliance with the License.
# * You may obtain a copy of the License at
# *
# *      http://www.openairinterface.org/?page_id=698
# *
# * Unless required by applicable law or agreed to in writing, software
# * distributed under the License is distributed on an "AS IS" BASIS,
# * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# * See the License for the specific language governing permissions and
# * limitations under the License.
# *-------------------------------------------------------------------------------
# * For more information about the OpenAirInterface (OAI) Software Alliance:
# *      contact@openairinterface.org
# */
#---------------------------------------------------------------------
#
# Dockerfile for the Open-Air-Interface LMF service
#   Valid for Rocky Linux 8.7+
#
#---------------------------------------------------------------------

#---------------------------------------------------------------------
# BUILDER IMAGE
#---------------------------------------------------------------------
FROM docker.io/rockylinux:8 AS oai-lmf-builder

ENV IS_DOCKERFILE=1

RUN dnf install 'dnf-command(config-manager)' -y && \
    dnf config-manager --set-enabled powertools && \
    dnf install epel-release -y && crb enable && \
    dnf update -y && \
    # here just to display the current version
    cat /etc/os-release && \
    dnf install -y \
        psmisc \
        git \
        diffutils \
        libasan \
        wget \
        file && \
    echo "/usr/local/lib" > /etc/ld.so.conf.d/local-lib.conf && \
    echo "/usr/local/lib64" >> /etc/ld.so.conf.d/local-lib.conf

# Some GIT configuration command quite useful
RUN git config --global https.postBuffer 123289600 && \
    git config --global http.sslverify false

# Copying source code
WORKDIR /openair-lmf
COPY . /openair-lmf

# Installing and Building LMF
WORKDIR /openair-lmf/build/scripts
RUN ./build_lmf --install-deps --force && \
    ldconfig
RUN ./build_lmf --clean --Verbose --build-type Release --jobs && \
    ldd /openair-lmf/build/lmf/build/lmf && \
    mv /openair-lmf/build/lmf/build/lmf /openair-lmf/build/lmf/build/oai_lmf && \
    # Adapting the entrypoint to NEF NF
    sed -i -e "s@openair-nf-root-folder@openair-lmf@g" \
           -e "s@nf-config-file@lmf.conf@g" \
           ../common-build/docker-scripts/entrypoint.py

#---------------------------------------------------------------------
# TARGET IMAGE
#---------------------------------------------------------------------
FROM docker.io/rockylinux:8-minimal as oai-lmf
ENV TZ=Europe/Paris

# We install some debug tools for the moment in addition of mandatory libraries
RUN microdnf update -y && \
    microdnf install -y \
      python3 \
      python3-pip \
      tzdata \
#      libasan \
      procps-ng \
      psmisc \
      net-tools \
      libicu \
      boost \
      libevent \
      findutils \
      libconfig && \
    pip3 install jinja2 && \
    microdnf clean all -y && \
    rm -rf /var/cache/yum /var/cache/dnf

# Copying executable and generated libraries
WORKDIR /openair-lmf/bin
COPY --from=oai-lmf-builder \
    /openair-lmf/build/lmf/build/oai_lmf \
    /openair-lmf/build/common-build/docker-scripts/entrypoint.py \
    /openair-lmf/scripts/healthcheck.sh \
    ./

WORKDIR /usr/lib64
COPY --from=oai-lmf-builder \
# Copying only the packages built from source
    /usr/local/lib64/libpistache.so.0 \
    /usr/local/lib/libnghttp2_asio.so \
    /usr/local/lib/libnghttp2_asio.so.1 \
    /usr/local/lib64/libspdlog.so \
    /usr/local/lib64/libfmt.so \
    /usr/lib64/

RUN ldconfig -v && \
    ldd /openair-lmf/bin/oai_lmf

WORKDIR /openair-lmf/etc
COPY --from=oai-lmf-builder /openair-lmf/etc/lmf.conf .

WORKDIR /openair-lmf

EXPOSE 80/tcp
# healthcheck
HEALTHCHECK --interval=10s \
            --timeout=15s \
            --retries=6 \
    CMD /openair-lmf/bin/healthcheck.sh

ENTRYPOINT ["python3","/openair-lmf/bin/entrypoint.py"]
CMD ["/openair-lmf/bin/oai_lmf", "-c" , "/openair-lmf/etc/lmf.conf", "-o"]
