/**
 * RNI API
 * The ETSI MEC ISG MEC012 Radio Network Information API described using OpenAPI
 *
 * OpenAPI spec version: 1.1.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

/*
 * Licensed to the OpenAirInterface (OAI) Software Alliance under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The OpenAirInterface Software Alliance licenses this file to You under
 * the OAI Public License, Version 1.1  (the "License"); you may not use this
 *file except in compliance with the License. You may obtain a copy of the
 *License at
 *
 *      http://www.openairinterface.org/?page_id=698
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *-------------------------------------------------------------------------------
 * For more information about the OpenAirInterface (OAI) Software Alliance:
 *      contact@openairinterface.org
 */

#ifndef FILE_LMF_API_SERVER_SEEN
#define FILE_LMF_API_SERVER_SEEN

#include "pistache/endpoint.h"
#include "pistache/http.h"
#include "pistache/router.h"

#include "CancelLocationApiImpl.h"
#include "DetermineLocationApiImpl.h"
#include "LocationContextTransferApiImpl.h"
// #include "RequestCipheringKeyDataApiImpl.h"
#include "lmf_app.hpp"

#ifdef __linux__
#include <signal.h>
#include <unistd.h>
#include <vector>
#endif

using namespace oai::lmf_server::api;
using namespace oai::lmf::app;

class LMFApiServer {
public:
  LMFApiServer(Pistache::Address address, lmf_app *lmf_app_inst)
      : m_httpEndpoint(std::make_shared<Pistache::Http::Endpoint>(address)) {
    m_router = std::make_shared<Pistache::Rest::Router>();
    m_address = address.host() + ":" + (address.port()).toString();
  }
  void init(size_t thr = 1);
  void start();
  void shutdown();

private:
  std::shared_ptr<Pistache::Http::Endpoint> m_httpEndpoint;
  std::shared_ptr<Pistache::Rest::Router> m_router;
  std::shared_ptr<DetermineLocationApiImpl> m_DetermineLocationApiImpl;
  std::shared_ptr<CancelLocationApiImpl> m_CancelLocationApiImpl;
  std::shared_ptr<LocationContextTransferApiImpl>
      m_LocationContextTransferApiImpl;
  // std::shared_ptr<RequestCipheringKeyDataApiImpl>
  //     m_RequestCipheringKeyDataApiImpl;
  std::string m_address;
};

#endif
