/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 */

#ifndef _ASN_CONSTANT_H
#define _ASN_CONSTANT_H

#ifdef __cplusplus
extern "C" {
#endif

#define min_val_SequenceNumber (0)
#define max_val_SequenceNumber (255)
#define min_val_TransactionNumber (0)
#define max_val_TransactionNumber (255)
#define min_val_ARFCN_ValueEUTRA (0)
#define max_val_ARFCN_ValueEUTRA (65535)
#define min_val_ARFCN_ValueEUTRA_v9a0 (65536)
#define max_val_ARFCN_ValueEUTRA_v9a0 (262143)
#define min_val_ARFCN_ValueEUTRA_r14 (0)
#define max_val_ARFCN_ValueEUTRA_r14 (262143)
#define maxEARFCN (65535)
#define maxEARFCN_Plus1 (65536)
#define maxEARFCN2 (262143)
#define min_val_ARFCN_ValueNR_r15 (0)
#define max_val_ARFCN_ValueNR_r15 (3279165)
#define min_val_ARFCN_ValueUTRA (0)
#define max_val_ARFCN_ValueUTRA (16383)
#define maxEPDU (16)
#define min_val_EPDU_ID (1)
#define max_val_EPDU_ID (256)
#define min_val_ReportingDuration (0)
#define max_val_ReportingDuration (255)
#define maxAddPRSconfig_r14 (2)
#define maxAvailNarrowBands_Minus1_r14 (15)
#define maxFreqLayers (3)
#define maxCarrier_r14 (5)
#define maxCells_r14 (72)
#define maxPaths_r14 (2)
#define maxBands (64)
#define maxFBI (64)
#define maxFBI_Plus1 (65)
#define maxFBI2 (256)
#define maxMBS_r14 (64)
#define maxWLAN_AP_r13 (64)
#define maxWLAN_DataSets_r14 (8)
#define maxWLAN_AP_r14 (128)
#define maxVisibleAPs_r14 (32)
#define maxKnownAPs_r14 (2048)
#define maxBT_Beacon_r13 (32)


#ifdef __cplusplus
}
#endif

#endif /* _ASN_CONSTANT_H */
