/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "LPP-PDU-Definitions"
 * 	found in "37355-g60.asn"
 * 	`asn1c -no-gen-OER -fcompound-names -no-gen-example -findirect-choice
 * -fno-include-deps -D lpp`
 */

#ifndef _DL_AoD_MeasCapabilityPerBand_r16_H_
#define _DL_AoD_MeasCapabilityPerBand_r16_H_

#include <asn_application.h>

/* Including external dependencies */
#include "FreqBandIndicatorNR-r16.h"
#include <NativeEnumerated.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum DL_AoD_MeasCapabilityPerBand_r16__simul_NR_DL_AoD_DL_TDOA_r16 {
  DL_AoD_MeasCapabilityPerBand_r16__simul_NR_DL_AoD_DL_TDOA_r16_supported = 0
} e_DL_AoD_MeasCapabilityPerBand_r16__simul_NR_DL_AoD_DL_TDOA_r16;
typedef enum DL_AoD_MeasCapabilityPerBand_r16__simul_NR_DL_AoD_Multi_RTT_r16 {
  DL_AoD_MeasCapabilityPerBand_r16__simul_NR_DL_AoD_Multi_RTT_r16_supported = 0
} e_DL_AoD_MeasCapabilityPerBand_r16__simul_NR_DL_AoD_Multi_RTT_r16;

/* DL-AoD-MeasCapabilityPerBand-r16 */
typedef struct DL_AoD_MeasCapabilityPerBand_r16 {
  FreqBandIndicatorNR_r16_t freqBandIndicatorNR_r16;
  long* simul_NR_DL_AoD_DL_TDOA_r16;   /* OPTIONAL */
  long* simul_NR_DL_AoD_Multi_RTT_r16; /* OPTIONAL */
  /*
   * This type is extensible,
   * possible extensions are below.
   */

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} DL_AoD_MeasCapabilityPerBand_r16_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_simul_NR_DL_AoD_DL_TDOA_r16_3;	//
 * (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_simul_NR_DL_AoD_Multi_RTT_r16_5;
 * // (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_DL_AoD_MeasCapabilityPerBand_r16;
extern asn_SEQUENCE_specifics_t
    asn_SPC_DL_AoD_MeasCapabilityPerBand_r16_specs_1;
extern asn_TYPE_member_t asn_MBR_DL_AoD_MeasCapabilityPerBand_r16_1[3];

#ifdef __cplusplus
}
#endif

#endif /* _DL_AoD_MeasCapabilityPerBand_r16_H_ */
#include <asn_internal.h>
