/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "LPP-PDU-Definitions"
 * 	found in "lpp.asn1"
 * 	`asn1c -pdu=all -fcompound-names -fno-include-deps -findirect-choice
 * -no-gen-BER -no-gen-OER -no-gen-JER -no-gen-example -D oai-lmf/src/lpp/`
 */

#ifndef _EPDU_Body_H_
#define _EPDU_Body_H_

#include <asn_application.h>

/* Including external dependencies */
#include <OCTET_STRING.h>

#ifdef __cplusplus
extern "C" {
#endif

/* EPDU-Body */
typedef OCTET_STRING_t EPDU_Body_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_EPDU_Body;
asn_struct_free_f EPDU_Body_free;
asn_struct_print_f EPDU_Body_print;
asn_constr_check_f EPDU_Body_constraint;
xer_type_decoder_f EPDU_Body_decode_xer;
xer_type_encoder_f EPDU_Body_encode_xer;
per_type_decoder_f EPDU_Body_decode_uper;
per_type_encoder_f EPDU_Body_encode_uper;
per_type_decoder_f EPDU_Body_decode_aper;
per_type_encoder_f EPDU_Body_encode_aper;

#ifdef __cplusplus
}
#endif

#endif /* _EPDU_Body_H_ */
#include <asn_internal.h>
