/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "LPP-PDU-Definitions"
 * 	found in "37355-g60.asn"
 * 	`asn1c -no-gen-OER -fcompound-names -no-gen-example -findirect-choice
 * -fno-include-deps -D lpp`
 */

#ifndef _GNSS_NavigationModelReq_H_
#define _GNSS_NavigationModelReq_H_

#include <asn_application.h>

/* Including external dependencies */
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum GNSS_NavigationModelReq_PR {
  GNSS_NavigationModelReq_PR_NOTHING, /* No components present */
  GNSS_NavigationModelReq_PR_storedNavList,
  GNSS_NavigationModelReq_PR_reqNavList
  /* Extensions may appear below */

} GNSS_NavigationModelReq_PR;

/* Forward declarations */
struct StoredNavListInfo;
struct ReqNavListInfo;

/* GNSS-NavigationModelReq */
typedef struct GNSS_NavigationModelReq {
  GNSS_NavigationModelReq_PR present;
  union GNSS_NavigationModelReq_u {
    struct StoredNavListInfo* storedNavList;
    struct ReqNavListInfo* reqNavList;
    /*
     * This type is extensible,
     * possible extensions are below.
     */
  } choice;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} GNSS_NavigationModelReq_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_GNSS_NavigationModelReq;
extern asn_CHOICE_specifics_t asn_SPC_GNSS_NavigationModelReq_specs_1;
extern asn_TYPE_member_t asn_MBR_GNSS_NavigationModelReq_1[2];
extern asn_per_constraints_t asn_PER_type_GNSS_NavigationModelReq_constr_1;

#ifdef __cplusplus
}
#endif

#endif /* _GNSS_NavigationModelReq_H_ */
#include <asn_internal.h>
