/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "LPP-PDU-Definitions"
 * 	found in "lpp.asn1"
 * 	`asn1c -gen-PER -fcompound-names -no-gen-example -findirect-choice -fno-include-deps`
 */

#ifndef	_GNSS_IonosphericModel_H_
#define	_GNSS_IonosphericModel_H_


#include <asn_application.h>

/* Including external dependencies */
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct KlobucharModelParameter;
struct NeQuickModelParameter;

/* GNSS-IonosphericModel */
typedef struct GNSS_IonosphericModel {
	struct KlobucharModelParameter	*klobucharModel;	/* OPTIONAL */
	struct NeQuickModelParameter	*neQuickModel;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} GNSS_IonosphericModel_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_GNSS_IonosphericModel;
extern asn_SEQUENCE_specifics_t asn_SPC_GNSS_IonosphericModel_specs_1;
extern asn_TYPE_member_t asn_MBR_GNSS_IonosphericModel_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _GNSS_IonosphericModel_H_ */
#include <asn_internal.h>
