#include "LPP-Message.h"
#include "LPP-TransactionID.h"
#include "LPP-MessageBody.h"
#include "RequestLocationInformation.h"
#include "RequestLocationInformation-r9-IEs.h"
#include "CommonIEsRequestLocationInformation.h"
#include "LocationCoordinateTypes.h"
#include "VelocityTypes.h"