/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "LPP-PDU-Definitions"
 * 	found in "37355-g60.asn"
 * 	`asn1c -no-gen-OER -fcompound-names -no-gen-example -findirect-choice
 * -fno-include-deps -D lpp`
 */

#ifndef _NR_Multi_RTT_MeasElement_r16_H_
#define _NR_Multi_RTT_MeasElement_r16_H_

#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include "NR-PhysCellID-r16.h"
#include "ARFCN-ValueNR-r15.h"
#include "NR-DL-PRS-ResourceID-r16.h"
#include "NR-DL-PRS-ResourceSetID-r16.h"
#include "NR-TimeStamp-r16.h"
#include "NR-TimingQuality-r16.h"
#include <constr_CHOICE.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum NR_Multi_RTT_MeasElement_r16__nr_UE_RxTxTimeDiff_r16_PR {
  NR_Multi_RTT_MeasElement_r16__nr_UE_RxTxTimeDiff_r16_PR_NOTHING, /* No
                                                                      components
                                                                      present */
  NR_Multi_RTT_MeasElement_r16__nr_UE_RxTxTimeDiff_r16_PR_k0_r16,
  NR_Multi_RTT_MeasElement_r16__nr_UE_RxTxTimeDiff_r16_PR_k1_r16,
  NR_Multi_RTT_MeasElement_r16__nr_UE_RxTxTimeDiff_r16_PR_k2_r16,
  NR_Multi_RTT_MeasElement_r16__nr_UE_RxTxTimeDiff_r16_PR_k3_r16,
  NR_Multi_RTT_MeasElement_r16__nr_UE_RxTxTimeDiff_r16_PR_k4_r16,
  NR_Multi_RTT_MeasElement_r16__nr_UE_RxTxTimeDiff_r16_PR_k5_r16
  /* Extensions may appear below */

} NR_Multi_RTT_MeasElement_r16__nr_UE_RxTxTimeDiff_r16_PR;

/* Forward declarations */
struct NCGI_r15;
struct NR_AdditionalPathList_r16;
struct NR_Multi_RTT_AdditionalMeasurements_r16;

/* NR-Multi-RTT-MeasElement-r16 */
typedef struct NR_Multi_RTT_MeasElement_r16 {
  long dl_PRS_ID_r16;
  NR_PhysCellID_r16_t* nr_PhysCellID_r16;                     /* OPTIONAL */
  struct NCGI_r15* nr_CellGlobalID_r16;                       /* OPTIONAL */
  ARFCN_ValueNR_r15_t* nr_ARFCN_r16;                          /* OPTIONAL */
  NR_DL_PRS_ResourceID_r16_t* nr_DL_PRS_ResourceID_r16;       /* OPTIONAL */
  NR_DL_PRS_ResourceSetID_r16_t* nr_DL_PRS_ResourceSetID_r16; /* OPTIONAL */
  struct NR_Multi_RTT_MeasElement_r16__nr_UE_RxTxTimeDiff_r16 {
    NR_Multi_RTT_MeasElement_r16__nr_UE_RxTxTimeDiff_r16_PR present;
    union NR_Multi_RTT_MeasElement_r16__nr_UE_RxTxTimeDiff_r16_u {
      long k0_r16;
      long k1_r16;
      long k2_r16;
      long k3_r16;
      long k4_r16;
      long k5_r16;
      /*
       * This type is extensible,
       * possible extensions are below.
       */
    } choice;

    /* Context for parsing across buffer boundaries */
    asn_struct_ctx_t _asn_ctx;
  } nr_UE_RxTxTimeDiff_r16;
  struct NR_AdditionalPathList_r16* nr_AdditionalPathList_r16; /* OPTIONAL */
  NR_TimeStamp_r16_t nr_TimeStamp_r16;
  NR_TimingQuality_r16_t nr_TimingQuality_r16;
  long* nr_DL_PRS_RSRP_Result_r16; /* OPTIONAL */
  struct NR_Multi_RTT_AdditionalMeasurements_r16*
      nr_Multi_RTT_AdditionalMeasurements_r16; /* OPTIONAL */
  /*
   * This type is extensible,
   * possible extensions are below.
   */

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} NR_Multi_RTT_MeasElement_r16_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_NR_Multi_RTT_MeasElement_r16;
extern asn_SEQUENCE_specifics_t asn_SPC_NR_Multi_RTT_MeasElement_r16_specs_1;
extern asn_TYPE_member_t asn_MBR_NR_Multi_RTT_MeasElement_r16_1[12];

#ifdef __cplusplus
}
#endif

#endif /* _NR_Multi_RTT_MeasElement_r16_H_ */
#include <asn_internal.h>
