/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "LPP-PDU-Definitions"
 * 	found in "37355-g60.asn"
 * 	`asn1c -no-gen-OER -fcompound-names -no-gen-example -findirect-choice
 * -fno-include-deps -D lpp`
 */

#ifndef _ProvideCapabilities_H_
#define _ProvideCapabilities_H_

#include <asn_application.h>

/* Including external dependencies */
#include <NULL.h>
#include <constr_CHOICE.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ProvideCapabilities__criticalExtensions_PR {
  ProvideCapabilities__criticalExtensions_PR_NOTHING, /* No components present
                                                       */
  ProvideCapabilities__criticalExtensions_PR_c1,
  ProvideCapabilities__criticalExtensions_PR_criticalExtensionsFuture
} ProvideCapabilities__criticalExtensions_PR;
typedef enum ProvideCapabilities__criticalExtensions__c1_PR {
  ProvideCapabilities__criticalExtensions__c1_PR_NOTHING, /* No components
                                                             present */
  ProvideCapabilities__criticalExtensions__c1_PR_provideCapabilities_r9,
  ProvideCapabilities__criticalExtensions__c1_PR_spare3,
  ProvideCapabilities__criticalExtensions__c1_PR_spare2,
  ProvideCapabilities__criticalExtensions__c1_PR_spare1
} ProvideCapabilities__criticalExtensions__c1_PR;

/* Forward declarations */
struct ProvideCapabilities_r9_IEs;

/* ProvideCapabilities */
typedef struct ProvideCapabilities {
  struct ProvideCapabilities__criticalExtensions {
    ProvideCapabilities__criticalExtensions_PR present;
    union ProvideCapabilities__criticalExtensions_u {
      struct ProvideCapabilities__criticalExtensions__c1 {
        ProvideCapabilities__criticalExtensions__c1_PR present;
        union ProvideCapabilities__criticalExtensions__c1_u {
          struct ProvideCapabilities_r9_IEs* provideCapabilities_r9;
          NULL_t spare3;
          NULL_t spare2;
          NULL_t spare1;
        } choice;

        /* Context for parsing across buffer boundaries */
        asn_struct_ctx_t _asn_ctx;
      } * c1;
      struct ProvideCapabilities__criticalExtensions__criticalExtensionsFuture {
        /* Context for parsing across buffer boundaries */
        asn_struct_ctx_t _asn_ctx;
      } * criticalExtensionsFuture;
    } choice;

    /* Context for parsing across buffer boundaries */
    asn_struct_ctx_t _asn_ctx;
  } criticalExtensions;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} ProvideCapabilities_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ProvideCapabilities;
extern asn_SEQUENCE_specifics_t asn_SPC_ProvideCapabilities_specs_1;
extern asn_TYPE_member_t asn_MBR_ProvideCapabilities_1[1];

#ifdef __cplusplus
}
#endif

#endif /* _ProvideCapabilities_H_ */
#include <asn_internal.h>
