/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "LPP-Broadcast-Definitions"
 * 	found in "37355-g60.asn"
 * 	`asn1c -no-gen-OER -fcompound-names -no-gen-example -findirect-choice
 * -fno-include-deps -D lpp`
 */

#ifndef _SegmentationInfo_r15_H_
#define _SegmentationInfo_r15_H_

#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>
#include <NativeInteger.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum SegmentationInfo_r15__segmentationOption_r15 {
  SegmentationInfo_r15__segmentationOption_r15_pseudo_seg       = 0,
  SegmentationInfo_r15__segmentationOption_r15_octet_string_seg = 1
} e_SegmentationInfo_r15__segmentationOption_r15;
typedef enum SegmentationInfo_r15__assistanceDataSegmentType_r15 {
  SegmentationInfo_r15__assistanceDataSegmentType_r15_notLastSegment = 0,
  SegmentationInfo_r15__assistanceDataSegmentType_r15_lastSegment    = 1
} e_SegmentationInfo_r15__assistanceDataSegmentType_r15;

/* SegmentationInfo-r15 */
typedef struct SegmentationInfo_r15 {
  long segmentationOption_r15;
  long assistanceDataSegmentType_r15;
  long assistanceDataSegmentNumber_r15;
  /*
   * This type is extensible,
   * possible extensions are below.
   */

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} SegmentationInfo_r15_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_segmentationOption_r15_2;	// (Use
 * -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_assistanceDataSegmentType_r15_5;
 * // (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_SegmentationInfo_r15;
extern asn_SEQUENCE_specifics_t asn_SPC_SegmentationInfo_r15_specs_1;
extern asn_TYPE_member_t asn_MBR_SegmentationInfo_r15_1[3];

#ifdef __cplusplus
}
#endif

#endif /* _SegmentationInfo_r15_H_ */
#include <asn_internal.h>
