/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "LPP-PDU-Definitions"
 * 	found in "37355-g60.asn"
 * 	`asn1c -no-gen-OER -fcompound-names -no-gen-example -findirect-choice
 * -fno-include-deps -D lpp`
 */

#include "SRS-CapabilityPerBand-r16.h"

#include "OLPC-SRS-Pos-r16.h"
#include "SpatialRelationsSRS-Pos-r16.h"
asn_TYPE_member_t asn_MBR_SRS_CapabilityPerBand_r16_1[] = {
    {ATF_NOFLAGS,
     0,
     offsetof(struct SRS_CapabilityPerBand_r16, freqBandIndicatorNR_r16),
     (ASN_TAG_CLASS_CONTEXT | (0 << 2)),
     -1, /* IMPLICIT tag at current level */
     &asn_DEF_FreqBandIndicatorNR_r16,
     0,
     {0, 0, 0},
     0,
     0, /* No default value */
     "freqBandIndicatorNR-r16"},
    {ATF_POINTER,
     2,
     offsetof(struct SRS_CapabilityPerBand_r16, olpc_SRS_Pos_r16),
     (ASN_TAG_CLASS_CONTEXT | (1 << 2)),
     -1, /* IMPLICIT tag at current level */
     &asn_DEF_OLPC_SRS_Pos_r16,
     0,
     {0, 0, 0},
     0,
     0, /* No default value */
     "olpc-SRS-Pos-r16"},
    {ATF_POINTER,
     1,
     offsetof(struct SRS_CapabilityPerBand_r16, spatialRelationsSRS_Pos_r16),
     (ASN_TAG_CLASS_CONTEXT | (2 << 2)),
     -1, /* IMPLICIT tag at current level */
     &asn_DEF_SpatialRelationsSRS_Pos_r16,
     0,
     {0, 0, 0},
     0,
     0, /* No default value */
     "spatialRelationsSRS-Pos-r16"},
};
static const int asn_MAP_SRS_CapabilityPerBand_r16_oms_1[]            = {1, 2};
static const ber_tlv_tag_t asn_DEF_SRS_CapabilityPerBand_r16_tags_1[] = {
    (ASN_TAG_CLASS_UNIVERSAL | (16 << 2))};
static const asn_TYPE_tag2member_t
    asn_MAP_SRS_CapabilityPerBand_r16_tag2el_1[] = {
        {(ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0,
         0}, /* freqBandIndicatorNR-r16 */
        {(ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0}, /* olpc-SRS-Pos-r16 */
        {(ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0,
         0} /* spatialRelationsSRS-Pos-r16 */
};
asn_SEQUENCE_specifics_t asn_SPC_SRS_CapabilityPerBand_r16_specs_1 = {
    sizeof(struct SRS_CapabilityPerBand_r16),
    offsetof(struct SRS_CapabilityPerBand_r16, _asn_ctx),
    asn_MAP_SRS_CapabilityPerBand_r16_tag2el_1,
    3,                                       /* Count of tags in the map */
    asn_MAP_SRS_CapabilityPerBand_r16_oms_1, /* Optional members */
    2,
    0, /* Root/Additions */
    3, /* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_SRS_CapabilityPerBand_r16 = {
    "SRS-CapabilityPerBand-r16",
    "SRS-CapabilityPerBand-r16",
    &asn_OP_SEQUENCE,
    asn_DEF_SRS_CapabilityPerBand_r16_tags_1,
    sizeof(asn_DEF_SRS_CapabilityPerBand_r16_tags_1) /
        sizeof(asn_DEF_SRS_CapabilityPerBand_r16_tags_1[0]), /* 1 */
    asn_DEF_SRS_CapabilityPerBand_r16_tags_1,                /* Same as above */
    sizeof(asn_DEF_SRS_CapabilityPerBand_r16_tags_1) /
        sizeof(asn_DEF_SRS_CapabilityPerBand_r16_tags_1[0]), /* 1 */
    {0, 0, SEQUENCE_constraint},
    asn_MBR_SRS_CapabilityPerBand_r16_1,
    3,                                         /* Elements count */
    &asn_SPC_SRS_CapabilityPerBand_r16_specs_1 /* Additional specs */
};
