/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "LPP-PDU-Definitions"
 * 	found in "lpp.asn1"
 * 	`asn1c -gen-PER -fcompound-names -no-gen-example -findirect-choice
 * -fno-include-deps`
 */

#include "UTC-ModelSet2.h"

static int memb_utcA0_constraint_1(
    const asn_TYPE_descriptor_t* td, const void* sptr,
    asn_app_constraint_failed_f* ctfailcb, void* app_key) {
  long value;

  if (!sptr) {
    ASN__CTFAIL(
        app_key, td, sptr, "%s: value not given (%s:%d)", td->name, __FILE__,
        __LINE__);
    return -1;
  }

  value = *(const long*) sptr;

  if ((value >= -32768 && value <= 32767)) {
    /* Constraint check succeeded */
    return 0;
  } else {
    ASN__CTFAIL(
        app_key, td, sptr, "%s: constraint failed (%s:%d)", td->name, __FILE__,
        __LINE__);
    return -1;
  }
}

static int memb_utcA1_constraint_1(
    const asn_TYPE_descriptor_t* td, const void* sptr,
    asn_app_constraint_failed_f* ctfailcb, void* app_key) {
  long value;

  if (!sptr) {
    ASN__CTFAIL(
        app_key, td, sptr, "%s: value not given (%s:%d)", td->name, __FILE__,
        __LINE__);
    return -1;
  }

  value = *(const long*) sptr;

  if ((value >= -4096 && value <= 4095)) {
    /* Constraint check succeeded */
    return 0;
  } else {
    ASN__CTFAIL(
        app_key, td, sptr, "%s: constraint failed (%s:%d)", td->name, __FILE__,
        __LINE__);
    return -1;
  }
}

static int memb_utcA2_constraint_1(
    const asn_TYPE_descriptor_t* td, const void* sptr,
    asn_app_constraint_failed_f* ctfailcb, void* app_key) {
  long value;

  if (!sptr) {
    ASN__CTFAIL(
        app_key, td, sptr, "%s: value not given (%s:%d)", td->name, __FILE__,
        __LINE__);
    return -1;
  }

  value = *(const long*) sptr;

  if ((value >= -64 && value <= 63)) {
    /* Constraint check succeeded */
    return 0;
  } else {
    ASN__CTFAIL(
        app_key, td, sptr, "%s: constraint failed (%s:%d)", td->name, __FILE__,
        __LINE__);
    return -1;
  }
}

static int memb_utcDeltaTls_constraint_1(
    const asn_TYPE_descriptor_t* td, const void* sptr,
    asn_app_constraint_failed_f* ctfailcb, void* app_key) {
  long value;

  if (!sptr) {
    ASN__CTFAIL(
        app_key, td, sptr, "%s: value not given (%s:%d)", td->name, __FILE__,
        __LINE__);
    return -1;
  }

  value = *(const long*) sptr;

  if ((value >= -128 && value <= 127)) {
    /* Constraint check succeeded */
    return 0;
  } else {
    ASN__CTFAIL(
        app_key, td, sptr, "%s: constraint failed (%s:%d)", td->name, __FILE__,
        __LINE__);
    return -1;
  }
}

static int memb_utcTot_constraint_1(
    const asn_TYPE_descriptor_t* td, const void* sptr,
    asn_app_constraint_failed_f* ctfailcb, void* app_key) {
  long value;

  if (!sptr) {
    ASN__CTFAIL(
        app_key, td, sptr, "%s: value not given (%s:%d)", td->name, __FILE__,
        __LINE__);
    return -1;
  }

  value = *(const long*) sptr;

  if ((value >= 0 && value <= 65535)) {
    /* Constraint check succeeded */
    return 0;
  } else {
    ASN__CTFAIL(
        app_key, td, sptr, "%s: constraint failed (%s:%d)", td->name, __FILE__,
        __LINE__);
    return -1;
  }
}

static int memb_utcWNot_constraint_1(
    const asn_TYPE_descriptor_t* td, const void* sptr,
    asn_app_constraint_failed_f* ctfailcb, void* app_key) {
  long value;

  if (!sptr) {
    ASN__CTFAIL(
        app_key, td, sptr, "%s: value not given (%s:%d)", td->name, __FILE__,
        __LINE__);
    return -1;
  }

  value = *(const long*) sptr;

  if ((value >= 0 && value <= 8191)) {
    /* Constraint check succeeded */
    return 0;
  } else {
    ASN__CTFAIL(
        app_key, td, sptr, "%s: constraint failed (%s:%d)", td->name, __FILE__,
        __LINE__);
    return -1;
  }
}

static int memb_utcWNlsf_constraint_1(
    const asn_TYPE_descriptor_t* td, const void* sptr,
    asn_app_constraint_failed_f* ctfailcb, void* app_key) {
  long value;

  if (!sptr) {
    ASN__CTFAIL(
        app_key, td, sptr, "%s: value not given (%s:%d)", td->name, __FILE__,
        __LINE__);
    return -1;
  }

  value = *(const long*) sptr;

  if ((value >= 0 && value <= 255)) {
    /* Constraint check succeeded */
    return 0;
  } else {
    ASN__CTFAIL(
        app_key, td, sptr, "%s: constraint failed (%s:%d)", td->name, __FILE__,
        __LINE__);
    return -1;
  }
}

static int memb_utcDN_constraint_1(
    const asn_TYPE_descriptor_t* td, const void* sptr,
    asn_app_constraint_failed_f* ctfailcb, void* app_key) {
  const BIT_STRING_t* st = (const BIT_STRING_t*) sptr;
  size_t size;

  if (!sptr) {
    ASN__CTFAIL(
        app_key, td, sptr, "%s: value not given (%s:%d)", td->name, __FILE__,
        __LINE__);
    return -1;
  }

  if (st->size > 0) {
    /* Size in bits */
    size = 8 * st->size - (st->bits_unused & 0x07);
  } else {
    size = 0;
  }

  if ((size == 4)) {
    /* Constraint check succeeded */
    return 0;
  } else {
    ASN__CTFAIL(
        app_key, td, sptr, "%s: constraint failed (%s:%d)", td->name, __FILE__,
        __LINE__);
    return -1;
  }
}

static int memb_utcDeltaTlsf_constraint_1(
    const asn_TYPE_descriptor_t* td, const void* sptr,
    asn_app_constraint_failed_f* ctfailcb, void* app_key) {
  long value;

  if (!sptr) {
    ASN__CTFAIL(
        app_key, td, sptr, "%s: value not given (%s:%d)", td->name, __FILE__,
        __LINE__);
    return -1;
  }

  value = *(const long*) sptr;

  if ((value >= -128 && value <= 127)) {
    /* Constraint check succeeded */
    return 0;
  } else {
    ASN__CTFAIL(
        app_key, td, sptr, "%s: constraint failed (%s:%d)", td->name, __FILE__,
        __LINE__);
    return -1;
  }
}

static asn_oer_constraints_t asn_OER_memb_utcA0_constr_2 CC_NOTUSED = {
    {2, 0} /* (-32768..32767) */,
    -1};
static asn_per_constraints_t asn_PER_memb_utcA0_constr_2 CC_NOTUSED = {
    {APC_CONSTRAINED, 16, 16, -32768, 32767} /* (-32768..32767) */,
    {APC_UNCONSTRAINED, -1, -1, 0, 0},
    0,
    0 /* No PER value map */
};
static asn_oer_constraints_t asn_OER_memb_utcA1_constr_3 CC_NOTUSED = {
    {2, 0} /* (-4096..4095) */,
    -1};
static asn_per_constraints_t asn_PER_memb_utcA1_constr_3 CC_NOTUSED = {
    {APC_CONSTRAINED, 13, 13, -4096, 4095} /* (-4096..4095) */,
    {APC_UNCONSTRAINED, -1, -1, 0, 0},
    0,
    0 /* No PER value map */
};
static asn_oer_constraints_t asn_OER_memb_utcA2_constr_4 CC_NOTUSED = {
    {1, 0} /* (-64..63) */,
    -1};
static asn_per_constraints_t asn_PER_memb_utcA2_constr_4 CC_NOTUSED = {
    {APC_CONSTRAINED, 7, 7, -64, 63} /* (-64..63) */,
    {APC_UNCONSTRAINED, -1, -1, 0, 0},
    0,
    0 /* No PER value map */
};
static asn_oer_constraints_t asn_OER_memb_utcDeltaTls_constr_5 CC_NOTUSED = {
    {1, 0} /* (-128..127) */,
    -1};
static asn_per_constraints_t asn_PER_memb_utcDeltaTls_constr_5 CC_NOTUSED = {
    {APC_CONSTRAINED, 8, 8, -128, 127} /* (-128..127) */,
    {APC_UNCONSTRAINED, -1, -1, 0, 0},
    0,
    0 /* No PER value map */
};
static asn_oer_constraints_t asn_OER_memb_utcTot_constr_6 CC_NOTUSED = {
    {2, 1} /* (0..65535) */,
    -1};
static asn_per_constraints_t asn_PER_memb_utcTot_constr_6 CC_NOTUSED = {
    {APC_CONSTRAINED, 16, 16, 0, 65535} /* (0..65535) */,
    {APC_UNCONSTRAINED, -1, -1, 0, 0},
    0,
    0 /* No PER value map */
};
static asn_oer_constraints_t asn_OER_memb_utcWNot_constr_7 CC_NOTUSED = {
    {2, 1} /* (0..8191) */,
    -1};
static asn_per_constraints_t asn_PER_memb_utcWNot_constr_7 CC_NOTUSED = {
    {APC_CONSTRAINED, 13, 13, 0, 8191} /* (0..8191) */,
    {APC_UNCONSTRAINED, -1, -1, 0, 0},
    0,
    0 /* No PER value map */
};
static asn_oer_constraints_t asn_OER_memb_utcWNlsf_constr_8 CC_NOTUSED = {
    {1, 1} /* (0..255) */,
    -1};
static asn_per_constraints_t asn_PER_memb_utcWNlsf_constr_8 CC_NOTUSED = {
    {APC_CONSTRAINED, 8, 8, 0, 255} /* (0..255) */,
    {APC_UNCONSTRAINED, -1, -1, 0, 0},
    0,
    0 /* No PER value map */
};
static asn_oer_constraints_t asn_OER_memb_utcDN_constr_9 CC_NOTUSED = {
    {0, 0},
    4 /* (SIZE(4..4)) */};
static asn_per_constraints_t asn_PER_memb_utcDN_constr_9 CC_NOTUSED = {
    {APC_UNCONSTRAINED, -1, -1, 0, 0},
    {APC_CONSTRAINED, 0, 0, 4, 4} /* (SIZE(4..4)) */,
    0,
    0 /* No PER value map */
};
static asn_oer_constraints_t asn_OER_memb_utcDeltaTlsf_constr_10 CC_NOTUSED = {
    {1, 0} /* (-128..127) */,
    -1};
static asn_per_constraints_t asn_PER_memb_utcDeltaTlsf_constr_10 CC_NOTUSED = {
    {APC_CONSTRAINED, 8, 8, -128, 127} /* (-128..127) */,
    {APC_UNCONSTRAINED, -1, -1, 0, 0},
    0,
    0 /* No PER value map */
};
asn_TYPE_member_t asn_MBR_UTC_ModelSet2_1[] = {
    {ATF_NOFLAGS,
     0,
     offsetof(struct UTC_ModelSet2, utcA0),
     (ASN_TAG_CLASS_CONTEXT | (0 << 2)),
     -1, /* IMPLICIT tag at current level */
     &asn_DEF_NativeInteger,
     0,
     {&asn_OER_memb_utcA0_constr_2, &asn_PER_memb_utcA0_constr_2,
      memb_utcA0_constraint_1},
     0,
     0, /* No default value */
     "utcA0"},
    {ATF_NOFLAGS,
     0,
     offsetof(struct UTC_ModelSet2, utcA1),
     (ASN_TAG_CLASS_CONTEXT | (1 << 2)),
     -1, /* IMPLICIT tag at current level */
     &asn_DEF_NativeInteger,
     0,
     {&asn_OER_memb_utcA1_constr_3, &asn_PER_memb_utcA1_constr_3,
      memb_utcA1_constraint_1},
     0,
     0, /* No default value */
     "utcA1"},
    {ATF_NOFLAGS,
     0,
     offsetof(struct UTC_ModelSet2, utcA2),
     (ASN_TAG_CLASS_CONTEXT | (2 << 2)),
     -1, /* IMPLICIT tag at current level */
     &asn_DEF_NativeInteger,
     0,
     {&asn_OER_memb_utcA2_constr_4, &asn_PER_memb_utcA2_constr_4,
      memb_utcA2_constraint_1},
     0,
     0, /* No default value */
     "utcA2"},
    {ATF_NOFLAGS,
     0,
     offsetof(struct UTC_ModelSet2, utcDeltaTls),
     (ASN_TAG_CLASS_CONTEXT | (3 << 2)),
     -1, /* IMPLICIT tag at current level */
     &asn_DEF_NativeInteger,
     0,
     {&asn_OER_memb_utcDeltaTls_constr_5, &asn_PER_memb_utcDeltaTls_constr_5,
      memb_utcDeltaTls_constraint_1},
     0,
     0, /* No default value */
     "utcDeltaTls"},
    {ATF_NOFLAGS,
     0,
     offsetof(struct UTC_ModelSet2, utcTot),
     (ASN_TAG_CLASS_CONTEXT | (4 << 2)),
     -1, /* IMPLICIT tag at current level */
     &asn_DEF_NativeInteger,
     0,
     {&asn_OER_memb_utcTot_constr_6, &asn_PER_memb_utcTot_constr_6,
      memb_utcTot_constraint_1},
     0,
     0, /* No default value */
     "utcTot"},
    {ATF_NOFLAGS,
     0,
     offsetof(struct UTC_ModelSet2, utcWNot),
     (ASN_TAG_CLASS_CONTEXT | (5 << 2)),
     -1, /* IMPLICIT tag at current level */
     &asn_DEF_NativeInteger,
     0,
     {&asn_OER_memb_utcWNot_constr_7, &asn_PER_memb_utcWNot_constr_7,
      memb_utcWNot_constraint_1},
     0,
     0, /* No default value */
     "utcWNot"},
    {ATF_NOFLAGS,
     0,
     offsetof(struct UTC_ModelSet2, utcWNlsf),
     (ASN_TAG_CLASS_CONTEXT | (6 << 2)),
     -1, /* IMPLICIT tag at current level */
     &asn_DEF_NativeInteger,
     0,
     {&asn_OER_memb_utcWNlsf_constr_8, &asn_PER_memb_utcWNlsf_constr_8,
      memb_utcWNlsf_constraint_1},
     0,
     0, /* No default value */
     "utcWNlsf"},
    {ATF_NOFLAGS,
     0,
     offsetof(struct UTC_ModelSet2, utcDN),
     (ASN_TAG_CLASS_CONTEXT | (7 << 2)),
     -1, /* IMPLICIT tag at current level */
     &asn_DEF_BIT_STRING,
     0,
     {&asn_OER_memb_utcDN_constr_9, &asn_PER_memb_utcDN_constr_9,
      memb_utcDN_constraint_1},
     0,
     0, /* No default value */
     "utcDN"},
    {ATF_NOFLAGS,
     0,
     offsetof(struct UTC_ModelSet2, utcDeltaTlsf),
     (ASN_TAG_CLASS_CONTEXT | (8 << 2)),
     -1, /* IMPLICIT tag at current level */
     &asn_DEF_NativeInteger,
     0,
     {&asn_OER_memb_utcDeltaTlsf_constr_10,
      &asn_PER_memb_utcDeltaTlsf_constr_10, memb_utcDeltaTlsf_constraint_1},
     0,
     0, /* No default value */
     "utcDeltaTlsf"},
};
static const ber_tlv_tag_t asn_DEF_UTC_ModelSet2_tags_1[] = {
    (ASN_TAG_CLASS_UNIVERSAL | (16 << 2))};
static const asn_TYPE_tag2member_t asn_MAP_UTC_ModelSet2_tag2el_1[] = {
    {(ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0}, /* utcA0 */
    {(ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0}, /* utcA1 */
    {(ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0}, /* utcA2 */
    {(ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0}, /* utcDeltaTls */
    {(ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0}, /* utcTot */
    {(ASN_TAG_CLASS_CONTEXT | (5 << 2)), 5, 0, 0}, /* utcWNot */
    {(ASN_TAG_CLASS_CONTEXT | (6 << 2)), 6, 0, 0}, /* utcWNlsf */
    {(ASN_TAG_CLASS_CONTEXT | (7 << 2)), 7, 0, 0}, /* utcDN */
    {(ASN_TAG_CLASS_CONTEXT | (8 << 2)), 8, 0, 0}  /* utcDeltaTlsf */
};
asn_SEQUENCE_specifics_t asn_SPC_UTC_ModelSet2_specs_1 = {
    sizeof(struct UTC_ModelSet2),
    offsetof(struct UTC_ModelSet2, _asn_ctx),
    asn_MAP_UTC_ModelSet2_tag2el_1,
    9, /* Count of tags in the map */
    0,
    0,
    0, /* Optional elements (not needed) */
    9, /* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_UTC_ModelSet2 = {
    "UTC-ModelSet2",
    "UTC-ModelSet2",
    &asn_OP_SEQUENCE,
    asn_DEF_UTC_ModelSet2_tags_1,
    sizeof(asn_DEF_UTC_ModelSet2_tags_1) /
        sizeof(asn_DEF_UTC_ModelSet2_tags_1[0]), /* 1 */
    asn_DEF_UTC_ModelSet2_tags_1,                /* Same as above */
    sizeof(asn_DEF_UTC_ModelSet2_tags_1) /
        sizeof(asn_DEF_UTC_ModelSet2_tags_1[0]), /* 1 */
    {0, 0, SEQUENCE_constraint},
    asn_MBR_UTC_ModelSet2_1,
    9,                             /* Elements count */
    &asn_SPC_UTC_ModelSet2_specs_1 /* Additional specs */
};
