/**
 * LMF Broadcast
 * LMF Broadcast Service. © 2021, 3GPP Organizational Partners (ARIB, ATIS,
 * CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 1.0.3
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

#include "RequestCipheringKeyDataApi.h"
#include "Helpers.h"
#include "logger.hpp"
#include <iostream>

using namespace std;

namespace oai {
namespace lmf_server {
namespace api {

using namespace oai::lmf_server::helpers;
using namespace oai::lmf_server::model;

const std::string RequestCipheringKeyDataApi::base = "/nlmf-broadcast/v1";

RequestCipheringKeyDataApi::RequestCipheringKeyDataApi(
    std::shared_ptr<Pistache::Rest::Router> rtr) {
  router = rtr;
}

void RequestCipheringKeyDataApi::init() { setupRoutes(); }

void RequestCipheringKeyDataApi::setupRoutes() {
  using namespace Pistache::Rest;

  Routes::Post(
      *router, base + "/cipher-key-data",
      Routes::bind(&RequestCipheringKeyDataApi::ciphering_key_data_handler,
                   this));

  // Default handler, called when a route is not found
  router->addCustomHandler(
      Routes::bind(&RequestCipheringKeyDataApi::
                       request_ciphering_key_data_api_default_handler,
                   this));
}

std::pair<Pistache::Http::Code, std::string>
RequestCipheringKeyDataApi::handleParsingException(
    const std::exception &ex) const noexcept {
  try {
    throw;
  } catch (nlohmann::detail::exception &e) {
    return std::make_pair(Pistache::Http::Code::Bad_Request, e.what());
  } catch (oai::lmf_server::helpers::ValidationException &e) {
    return std::make_pair(Pistache::Http::Code::Bad_Request, e.what());
  } catch (std::exception &e) {
    return std::make_pair(Pistache::Http::Code::Internal_Server_Error,
                          e.what());
  }
}

std::pair<Pistache::Http::Code, std::string>
RequestCipheringKeyDataApi::handleOperationException(
    const std::exception &ex) const noexcept {
  return std::make_pair(Pistache::Http::Code::Internal_Server_Error, ex.what());
}

void RequestCipheringKeyDataApi::ciphering_key_data_handler(
    const Pistache::Rest::Request &request,
    Pistache::Http::ResponseWriter response) {
  try {
    // Getting the body param

    // CipherRequestData cipherRequestData;

    try {
      // nlohmann::json::parse(request.body()).get_to(cipherRequestData);
      // cipherRequestData.validate();
    } catch (std::exception &e) {
      const std::pair<Pistache::Http::Code, std::string> errorInfo =
          this->handleParsingException(e);
      response.send(errorInfo.first, errorInfo.second);
      return;
    }

    try {
      // this->ciphering_key_data(cipherRequestData, response);
    } catch (Pistache::Http::HttpError &e) {
      response.send(static_cast<Pistache::Http::Code>(e.code()), e.what());
      return;
    } catch (std::exception &e) {
      const std::pair<Pistache::Http::Code, std::string> errorInfo =
          this->handleOperationException(e);
      response.send(errorInfo.first, errorInfo.second);
      return;
    }

  } catch (std::exception &e) {
    response.send(Pistache::Http::Code::Internal_Server_Error, e.what());
  }
}

void RequestCipheringKeyDataApi::request_ciphering_key_data_api_default_handler(
    const Pistache::Rest::Request &, Pistache::Http::ResponseWriter response) {
  response.send(Pistache::Http::Code::Not_Found,
                "The requested method does not exist");
}

} // namespace api
} // namespace lmf_server
} // namespace oai
