/**
 * LMF Broadcast
 * LMF Broadcast Service. © 2021, 3GPP Organizational Partners (ARIB, ATIS,
 * CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 1.0.3
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

#include "CipherResponseData.h"
#include "Helpers.h"

#include <sstream>

namespace oai {
namespace lmf_server {
namespace model {

CipherResponseData::CipherResponseData() {}

void CipherResponseData::validate() const {
  std::stringstream msg;
  if (!validate(msg)) {
    throw oai::lmf_server::helpers::ValidationException(msg.str());
  }
}

bool CipherResponseData::validate(std::stringstream &msg) const {
  return validate(msg, "");
}

bool CipherResponseData::validate(std::stringstream &msg,
                                  const std::string &pathPrefix) const {
  bool success = true;
  const std::string _pathPrefix =
      pathPrefix.empty() ? "CipherResponseData" : pathPrefix;

  return success;
}

bool CipherResponseData::operator==(const CipherResponseData &rhs) const {
  return

      (getDataAvailability() == rhs.getDataAvailability())

          ;
}

bool CipherResponseData::operator!=(const CipherResponseData &rhs) const {
  return !(*this == rhs);
}

void to_json(nlohmann::json &j, const CipherResponseData &o) {
  j = nlohmann::json();
  j["dataAvailability"] = o.m_DataAvailability;
}

void from_json(const nlohmann::json &j, CipherResponseData &o) {
  j.at("dataAvailability").get_to(o.m_DataAvailability);
}

DataAvailability CipherResponseData::getDataAvailability() const {
  return m_DataAvailability;
}
void CipherResponseData::setDataAvailability(DataAvailability const &value) {
  m_DataAvailability = value;
}

} // namespace model
} // namespace lmf_server
} // namespace oai
