/**
* Common Data Types
* Common Data Types for Service Based Interfaces. © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
*
* The version of the OpenAPI document: 1.2.7
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#include "DnaiChangeTypeRm.h"
#include "Helpers.h"

#include <sstream>

namespace oai::lmf_server::model
{

DnaiChangeTypeRm::DnaiChangeTypeRm()
{
    
}

void DnaiChangeTypeRm::validate() const
{
    std::stringstream msg;
    if (!validate(msg))
    {
        throw org::openapitools::server::helpers::ValidationException(msg.str());
    }
}

bool DnaiChangeTypeRm::validate(std::stringstream& msg) const
{
    return validate(msg, "");
}

bool DnaiChangeTypeRm::validate(std::stringstream& msg, const std::string& pathPrefix) const
{
    bool success = true;
    const std::string _pathPrefix = pathPrefix.empty() ? "DnaiChangeTypeRm" : pathPrefix;

    
    return success;
}

bool DnaiChangeTypeRm::operator==(const DnaiChangeTypeRm& rhs) const
{
    return *this == rhs;
}

bool DnaiChangeTypeRm::operator!=(const DnaiChangeTypeRm& rhs) const
{
    return !(*this == rhs);
}

void to_json(nlohmann::json& j, const DnaiChangeTypeRm& o)
{
    j = nlohmann::json();
    
}

void from_json(const nlohmann::json& j, DnaiChangeTypeRm& o)
{
    
}



} // namespace oai::lmf_server::model

