/**
 * LMF Location
 * LMF Location Service. © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA,
 * ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 1.1.5
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */
/*
 * InputData.h
 *
 *
 */

#ifndef InputData_H_
#define InputData_H_

#include "AreaEventInfo.h"
#include "Ecgi.h"
#include "ExternalClientType.h"
#include "LcsPriority.h"
#include "LdrType.h"
#include "LocationQoS.h"
#include "MotionEventInfo.h"
#include "Ncgi.h"
#include "PeriodicEventInfo.h"
#include "RefToBinaryData.h"
#include "ReportingAccessType.h"
#include "SupportedGADShapes.h"
#include "UeConnectivityState.h"
#include "UeLcsCapability.h"
#include "UeLocationServiceInd.h"
#include "VelocityRequested.h"
#include <nlohmann/json.hpp>
#include <string>
#include <vector>

namespace oai {
namespace lmf_server {
namespace model {

/// <summary>
///
/// </summary>
class InputData {
public:
  InputData();
  virtual ~InputData() = default;

  /// <summary>
  /// Validate the current data in the model. Throws a ValidationException on
  /// failure.
  /// </summary>
  void validate() const;

  /// <summary>
  /// Validate the current data in the model. Returns false on error and writes
  /// an error message into the given stringstream.
  /// </summary>
  bool validate(std::stringstream &msg) const;

  /// <summary>
  /// Helper overload for validate. Used when one model stores another model and
  /// calls it's validate. Not meant to be called outside that case.
  /// </summary>
  bool validate(std::stringstream &msg, const std::string &pathPrefix) const;

  bool operator==(const InputData &rhs) const;
  bool operator!=(const InputData &rhs) const;

  /////////////////////////////////////////////
  /// InputData members

  /// <summary>
  ///
  /// </summary>
  ExternalClientType getExternalClientType() const;
  void setExternalClientType(ExternalClientType const &value);
  bool externalClientTypeIsSet() const;
  void unsetExternalClientType();
  /// <summary>
  ///
  /// </summary>
  std::string getCorrelationID() const;
  void setCorrelationID(std::string const &value);
  bool correlationIDIsSet() const;
  void unsetCorrelationID();
  /// <summary>
  ///
  /// </summary>
  std::string getAmfId() const;
  void setAmfId(std::string const &value);
  bool amfIdIsSet() const;
  void unsetAmfId();
  /// <summary>
  ///
  /// </summary>
  LocationQoS getLocationQoS() const;
  void setLocationQoS(LocationQoS const &value);
  bool locationQoSIsSet() const;
  void unsetLocationQoS();
  /// <summary>
  ///
  /// </summary>
  std::vector<SupportedGADShapes> getSupportedGADShapes() const;
  void setSupportedGADShapes(std::vector<SupportedGADShapes> const &value);
  bool supportedGADShapesIsSet() const;
  void unsetSupportedGADShapes();
  /// <summary>
  ///
  /// </summary>
  std::string getSupi() const;
  void setSupi(std::string const &value);
  bool supiIsSet() const;
  void unsetSupi();
  /// <summary>
  ///
  /// </summary>
  std::string getPei() const;
  void setPei(std::string const &value);
  bool peiIsSet() const;
  void unsetPei();
  /// <summary>
  ///
  /// </summary>
  std::string getGpsi() const;
  void setGpsi(std::string const &value);
  bool gpsiIsSet() const;
  void unsetGpsi();
  /// <summary>
  ///
  /// </summary>
  Ecgi getEcgi() const;
  void setEcgi(Ecgi const &value);
  bool ecgiIsSet() const;
  void unsetEcgi();
  /// <summary>
  ///
  /// </summary>
  Ecgi getEcgiOnSecondNode() const;
  void setEcgiOnSecondNode(Ecgi const &value);
  bool ecgiOnSecondNodeIsSet() const;
  void unsetEcgiOnSecondNode();
  /// <summary>
  ///
  /// </summary>
  Ncgi getNcgi() const;
  void setNcgi(Ncgi const &value);
  bool ncgiIsSet() const;
  void unsetNcgi();
  /// <summary>
  ///
  /// </summary>
  Ncgi getNcgiOnSecondNode() const;
  void setNcgiOnSecondNode(Ncgi const &value);
  bool ncgiOnSecondNodeIsSet() const;
  void unsetNcgiOnSecondNode();
  /// <summary>
  ///
  /// </summary>
  LcsPriority getPriority() const;
  void setPriority(LcsPriority const &value);
  bool priorityIsSet() const;
  void unsetPriority();
  /// <summary>
  ///
  /// </summary>
  VelocityRequested getVelocityRequested() const;
  void setVelocityRequested(VelocityRequested const &value);
  bool velocityRequestedIsSet() const;
  void unsetVelocityRequested();
  /// <summary>
  ///
  /// </summary>
  UeLcsCapability getUeLcsCap() const;
  void setUeLcsCap(UeLcsCapability const &value);
  bool ueLcsCapIsSet() const;
  void unsetUeLcsCap();
  /// <summary>
  ///
  /// </summary>
  int32_t getLcsServiceType() const;
  void setLcsServiceType(int32_t const value);
  bool lcsServiceTypeIsSet() const;
  void unsetLcsServiceType();
  /// <summary>
  ///
  /// </summary>
  LdrType getLdrType() const;
  void setLdrType(LdrType const &value);
  bool ldrTypeIsSet() const;
  void unsetLdrType();
  /// <summary>
  ///
  /// </summary>
  std::string getHgmlcCallBackURI() const;
  void setHgmlcCallBackURI(std::string const &value);
  bool hgmlcCallBackURIIsSet() const;
  void unsetHgmlcCallBackURI();
  /// <summary>
  ///
  /// </summary>
  std::string getVgmlcAddress() const;
  void setVgmlcAddress(std::string const &value);
  bool vgmlcAddressIsSet() const;
  void unsetVgmlcAddress();
  /// <summary>
  ///
  /// </summary>
  std::string getLdrReference() const;
  void setLdrReference(std::string const &value);
  bool ldrReferenceIsSet() const;
  void unsetLdrReference();
  /// <summary>
  ///
  /// </summary>
  PeriodicEventInfo getPeriodicEventInfo() const;
  void setPeriodicEventInfo(PeriodicEventInfo const &value);
  bool periodicEventInfoIsSet() const;
  void unsetPeriodicEventInfo();
  /// <summary>
  ///
  /// </summary>
  AreaEventInfo getAreaEventInfo() const;
  void setAreaEventInfo(AreaEventInfo const &value);
  bool areaEventInfoIsSet() const;
  void unsetAreaEventInfo();
  /// <summary>
  ///
  /// </summary>
  MotionEventInfo getMotionEventInfo() const;
  void setMotionEventInfo(MotionEventInfo const &value);
  bool motionEventInfoIsSet() const;
  void unsetMotionEventInfo();
  /// <summary>
  ///
  /// </summary>
  std::vector<ReportingAccessType> getReportingAccessTypes() const;
  void setReportingAccessTypes(std::vector<ReportingAccessType> const &value);
  bool reportingAccessTypesIsSet() const;
  void unsetReportingAccessTypes();
  /// <summary>
  ///
  /// </summary>
  UeConnectivityState getUeConnectivityStates() const;
  void setUeConnectivityStates(UeConnectivityState const &value);
  bool ueConnectivityStatesIsSet() const;
  void unsetUeConnectivityStates();
  /// <summary>
  ///
  /// </summary>
  UeLocationServiceInd getUeLocationServiceInd() const;
  void setUeLocationServiceInd(UeLocationServiceInd const &value);
  bool ueLocationServiceIndIsSet() const;
  void unsetUeLocationServiceInd();
  /// <summary>
  ///
  /// </summary>
  RefToBinaryData getLppMessage() const;
  void setLppMessage(RefToBinaryData const &value);
  bool lppMessageIsSet() const;
  void unsetLppMessage();
  /// <summary>
  ///
  /// </summary>
  std::string getSupportedFeatures() const;
  void setSupportedFeatures(std::string const &value);
  bool supportedFeaturesIsSet() const;
  void unsetSupportedFeatures();

  friend void to_json(nlohmann::json &j, const InputData &o);
  friend void from_json(const nlohmann::json &j, InputData &o);

protected:
  ExternalClientType m_ExternalClientType;
  bool m_ExternalClientTypeIsSet;
  std::string m_CorrelationID;
  bool m_CorrelationIDIsSet;
  std::string m_AmfId;
  bool m_AmfIdIsSet;
  LocationQoS m_LocationQoS;
  bool m_LocationQoSIsSet;
  std::vector<SupportedGADShapes> m_SupportedGADShapes;
  bool m_SupportedGADShapesIsSet;
  std::string m_Supi;
  bool m_SupiIsSet;
  std::string m_Pei;
  bool m_PeiIsSet;
  std::string m_Gpsi;
  bool m_GpsiIsSet;
  Ecgi m_Ecgi;
  bool m_EcgiIsSet;
  Ecgi m_EcgiOnSecondNode;
  bool m_EcgiOnSecondNodeIsSet;
  Ncgi m_Ncgi;
  bool m_NcgiIsSet;
  Ncgi m_NcgiOnSecondNode;
  bool m_NcgiOnSecondNodeIsSet;
  LcsPriority m_Priority;
  bool m_PriorityIsSet;
  VelocityRequested m_VelocityRequested;
  bool m_VelocityRequestedIsSet;
  UeLcsCapability m_UeLcsCap;
  bool m_UeLcsCapIsSet;
  int32_t m_LcsServiceType;
  bool m_LcsServiceTypeIsSet;
  LdrType m_LdrType;
  bool m_LdrTypeIsSet;
  std::string m_HgmlcCallBackURI;
  bool m_HgmlcCallBackURIIsSet;
  std::string m_VgmlcAddress;
  bool m_VgmlcAddressIsSet;
  std::string m_LdrReference;
  bool m_LdrReferenceIsSet;
  PeriodicEventInfo m_PeriodicEventInfo;
  bool m_PeriodicEventInfoIsSet;
  AreaEventInfo m_AreaEventInfo;
  bool m_AreaEventInfoIsSet;
  MotionEventInfo m_MotionEventInfo;
  bool m_MotionEventInfoIsSet;
  std::vector<ReportingAccessType> m_ReportingAccessTypes;
  bool m_ReportingAccessTypesIsSet;
  UeConnectivityState m_UeConnectivityStates;
  bool m_UeConnectivityStatesIsSet;
  UeLocationServiceInd m_UeLocationServiceInd;
  bool m_UeLocationServiceIndIsSet;
  RefToBinaryData m_LppMessage;
  bool m_LppMessageIsSet;
  std::string m_SupportedFeatures;
  bool m_SupportedFeaturesIsSet;
};

} // namespace model
} // namespace lmf_server
} // namespace oai

#endif /* InputData_H_ */
