/**
* LMF Location
* LMF Location Service. © 2019, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
*
* The version of the OpenAPI document: 1.0.4
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * InputData.h
 *
 * 
 */

#ifndef InputData_H_
#define InputData_H_


#include "LcsPriority.h"
#include "Ecgi.h"
#include "Ncgi.h"
#include "UeLcsCapability.h"
#include <string>
#include "ExternalClientType.h"
#include "LocationQoS.h"
#include "VelocityRequested.h"
#include <vector>
#include "SupportedGADShapes.h"
#include <nlohmann/json.hpp>

namespace oai::lmf_server::model
{

/// <summary>
/// 
/// </summary>
class  InputData
{
public:
    InputData();
    virtual ~InputData() = default;


    /// <summary>
    /// Validate the current data in the model. Throws a ValidationException on failure.
    /// </summary>
    void validate() const;

    /// <summary>
    /// Validate the current data in the model. Returns false on error and writes an error
    /// message into the given stringstream.
    /// </summary>
    bool validate(std::stringstream& msg) const;

    /// <summary>
    /// Helper overload for validate. Used when one model stores another model and calls it's validate.
    /// Not meant to be called outside that case.
    /// </summary>
    bool validate(std::stringstream& msg, const std::string& pathPrefix) const;

    bool operator==(const InputData& rhs) const;
    bool operator!=(const InputData& rhs) const;

    /////////////////////////////////////////////
    /// InputData members

    /// <summary>
    /// 
    /// </summary>
    ExternalClientType getExternalClientType() const;
    void setExternalClientType(ExternalClientType const& value);
    bool externalClientTypeIsSet() const;
    void unsetExternalClientType();
    /// <summary>
    /// 
    /// </summary>
    std::string getCorrelationID() const;
    void setCorrelationID(std::string const& value);
    bool correlationIDIsSet() const;
    void unsetCorrelationID();
    /// <summary>
    /// 
    /// </summary>
    std::string getAmfId() const;
    void setAmfId(std::string const& value);
    bool amfIdIsSet() const;
    void unsetAmfId();
    /// <summary>
    /// 
    /// </summary>
    LocationQoS getLocationQoS() const;
    void setLocationQoS(LocationQoS const& value);
    bool locationQoSIsSet() const;
    void unsetLocationQoS();
    /// <summary>
    /// 
    /// </summary>
    std::vector<SupportedGADShapes> getSupportedGADShapes() const;
    void setSupportedGADShapes(std::vector<SupportedGADShapes> const& value);
    bool supportedGADShapesIsSet() const;
    void unsetSupportedGADShapes();
    /// <summary>
    /// 
    /// </summary>
    std::string getSupi() const;
    void setSupi(std::string const& value);
    bool supiIsSet() const;
    void unsetSupi();
    /// <summary>
    /// 
    /// </summary>
    std::string getPei() const;
    void setPei(std::string const& value);
    bool peiIsSet() const;
    void unsetPei();
    /// <summary>
    /// 
    /// </summary>
    std::string getGpsi() const;
    void setGpsi(std::string const& value);
    bool gpsiIsSet() const;
    void unsetGpsi();
    /// <summary>
    /// 
    /// </summary>
    Ecgi getEcgi() const;
    void setEcgi(Ecgi const& value);
    bool ecgiIsSet() const;
    void unsetEcgi();
    /// <summary>
    /// 
    /// </summary>
    Ncgi getNcgi() const;
    void setNcgi(Ncgi const& value);
    bool ncgiIsSet() const;
    void unsetNcgi();
    /// <summary>
    /// 
    /// </summary>
    LcsPriority getPriority() const;
    void setPriority(LcsPriority const& value);
    bool priorityIsSet() const;
    void unsetPriority();
    /// <summary>
    /// 
    /// </summary>
    VelocityRequested getVelocityRequested() const;
    void setVelocityRequested(VelocityRequested const& value);
    bool velocityRequestedIsSet() const;
    void unsetVelocityRequested();
    /// <summary>
    /// 
    /// </summary>
    UeLcsCapability getUeLcsCap() const;
    void setUeLcsCap(UeLcsCapability const& value);
    bool ueLcsCapIsSet() const;
    void unsetUeLcsCap();

    friend void to_json(nlohmann::json& j, const InputData& o);
    friend void from_json(const nlohmann::json& j, InputData& o);
protected:
    ExternalClientType m_ExternalClientType;
    bool m_ExternalClientTypeIsSet;
    std::string m_CorrelationID;
    bool m_CorrelationIDIsSet;
    std::string m_AmfId;
    bool m_AmfIdIsSet;
    LocationQoS m_LocationQoS;
    bool m_LocationQoSIsSet;
    std::vector<SupportedGADShapes> m_SupportedGADShapes;
    bool m_SupportedGADShapesIsSet;
    std::string m_Supi;
    bool m_SupiIsSet;
    std::string m_Pei;
    bool m_PeiIsSet;
    std::string m_Gpsi;
    bool m_GpsiIsSet;
    Ecgi m_Ecgi;
    bool m_EcgiIsSet;
    Ncgi m_Ncgi;
    bool m_NcgiIsSet;
    LcsPriority m_Priority;
    bool m_PriorityIsSet;
    VelocityRequested m_VelocityRequested;
    bool m_VelocityRequestedIsSet;
    UeLcsCapability m_UeLcsCap;
    bool m_UeLcsCapIsSet;
    
};

} // namespace oai::lmf_server::model

#endif /* InputData_H_ */
