/**
 * LMF Location
 * LMF Location Service. © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA,
 * ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 1.1.5
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */
/*
 * InputData.h
 *
 *
 */

#ifndef InputData_H_
#define InputData_H_

#include "LcsPriority.h"
#include "AreaEventInfo.h"
#include "Ncgi.h"
#include "UeConnectivityState.h"
#include "RefToBinaryData.h"
#include <string>
#include "ExternalClientType.h"
#include "PeriodicEventInfo.h"
#include "ReportingAccessType.h"
#include "UeLocationServiceInd.h"
#include <vector>
#include "Ecgi.h"
#include "LdrType.h"
#include "UeLcsCapability.h"
#include "LocationQoS.h"
#include "VelocityRequested.h"
#include "MotionEventInfo.h"
#include "SupportedGADShapes.h"
#include <nlohmann/json.hpp>

namespace oai::lmf_server::model {

/// <summary>
///
/// </summary>
class InputData {
 public:
  InputData();
  virtual ~InputData() = default;

  /// <summary>
  /// Validate the current data in the model. Throws a ValidationException on
  /// failure.
  /// </summary>
  void validate() const;

  /// <summary>
  /// Validate the current data in the model. Returns false on error and writes
  /// an error message into the given stringstream.
  /// </summary>
  bool validate(std::stringstream& msg) const;

  /// <summary>
  /// Helper overload for validate. Used when one model stores another model and
  /// calls it's validate. Not meant to be called outside that case.
  /// </summary>
  bool validate(std::stringstream& msg, const std::string& pathPrefix) const;

  bool operator==(const InputData& rhs) const;
  bool operator!=(const InputData& rhs) const;

  /////////////////////////////////////////////
  /// InputData members

  /// <summary>
  ///
  /// </summary>
  oai::lmf_server::model::ExternalClientType getExternalClientType() const;
  void setExternalClientType(
      oai::lmf_server::model::ExternalClientType const& value);
  bool externalClientTypeIsSet() const;
  void unsetExternalClientType();
  /// <summary>
  ///
  /// </summary>
  std::string getCorrelationID() const;
  void setCorrelationID(std::string const& value);
  bool correlationIDIsSet() const;
  void unsetCorrelationID();
  /// <summary>
  ///
  /// </summary>
  std::string getAmfId() const;
  void setAmfId(std::string const& value);
  bool amfIdIsSet() const;
  void unsetAmfId();
  /// <summary>
  ///
  /// </summary>
  oai::lmf_server::model::LocationQoS getLocationQoS() const;
  void setLocationQoS(oai::lmf_server::model::LocationQoS const& value);
  bool locationQoSIsSet() const;
  void unsetLocationQoS();
  /// <summary>
  ///
  /// </summary>
  std::vector<oai::lmf_server::model::SupportedGADShapes>
  getSupportedGADShapes() const;
  void setSupportedGADShapes(
      std::vector<oai::lmf_server::model::SupportedGADShapes> const& value);
  bool supportedGADShapesIsSet() const;
  void unsetSupportedGADShapes();
  /// <summary>
  ///
  /// </summary>
  std::string getSupi() const;
  void setSupi(std::string const& value);
  bool supiIsSet() const;
  void unsetSupi();
  /// <summary>
  ///
  /// </summary>
  std::string getPei() const;
  void setPei(std::string const& value);
  bool peiIsSet() const;
  void unsetPei();
  /// <summary>
  ///
  /// </summary>
  std::string getGpsi() const;
  void setGpsi(std::string const& value);
  bool gpsiIsSet() const;
  void unsetGpsi();
  /// <summary>
  ///
  /// </summary>
  oai::lmf_server::model::Ecgi getEcgi() const;
  void setEcgi(oai::lmf_server::model::Ecgi const& value);
  bool ecgiIsSet() const;
  void unsetEcgi();
  /// <summary>
  ///
  /// </summary>
  oai::lmf_server::model::Ecgi getEcgiOnSecondNode() const;
  void setEcgiOnSecondNode(oai::lmf_server::model::Ecgi const& value);
  bool ecgiOnSecondNodeIsSet() const;
  void unsetEcgiOnSecondNode();
  /// <summary>
  ///
  /// </summary>
  oai::lmf_server::model::Ncgi getNcgi() const;
  void setNcgi(oai::lmf_server::model::Ncgi const& value);
  bool ncgiIsSet() const;
  void unsetNcgi();
  /// <summary>
  ///
  /// </summary>
  oai::lmf_server::model::Ncgi getNcgiOnSecondNode() const;
  void setNcgiOnSecondNode(oai::lmf_server::model::Ncgi const& value);
  bool ncgiOnSecondNodeIsSet() const;
  void unsetNcgiOnSecondNode();
  /// <summary>
  ///
  /// </summary>
  oai::lmf_server::model::LcsPriority getPriority() const;
  void setPriority(oai::lmf_server::model::LcsPriority const& value);
  bool priorityIsSet() const;
  void unsetPriority();
  /// <summary>
  ///
  /// </summary>
  oai::lmf_server::model::VelocityRequested getVelocityRequested() const;
  void setVelocityRequested(
      oai::lmf_server::model::VelocityRequested const& value);
  bool velocityRequestedIsSet() const;
  void unsetVelocityRequested();
  /// <summary>
  ///
  /// </summary>
  oai::lmf_server::model::UeLcsCapability getUeLcsCap() const;
  void setUeLcsCap(oai::lmf_server::model::UeLcsCapability const& value);
  bool ueLcsCapIsSet() const;
  void unsetUeLcsCap();
  /// <summary>
  ///
  /// </summary>
  int32_t getLcsServiceType() const;
  void setLcsServiceType(int32_t const value);
  bool lcsServiceTypeIsSet() const;
  void unsetLcsServiceType();
  /// <summary>
  ///
  /// </summary>
  oai::lmf_server::model::LdrType getLdrType() const;
  void setLdrType(oai::lmf_server::model::LdrType const& value);
  bool ldrTypeIsSet() const;
  void unsetLdrType();
  /// <summary>
  ///
  /// </summary>
  std::string getHgmlcCallBackURI() const;
  void setHgmlcCallBackURI(std::string const& value);
  bool hgmlcCallBackURIIsSet() const;
  void unsetHgmlcCallBackURI();
  /// <summary>
  ///
  /// </summary>
  std::string getVgmlcAddress() const;
  void setVgmlcAddress(std::string const& value);
  bool vgmlcAddressIsSet() const;
  void unsetVgmlcAddress();
  /// <summary>
  ///
  /// </summary>
  std::string getLdrReference() const;
  void setLdrReference(std::string const& value);
  bool ldrReferenceIsSet() const;
  void unsetLdrReference();
  /// <summary>
  ///
  /// </summary>
  oai::lmf_server::model::PeriodicEventInfo getPeriodicEventInfo() const;
  void setPeriodicEventInfo(
      oai::lmf_server::model::PeriodicEventInfo const& value);
  bool periodicEventInfoIsSet() const;
  void unsetPeriodicEventInfo();
  /// <summary>
  ///
  /// </summary>
  oai::lmf_server::model::AreaEventInfo getAreaEventInfo() const;
  void setAreaEventInfo(oai::lmf_server::model::AreaEventInfo const& value);
  bool areaEventInfoIsSet() const;
  void unsetAreaEventInfo();
  /// <summary>
  ///
  /// </summary>
  oai::lmf_server::model::MotionEventInfo getMotionEventInfo() const;
  void setMotionEventInfo(oai::lmf_server::model::MotionEventInfo const& value);
  bool motionEventInfoIsSet() const;
  void unsetMotionEventInfo();
  /// <summary>
  ///
  /// </summary>
  std::vector<oai::lmf_server::model::ReportingAccessType>
  getReportingAccessTypes() const;
  void setReportingAccessTypes(
      std::vector<oai::lmf_server::model::ReportingAccessType> const& value);
  bool reportingAccessTypesIsSet() const;
  void unsetReportingAccessTypes();
  /// <summary>
  ///
  /// </summary>
  oai::lmf_server::model::UeConnectivityState getUeConnectivityStates() const;
  void setUeConnectivityStates(
      oai::lmf_server::model::UeConnectivityState const& value);
  bool ueConnectivityStatesIsSet() const;
  void unsetUeConnectivityStates();
  /// <summary>
  ///
  /// </summary>
  oai::lmf_server::model::UeLocationServiceInd getUeLocationServiceInd() const;
  void setUeLocationServiceInd(
      oai::lmf_server::model::UeLocationServiceInd const& value);
  bool ueLocationServiceIndIsSet() const;
  void unsetUeLocationServiceInd();
  /// <summary>
  ///
  /// </summary>
  oai::lmf_server::model::RefToBinaryData getLppMessage() const;
  void setLppMessage(oai::lmf_server::model::RefToBinaryData const& value);
  bool lppMessageIsSet() const;
  void unsetLppMessage();
  /// <summary>
  ///
  /// </summary>
  std::string getSupportedFeatures() const;
  void setSupportedFeatures(std::string const& value);
  bool supportedFeaturesIsSet() const;
  void unsetSupportedFeatures();

  friend void to_json(nlohmann::json& j, const InputData& o);
  friend void from_json(const nlohmann::json& j, InputData& o);

 protected:
  oai::lmf_server::model::ExternalClientType m_ExternalClientType;
  bool m_ExternalClientTypeIsSet;
  std::string m_CorrelationID;
  bool m_CorrelationIDIsSet;
  std::string m_AmfId;
  bool m_AmfIdIsSet;
  oai::lmf_server::model::LocationQoS m_LocationQoS;
  bool m_LocationQoSIsSet;
  std::vector<oai::lmf_server::model::SupportedGADShapes> m_SupportedGADShapes;
  bool m_SupportedGADShapesIsSet;
  std::string m_Supi;
  bool m_SupiIsSet;
  std::string m_Pei;
  bool m_PeiIsSet;
  std::string m_Gpsi;
  bool m_GpsiIsSet;
  oai::lmf_server::model::Ecgi m_Ecgi;
  bool m_EcgiIsSet;
  oai::lmf_server::model::Ecgi m_EcgiOnSecondNode;
  bool m_EcgiOnSecondNodeIsSet;
  oai::lmf_server::model::Ncgi m_Ncgi;
  bool m_NcgiIsSet;
  oai::lmf_server::model::Ncgi m_NcgiOnSecondNode;
  bool m_NcgiOnSecondNodeIsSet;
  oai::lmf_server::model::LcsPriority m_Priority;
  bool m_PriorityIsSet;
  oai::lmf_server::model::VelocityRequested m_VelocityRequested;
  bool m_VelocityRequestedIsSet;
  oai::lmf_server::model::UeLcsCapability m_UeLcsCap;
  bool m_UeLcsCapIsSet;
  int32_t m_LcsServiceType;
  bool m_LcsServiceTypeIsSet;
  oai::lmf_server::model::LdrType m_LdrType;
  bool m_LdrTypeIsSet;
  std::string m_HgmlcCallBackURI;
  bool m_HgmlcCallBackURIIsSet;
  std::string m_VgmlcAddress;
  bool m_VgmlcAddressIsSet;
  std::string m_LdrReference;
  bool m_LdrReferenceIsSet;
  oai::lmf_server::model::PeriodicEventInfo m_PeriodicEventInfo;
  bool m_PeriodicEventInfoIsSet;
  oai::lmf_server::model::AreaEventInfo m_AreaEventInfo;
  bool m_AreaEventInfoIsSet;
  oai::lmf_server::model::MotionEventInfo m_MotionEventInfo;
  bool m_MotionEventInfoIsSet;
  std::vector<oai::lmf_server::model::ReportingAccessType>
      m_ReportingAccessTypes;
  bool m_ReportingAccessTypesIsSet;
  oai::lmf_server::model::UeConnectivityState m_UeConnectivityStates;
  bool m_UeConnectivityStatesIsSet;
  oai::lmf_server::model::UeLocationServiceInd m_UeLocationServiceInd;
  bool m_UeLocationServiceIndIsSet;
  oai::lmf_server::model::RefToBinaryData m_LppMessage;
  bool m_LppMessageIsSet;
  std::string m_SupportedFeatures;
  bool m_SupportedFeaturesIsSet;
};

}  // namespace oai::lmf_server::model

#endif /* InputData_H_ */
