/**
* LMF Location
* LMF Location Service. © 2019, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
*
* The version of the OpenAPI document: 1.0.4
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * LocationData.h
 *
 * 
 */

#ifndef LocationData_H_
#define LocationData_H_


#include "GnssPositioningMethodAndUsage.h"
#include "AccuracyFulfilmentIndicator.h"
#include "Ecgi.h"
#include "Ncgi.h"
#include "CivicAddress.h"
#include "GeographicArea.h"
#include "VelocityEstimate.h"
#include "PositioningMethodAndUsage.h"
#include <vector>
#include <nlohmann/json.hpp>

namespace oai::lmf_server::model
{

/// <summary>
/// 
/// </summary>
class  LocationData
{
public:
    LocationData();
    virtual ~LocationData() = default;


    /// <summary>
    /// Validate the current data in the model. Throws a ValidationException on failure.
    /// </summary>
    void validate() const;

    /// <summary>
    /// Validate the current data in the model. Returns false on error and writes an error
    /// message into the given stringstream.
    /// </summary>
    bool validate(std::stringstream& msg) const;

    /// <summary>
    /// Helper overload for validate. Used when one model stores another model and calls it's validate.
    /// Not meant to be called outside that case.
    /// </summary>
    bool validate(std::stringstream& msg, const std::string& pathPrefix) const;

    bool operator==(const LocationData& rhs) const;
    bool operator!=(const LocationData& rhs) const;

    /////////////////////////////////////////////
    /// LocationData members

    /// <summary>
    /// 
    /// </summary>
    GeographicArea getLocationEstimate() const;
    void setLocationEstimate(GeographicArea const& value);
    /// <summary>
    /// 
    /// </summary>
    AccuracyFulfilmentIndicator getAccuracyFulfilmentIndicator() const;
    void setAccuracyFulfilmentIndicator(AccuracyFulfilmentIndicator const& value);
    bool accuracyFulfilmentIndicatorIsSet() const;
    void unsetAccuracyFulfilmentIndicator();
    /// <summary>
    /// 
    /// </summary>
    int32_t getAgeOfLocationEstimate() const;
    void setAgeOfLocationEstimate(int32_t const value);
    bool ageOfLocationEstimateIsSet() const;
    void unsetAgeOfLocationEstimate();
    /// <summary>
    /// 
    /// </summary>
    VelocityEstimate getVelocityEstimate() const;
    void setVelocityEstimate(VelocityEstimate const& value);
    bool velocityEstimateIsSet() const;
    void unsetVelocityEstimate();
    /// <summary>
    /// 
    /// </summary>
    CivicAddress getCivicAddress() const;
    void setCivicAddress(CivicAddress const& value);
    bool civicAddressIsSet() const;
    void unsetCivicAddress();
    /// <summary>
    /// 
    /// </summary>
    std::vector<PositioningMethodAndUsage> getPositioningDataList() const;
    void setPositioningDataList(std::vector<PositioningMethodAndUsage> const& value);
    bool positioningDataListIsSet() const;
    void unsetPositioningDataList();
    /// <summary>
    /// 
    /// </summary>
    std::vector<GnssPositioningMethodAndUsage> getGnssPositioningDataList() const;
    void setGnssPositioningDataList(std::vector<GnssPositioningMethodAndUsage> const& value);
    bool gnssPositioningDataListIsSet() const;
    void unsetGnssPositioningDataList();
    /// <summary>
    /// 
    /// </summary>
    Ecgi getEcgi() const;
    void setEcgi(Ecgi const& value);
    bool ecgiIsSet() const;
    void unsetEcgi();
    /// <summary>
    /// 
    /// </summary>
    Ncgi getNcgi() const;
    void setNcgi(Ncgi const& value);
    bool ncgiIsSet() const;
    void unsetNcgi();
    /// <summary>
    /// 
    /// </summary>
    float getAltitude() const;
    void setAltitude(float const value);
    bool altitudeIsSet() const;
    void unsetAltitude();
    /// <summary>
    /// 
    /// </summary>
    int32_t getBarometricPressure() const;
    void setBarometricPressure(int32_t const value);
    bool barometricPressureIsSet() const;
    void unsetBarometricPressure();

    friend void to_json(nlohmann::json& j, const LocationData& o);
    friend void from_json(const nlohmann::json& j, LocationData& o);
protected:
    GeographicArea m_LocationEstimate;

    AccuracyFulfilmentIndicator m_AccuracyFulfilmentIndicator;
    bool m_AccuracyFulfilmentIndicatorIsSet;
    int32_t m_AgeOfLocationEstimate;
    bool m_AgeOfLocationEstimateIsSet;
    VelocityEstimate m_VelocityEstimate;
    bool m_VelocityEstimateIsSet;
    CivicAddress m_CivicAddress;
    bool m_CivicAddressIsSet;
    std::vector<PositioningMethodAndUsage> m_PositioningDataList;
    bool m_PositioningDataListIsSet;
    std::vector<GnssPositioningMethodAndUsage> m_GnssPositioningDataList;
    bool m_GnssPositioningDataListIsSet;
    Ecgi m_Ecgi;
    bool m_EcgiIsSet;
    Ncgi m_Ncgi;
    bool m_NcgiIsSet;
    float m_Altitude;
    bool m_AltitudeIsSet;
    int32_t m_BarometricPressure;
    bool m_BarometricPressureIsSet;
    
};

} // namespace oai::lmf_server::model

#endif /* LocationData_H_ */
