/**
 * LMF Location
 * LMF Location Service. © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA,
 * ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 1.1.5
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */
/*
 * LocContextData.h
 *
 *
 */

#ifndef LocContextData_H_
#define LocContextData_H_

#include "AreaEventInfo.h"
#include "Ecgi.h"
#include "EventReportMessage.h"
#include "EventReportingStatus.h"
#include "Guami.h"
#include "LdrType.h"
#include "LocationQoS.h"
#include "MotionEventInfo.h"
#include "Ncgi.h"
#include "PeriodicEventInfo.h"
#include "SupportedGADShapes.h"
#include "UELocationInfo.h"
#include <nlohmann/json.hpp>
#include <string>
#include <vector>

namespace oai {
namespace lmf_server {
namespace model {

/// <summary>
///
/// </summary>
class LocContextData {
public:
  LocContextData();
  virtual ~LocContextData() = default;

  /// <summary>
  /// Validate the current data in the model. Throws a ValidationException on
  /// failure.
  /// </summary>
  void validate() const;

  /// <summary>
  /// Validate the current data in the model. Returns false on error and writes
  /// an error message into the given stringstream.
  /// </summary>
  bool validate(std::stringstream &msg) const;

  /// <summary>
  /// Helper overload for validate. Used when one model stores another model and
  /// calls it's validate. Not meant to be called outside that case.
  /// </summary>
  bool validate(std::stringstream &msg, const std::string &pathPrefix) const;

  bool operator==(const LocContextData &rhs) const;
  bool operator!=(const LocContextData &rhs) const;

  /////////////////////////////////////////////
  /// LocContextData members

  /// <summary>
  ///
  /// </summary>
  std::string getAmfId() const;
  void setAmfId(std::string const &value);
  /// <summary>
  ///
  /// </summary>
  LocationQoS getLocationQoS() const;
  void setLocationQoS(LocationQoS const &value);
  bool locationQoSIsSet() const;
  void unsetLocationQoS();
  /// <summary>
  ///
  /// </summary>
  std::vector<SupportedGADShapes> getSupportedGADShapes() const;
  void setSupportedGADShapes(std::vector<SupportedGADShapes> const &value);
  bool supportedGADShapesIsSet() const;
  void unsetSupportedGADShapes();
  /// <summary>
  ///
  /// </summary>
  std::string getSupi() const;
  void setSupi(std::string const &value);
  bool supiIsSet() const;
  void unsetSupi();
  /// <summary>
  ///
  /// </summary>
  std::string getGpsi() const;
  void setGpsi(std::string const &value);
  bool gpsiIsSet() const;
  void unsetGpsi();
  /// <summary>
  ///
  /// </summary>
  LdrType getLdrType() const;
  void setLdrType(LdrType const &value);
  /// <summary>
  ///
  /// </summary>
  std::string getHgmlcCallBackURI() const;
  void setHgmlcCallBackURI(std::string const &value);
  /// <summary>
  ///
  /// </summary>
  std::string getLdrReference() const;
  void setLdrReference(std::string const &value);
  /// <summary>
  ///
  /// </summary>
  PeriodicEventInfo getPeriodicEventInfo() const;
  void setPeriodicEventInfo(PeriodicEventInfo const &value);
  bool periodicEventInfoIsSet() const;
  void unsetPeriodicEventInfo();
  /// <summary>
  ///
  /// </summary>
  AreaEventInfo getAreaEventInfo() const;
  void setAreaEventInfo(AreaEventInfo const &value);
  bool areaEventInfoIsSet() const;
  void unsetAreaEventInfo();
  /// <summary>
  ///
  /// </summary>
  MotionEventInfo getMotionEventInfo() const;
  void setMotionEventInfo(MotionEventInfo const &value);
  bool motionEventInfoIsSet() const;
  void unsetMotionEventInfo();
  /// <summary>
  ///
  /// </summary>
  EventReportMessage getEventReportMessage() const;
  void setEventReportMessage(EventReportMessage const &value);
  /// <summary>
  ///
  /// </summary>
  EventReportingStatus getEventReportingStatus() const;
  void setEventReportingStatus(EventReportingStatus const &value);
  bool eventReportingStatusIsSet() const;
  void unsetEventReportingStatus();
  /// <summary>
  ///
  /// </summary>
  UELocationInfo getUeLocationInfo() const;
  void setUeLocationInfo(UELocationInfo const &value);
  bool ueLocationInfoIsSet() const;
  void unsetUeLocationInfo();
  /// <summary>
  ///
  /// </summary>
  bool isCIoT5GSOptimisation() const;
  void setCIoT5GSOptimisation(bool const value);
  bool cIoT5GSOptimisationIsSet() const;
  void unsetCIoT5GSOptimisation();
  /// <summary>
  ///
  /// </summary>
  Ecgi getEcgi() const;
  void setEcgi(Ecgi const &value);
  bool ecgiIsSet() const;
  void unsetEcgi();
  /// <summary>
  ///
  /// </summary>
  Ncgi getNcgi() const;
  void setNcgi(Ncgi const &value);
  bool ncgiIsSet() const;
  void unsetNcgi();
  /// <summary>
  ///
  /// </summary>
  Guami getGuami() const;
  void setGuami(Guami const &value);
  bool guamiIsSet() const;
  void unsetGuami();
  /// <summary>
  ///
  /// </summary>
  std::string getSupportedFeatures() const;
  void setSupportedFeatures(std::string const &value);
  bool supportedFeaturesIsSet() const;
  void unsetSupportedFeatures();

  friend void to_json(nlohmann::json &j, const LocContextData &o);
  friend void from_json(const nlohmann::json &j, LocContextData &o);

protected:
  std::string m_AmfId;

  LocationQoS m_LocationQoS;
  bool m_LocationQoSIsSet;
  std::vector<SupportedGADShapes> m_SupportedGADShapes;
  bool m_SupportedGADShapesIsSet;
  std::string m_Supi;
  bool m_SupiIsSet;
  std::string m_Gpsi;
  bool m_GpsiIsSet;
  LdrType m_LdrType;

  std::string m_HgmlcCallBackURI;

  std::string m_LdrReference;

  PeriodicEventInfo m_PeriodicEventInfo;
  bool m_PeriodicEventInfoIsSet;
  AreaEventInfo m_AreaEventInfo;
  bool m_AreaEventInfoIsSet;
  MotionEventInfo m_MotionEventInfo;
  bool m_MotionEventInfoIsSet;
  EventReportMessage m_EventReportMessage;

  EventReportingStatus m_EventReportingStatus;
  bool m_EventReportingStatusIsSet;
  UELocationInfo m_UeLocationInfo;
  bool m_UeLocationInfoIsSet;
  bool m_CIoT5GSOptimisation;
  bool m_CIoT5GSOptimisationIsSet;
  Ecgi m_Ecgi;
  bool m_EcgiIsSet;
  Ncgi m_Ncgi;
  bool m_NcgiIsSet;
  Guami m_Guami;
  bool m_GuamiIsSet;
  std::string m_SupportedFeatures;
  bool m_SupportedFeaturesIsSet;
};

} // namespace model
} // namespace lmf_server
} // namespace oai

#endif /* LocContextData_H_ */
