/**
* Namf_Communication
* AMF Communication Service © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
*
* The version of the OpenAPI document: 1.0.8
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * N2SmInformation.h
 *
 * 
 */

#ifndef N2SmInformation_H_
#define N2SmInformation_H_


#include "N2InfoContent.h"
#include "Snssai.h"
#include <nlohmann/json.hpp>

namespace oai::lmf_server::model
{

/// <summary>
/// 
/// </summary>
class  N2SmInformation
{
public:
    N2SmInformation();
    virtual ~N2SmInformation() = default;


    /// <summary>
    /// Validate the current data in the model. Throws a ValidationException on failure.
    /// </summary>
    void validate() const;

    /// <summary>
    /// Validate the current data in the model. Returns false on error and writes an error
    /// message into the given stringstream.
    /// </summary>
    bool validate(std::stringstream& msg) const;

    /// <summary>
    /// Helper overload for validate. Used when one model stores another model and calls it's validate.
    /// Not meant to be called outside that case.
    /// </summary>
    bool validate(std::stringstream& msg, const std::string& pathPrefix) const;

    bool operator==(const N2SmInformation& rhs) const;
    bool operator!=(const N2SmInformation& rhs) const;

    /////////////////////////////////////////////
    /// N2SmInformation members

    /// <summary>
    /// 
    /// </summary>
    int32_t getPduSessionId() const;
    void setPduSessionId(int32_t const value);
    /// <summary>
    /// 
    /// </summary>
    N2InfoContent getN2InfoContent() const;
    void setN2InfoContent(N2InfoContent const& value);
    bool n2InfoContentIsSet() const;
    void unsetN2InfoContent();
    /// <summary>
    /// 
    /// </summary>
    Snssai getSNssai() const;
    void setSNssai(Snssai const& value);
    bool sNssaiIsSet() const;
    void unsetSNssai();
    /// <summary>
    /// 
    /// </summary>
    bool isSubjectToHo() const;
    void setSubjectToHo(bool const value);
    bool subjectToHoIsSet() const;
    void unsetSubjectToHo();

    friend void to_json(nlohmann::json& j, const N2SmInformation& o);
    friend void from_json(const nlohmann::json& j, N2SmInformation& o);
protected:
    int32_t m_PduSessionId;

    N2InfoContent m_N2InfoContent;
    bool m_N2InfoContentIsSet;
    Snssai m_SNssai;
    bool m_SNssaiIsSet;
    bool m_SubjectToHo;
    bool m_SubjectToHoIsSet;
    
};

} // namespace oai::lmf_server::model

#endif /* N2SmInformation_H_ */
