/**
* Common Data Types
* Common Data Types for Service Based Interfaces. © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
*
* The version of the OpenAPI document: 1.2.7
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * NssaaStatus.h
 *
 * 
 */

#ifndef NssaaStatus_H_
#define NssaaStatus_H_


#include "AuthStatus.h"
#include "Snssai.h"
#include <nlohmann/json.hpp>

namespace oai::lmf_server::model
{

/// <summary>
/// 
/// </summary>
class  NssaaStatus
{
public:
    NssaaStatus();
    virtual ~NssaaStatus() = default;


    /// <summary>
    /// Validate the current data in the model. Throws a ValidationException on failure.
    /// </summary>
    void validate() const;

    /// <summary>
    /// Validate the current data in the model. Returns false on error and writes an error
    /// message into the given stringstream.
    /// </summary>
    bool validate(std::stringstream& msg) const;

    /// <summary>
    /// Helper overload for validate. Used when one model stores another model and calls it's validate.
    /// Not meant to be called outside that case.
    /// </summary>
    bool validate(std::stringstream& msg, const std::string& pathPrefix) const;

    bool operator==(const NssaaStatus& rhs) const;
    bool operator!=(const NssaaStatus& rhs) const;

    /////////////////////////////////////////////
    /// NssaaStatus members

    /// <summary>
    /// 
    /// </summary>
    oai::lmf_server::model::Snssai getSnssai() const;
    void setSnssai(oai::lmf_server::model::Snssai const& value);
    /// <summary>
    /// 
    /// </summary>
    oai::lmf_server::model::AuthStatus getStatus() const;
    void setStatus(oai::lmf_server::model::AuthStatus const& value);

    friend void to_json(nlohmann::json& j, const NssaaStatus& o);
    friend void from_json(const nlohmann::json& j, NssaaStatus& o);
protected:
    oai::lmf_server::model::Snssai m_Snssai;

    oai::lmf_server::model::AuthStatus m_Status;

    
};

} // namespace oai::lmf_server::model

#endif /* NssaaStatus_H_ */
