/**
* Common Data Types
* Common Data Types for Service Based Interfaces. © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
*
* The version of the OpenAPI document: 1.2.7
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#include "PlmnIdNid_1.h"
#include "Helpers.h"

#include <sstream>

namespace oai::lmf_server::model
{

PlmnIdNid_1::PlmnIdNid_1()
{
    m_Mcc = "";
    m_Mnc = "";
    m_Nid = "";
    m_NidIsSet = false;
    
}

void PlmnIdNid_1::validate() const
{
    std::stringstream msg;
    if (!validate(msg))
    {
        throw org::openapitools::server::helpers::ValidationException(msg.str());
    }
}

bool PlmnIdNid_1::validate(std::stringstream& msg) const
{
    return validate(msg, "");
}

bool PlmnIdNid_1::validate(std::stringstream& msg, const std::string& pathPrefix) const
{
    bool success = true;
    const std::string _pathPrefix = pathPrefix.empty() ? "PlmnIdNid_1" : pathPrefix;

         
    
    /* Mcc */ {
        const std::string& value = m_Mcc;
        const std::string currentValuePath = _pathPrefix + ".mcc";
                
        

    }
         
    
    /* Mnc */ {
        const std::string& value = m_Mnc;
        const std::string currentValuePath = _pathPrefix + ".mnc";
                
        

    }
         
    if (nidIsSet())
    {
        const std::string& value = m_Nid;
        const std::string currentValuePath = _pathPrefix + ".nid";
                
        

    }
    
    return success;
}

bool PlmnIdNid_1::operator==(const PlmnIdNid_1& rhs) const
{
    return
    
    
    (getMcc() == rhs.getMcc())
     &&
    
    (getMnc() == rhs.getMnc())
     &&
    
    
    ((!nidIsSet() && !rhs.nidIsSet()) || (nidIsSet() && rhs.nidIsSet() && getNid() == rhs.getNid()))
    
    ;
}

bool PlmnIdNid_1::operator!=(const PlmnIdNid_1& rhs) const
{
    return !(*this == rhs);
}

void to_json(nlohmann::json& j, const PlmnIdNid_1& o)
{
    j = nlohmann::json();
    j["mcc"] = o.m_Mcc;
    j["mnc"] = o.m_Mnc;
    if(o.nidIsSet())
        j["nid"] = o.m_Nid;
    
}

void from_json(const nlohmann::json& j, PlmnIdNid_1& o)
{
    j.at("mcc").get_to(o.m_Mcc);
    j.at("mnc").get_to(o.m_Mnc);
    if(j.find("nid") != j.end())
    {
        j.at("nid").get_to(o.m_Nid);
        o.m_NidIsSet = true;
    } 
    
}

std::string PlmnIdNid_1::getMcc() const
{
    return m_Mcc;
}
void PlmnIdNid_1::setMcc(std::string const& value)
{
    m_Mcc = value;
}
std::string PlmnIdNid_1::getMnc() const
{
    return m_Mnc;
}
void PlmnIdNid_1::setMnc(std::string const& value)
{
    m_Mnc = value;
}
std::string PlmnIdNid_1::getNid() const
{
    return m_Nid;
}
void PlmnIdNid_1::setNid(std::string const& value)
{
    m_Nid = value;
    m_NidIsSet = true;
}
bool PlmnIdNid_1::nidIsSet() const
{
    return m_NidIsSet;
}
void PlmnIdNid_1::unsetNid()
{
    m_NidIsSet = false;
}


} // namespace oai::lmf_server::model

