/**
 * LMF Location
 * LMF Location Service. © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA,
 * ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 1.1.5
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */
/*
 * PointUncertaintyEllipse.h
 *
 *
 */

#ifndef PointUncertaintyEllipse_H_
#define PointUncertaintyEllipse_H_

#include "GADShape.h"
#include "GeographicalCoordinates.h"
#include "SupportedGADShapes.h"
#include "UncertaintyEllipse.h"
#include <nlohmann/json.hpp>

namespace oai {
namespace lmf_server {
namespace model {

/// <summary>
///
/// </summary>
class PointUncertaintyEllipse {
public:
  PointUncertaintyEllipse();
  virtual ~PointUncertaintyEllipse() = default;

  /// <summary>
  /// Validate the current data in the model. Throws a ValidationException on
  /// failure.
  /// </summary>
  void validate() const;

  /// <summary>
  /// Validate the current data in the model. Returns false on error and writes
  /// an error message into the given stringstream.
  /// </summary>
  bool validate(std::stringstream &msg) const;

  /// <summary>
  /// Helper overload for validate. Used when one model stores another model and
  /// calls it's validate. Not meant to be called outside that case.
  /// </summary>
  bool validate(std::stringstream &msg, const std::string &pathPrefix) const;

  bool operator==(const PointUncertaintyEllipse &rhs) const;
  bool operator!=(const PointUncertaintyEllipse &rhs) const;

  /////////////////////////////////////////////
  /// PointUncertaintyEllipse members

  /// <summary>
  ///
  /// </summary>
  SupportedGADShapes getShape() const;
  void setShape(SupportedGADShapes const &value);
  /// <summary>
  ///
  /// </summary>
  GeographicalCoordinates getPoint() const;
  void setPoint(GeographicalCoordinates const &value);
  /// <summary>
  ///
  /// </summary>
  UncertaintyEllipse getUncertaintyEllipse() const;
  void setUncertaintyEllipse(UncertaintyEllipse const &value);
  /// <summary>
  ///
  /// </summary>
  int32_t getConfidence() const;
  void setConfidence(int32_t const value);

  friend void to_json(nlohmann::json &j, const PointUncertaintyEllipse &o);
  friend void from_json(const nlohmann::json &j, PointUncertaintyEllipse &o);

protected:
  SupportedGADShapes m_Shape;

  GeographicalCoordinates m_Point;

  UncertaintyEllipse m_UncertaintyEllipse;

  int32_t m_Confidence;
};

} // namespace model
} // namespace lmf_server
} // namespace oai

#endif /* PointUncertaintyEllipse_H_ */
