/**
* LMF Location
* LMF Location Service. © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
*
* The version of the OpenAPI document: 1.1.5
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * ReportingArea.h
 *
 * 
 */

#ifndef ReportingArea_H_
#define ReportingArea_H_


#include "Ecgi.h"
#include "Ncgi.h"
#include "Tai.h"
#include "ReportingAreaType.h"
#include <nlohmann/json.hpp>

namespace oai::lmf_server::model
{

/// <summary>
/// 
/// </summary>
class  ReportingArea
{
public:
    ReportingArea();
    virtual ~ReportingArea() = default;


    /// <summary>
    /// Validate the current data in the model. Throws a ValidationException on failure.
    /// </summary>
    void validate() const;

    /// <summary>
    /// Validate the current data in the model. Returns false on error and writes an error
    /// message into the given stringstream.
    /// </summary>
    bool validate(std::stringstream& msg) const;

    /// <summary>
    /// Helper overload for validate. Used when one model stores another model and calls it's validate.
    /// Not meant to be called outside that case.
    /// </summary>
    bool validate(std::stringstream& msg, const std::string& pathPrefix) const;

    bool operator==(const ReportingArea& rhs) const;
    bool operator!=(const ReportingArea& rhs) const;

    /////////////////////////////////////////////
    /// ReportingArea members

    /// <summary>
    /// 
    /// </summary>
    oai::lmf_server::model::ReportingAreaType getAreaType() const;
    void setAreaType(oai::lmf_server::model::ReportingAreaType const& value);
    /// <summary>
    /// 
    /// </summary>
    oai::lmf_server::model::Tai getTai() const;
    void setTai(oai::lmf_server::model::Tai const& value);
    bool taiIsSet() const;
    void unsetTai();
    /// <summary>
    /// 
    /// </summary>
    oai::lmf_server::model::Ecgi getEcgi() const;
    void setEcgi(oai::lmf_server::model::Ecgi const& value);
    bool ecgiIsSet() const;
    void unsetEcgi();
    /// <summary>
    /// 
    /// </summary>
    oai::lmf_server::model::Ncgi getNcgi() const;
    void setNcgi(oai::lmf_server::model::Ncgi const& value);
    bool ncgiIsSet() const;
    void unsetNcgi();

    friend void to_json(nlohmann::json& j, const ReportingArea& o);
    friend void from_json(const nlohmann::json& j, ReportingArea& o);
protected:
    oai::lmf_server::model::ReportingAreaType m_AreaType;

    oai::lmf_server::model::Tai m_Tai;
    bool m_TaiIsSet;
    oai::lmf_server::model::Ecgi m_Ecgi;
    bool m_EcgiIsSet;
    oai::lmf_server::model::Ncgi m_Ncgi;
    bool m_NcgiIsSet;
    
};

} // namespace oai::lmf_server::model

#endif /* ReportingArea_H_ */
