/**
 * LMF Broadcast
 * LMF Broadcast Service. © 2021, 3GPP Organizational Partners (ARIB, ATIS,
 * CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 1.0.3
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

#include "StorageOutcome.h"
#include "Helpers.h"

#include <sstream>

namespace oai {
namespace lmf_server {
namespace model {

StorageOutcome::StorageOutcome() {}

void StorageOutcome::validate() const {
  std::stringstream msg;
  if (!validate(msg)) {
    throw oai::lmf_server::helpers::ValidationException(msg.str());
  }
}

bool StorageOutcome::validate(std::stringstream &msg) const {
  return validate(msg, "");
}

bool StorageOutcome::validate(std::stringstream &msg,
                              const std::string &pathPrefix) const {
  bool success = true;
  const std::string _pathPrefix =
      pathPrefix.empty() ? "StorageOutcome" : pathPrefix;

  return success;
}

bool StorageOutcome::operator==(const StorageOutcome &rhs) const {
  return false;
}

bool StorageOutcome::operator!=(const StorageOutcome &rhs) const {
  return !(*this == rhs);
}

void to_json(nlohmann::json &j, const StorageOutcome &o) {
  j = nlohmann::json();
}

void from_json(const nlohmann::json &j, StorageOutcome &o) {}

} // namespace model
} // namespace lmf_server
} // namespace oai
