/**
* LMF Location
* LMF Location Service. © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
*
* The version of the OpenAPI document: 1.1.3
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * UeConnectivityState.h
 *
 * 
 */

#ifndef UeConnectivityState_H_
#define UeConnectivityState_H_


#include "CmState.h"
#include "AccessType.h"
#include <nlohmann/json.hpp>

namespace oai::lmf_server::model
{

/// <summary>
/// 
/// </summary>
class  UeConnectivityState
{
public:
    UeConnectivityState();
    virtual ~UeConnectivityState() = default;


    /// <summary>
    /// Validate the current data in the model. Throws a ValidationException on failure.
    /// </summary>
    void validate() const;

    /// <summary>
    /// Validate the current data in the model. Returns false on error and writes an error
    /// message into the given stringstream.
    /// </summary>
    bool validate(std::stringstream& msg) const;

    /// <summary>
    /// Helper overload for validate. Used when one model stores another model and calls it's validate.
    /// Not meant to be called outside that case.
    /// </summary>
    bool validate(std::stringstream& msg, const std::string& pathPrefix) const;

    bool operator==(const UeConnectivityState& rhs) const;
    bool operator!=(const UeConnectivityState& rhs) const;

    /////////////////////////////////////////////
    /// UeConnectivityState members

    /// <summary>
    /// 
    /// </summary>
    oai::lmf_server::model::AccessType getAccessType() const;
    void setAccessType(oai::lmf_server::model::AccessType const& value);
    /// <summary>
    /// 
    /// </summary>
    oai::lmf_server::model::CmState getConnectivitystate() const;
    void setConnectivitystate(oai::lmf_server::model::CmState const& value);
    bool connectivitystateIsSet() const;
    void unsetConnectivitystate();

    friend void to_json(nlohmann::json& j, const UeConnectivityState& o);
    friend void from_json(const nlohmann::json& j, UeConnectivityState& o);
protected:
    oai::lmf_server::model::AccessType m_AccessType;

    oai::lmf_server::model::CmState m_Connectivitystate;
    bool m_ConnectivitystateIsSet;
    
};

} // namespace oai::lmf_server::model

#endif /* UeConnectivityState_H_ */
