/**
* Common Data Types
* Common Data Types for Service Based Interfaces. © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
*
* The version of the OpenAPI document: 1.2.7
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * UserLocation.h
 *
 * 
 */

#ifndef UserLocation_H_
#define UserLocation_H_


#include "EutraLocation.h"
#include "GeraLocation.h"
#include "NrLocation.h"
#include "UtraLocation.h"
#include "N3gaLocation.h"
#include <nlohmann/json.hpp>

namespace oai::lmf_server::model
{

/// <summary>
/// 
/// </summary>
class  UserLocation
{
public:
    UserLocation();
    virtual ~UserLocation() = default;


    /// <summary>
    /// Validate the current data in the model. Throws a ValidationException on failure.
    /// </summary>
    void validate() const;

    /// <summary>
    /// Validate the current data in the model. Returns false on error and writes an error
    /// message into the given stringstream.
    /// </summary>
    bool validate(std::stringstream& msg) const;

    /// <summary>
    /// Helper overload for validate. Used when one model stores another model and calls it's validate.
    /// Not meant to be called outside that case.
    /// </summary>
    bool validate(std::stringstream& msg, const std::string& pathPrefix) const;

    bool operator==(const UserLocation& rhs) const;
    bool operator!=(const UserLocation& rhs) const;

    /////////////////////////////////////////////
    /// UserLocation members

    /// <summary>
    /// 
    /// </summary>
    oai::lmf_server::model::EutraLocation getEutraLocation() const;
    void setEutraLocation(oai::lmf_server::model::EutraLocation const& value);
    bool eutraLocationIsSet() const;
    void unsetEutraLocation();
    /// <summary>
    /// 
    /// </summary>
    oai::lmf_server::model::NrLocation getNrLocation() const;
    void setNrLocation(oai::lmf_server::model::NrLocation const& value);
    bool nrLocationIsSet() const;
    void unsetNrLocation();
    /// <summary>
    /// 
    /// </summary>
    oai::lmf_server::model::N3gaLocation getN3gaLocation() const;
    void setN3gaLocation(oai::lmf_server::model::N3gaLocation const& value);
    bool n3gaLocationIsSet() const;
    void unsetN3gaLocation();
    /// <summary>
    /// 
    /// </summary>
    oai::lmf_server::model::UtraLocation getUtraLocation() const;
    void setUtraLocation(oai::lmf_server::model::UtraLocation const& value);
    bool utraLocationIsSet() const;
    void unsetUtraLocation();
    /// <summary>
    /// 
    /// </summary>
    oai::lmf_server::model::GeraLocation getGeraLocation() const;
    void setGeraLocation(oai::lmf_server::model::GeraLocation const& value);
    bool geraLocationIsSet() const;
    void unsetGeraLocation();

    friend void to_json(nlohmann::json& j, const UserLocation& o);
    friend void from_json(const nlohmann::json& j, UserLocation& o);
protected:
    oai::lmf_server::model::EutraLocation m_EutraLocation;
    bool m_EutraLocationIsSet;
    oai::lmf_server::model::NrLocation m_NrLocation;
    bool m_NrLocationIsSet;
    oai::lmf_server::model::N3gaLocation m_N3gaLocation;
    bool m_N3gaLocationIsSet;
    oai::lmf_server::model::UtraLocation m_UtraLocation;
    bool m_UtraLocationIsSet;
    oai::lmf_server::model::GeraLocation m_GeraLocation;
    bool m_GeraLocationIsSet;
    
};

} // namespace oai::lmf_server::model

#endif /* UserLocation_H_ */
